
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `AgentRun` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model AgentRun
 * 
 */
export type AgentRunModel = runtime.Types.Result.DefaultSelection<Prisma.$AgentRunPayload>

export type AggregateAgentRun = {
  _count: AgentRunCountAggregateOutputType | null
  _min: AgentRunMinAggregateOutputType | null
  _max: AgentRunMaxAggregateOutputType | null
}

export type AgentRunMinAggregateOutputType = {
  id: string | null
  agentId: string | null
  status: string | null
  steps: string | null
  result: string | null
  error: string | null
  startedAt: Date | null
  completedAt: Date | null
  createdAt: Date | null
}

export type AgentRunMaxAggregateOutputType = {
  id: string | null
  agentId: string | null
  status: string | null
  steps: string | null
  result: string | null
  error: string | null
  startedAt: Date | null
  completedAt: Date | null
  createdAt: Date | null
}

export type AgentRunCountAggregateOutputType = {
  id: number
  agentId: number
  status: number
  steps: number
  result: number
  error: number
  startedAt: number
  completedAt: number
  createdAt: number
  _all: number
}


export type AgentRunMinAggregateInputType = {
  id?: true
  agentId?: true
  status?: true
  steps?: true
  result?: true
  error?: true
  startedAt?: true
  completedAt?: true
  createdAt?: true
}

export type AgentRunMaxAggregateInputType = {
  id?: true
  agentId?: true
  status?: true
  steps?: true
  result?: true
  error?: true
  startedAt?: true
  completedAt?: true
  createdAt?: true
}

export type AgentRunCountAggregateInputType = {
  id?: true
  agentId?: true
  status?: true
  steps?: true
  result?: true
  error?: true
  startedAt?: true
  completedAt?: true
  createdAt?: true
  _all?: true
}

export type AgentRunAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AgentRun to aggregate.
   */
  where?: Prisma.AgentRunWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AgentRuns to fetch.
   */
  orderBy?: Prisma.AgentRunOrderByWithRelationInput | Prisma.AgentRunOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AgentRunWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AgentRuns from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AgentRuns.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned AgentRuns
  **/
  _count?: true | AgentRunCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AgentRunMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AgentRunMaxAggregateInputType
}

export type GetAgentRunAggregateType<T extends AgentRunAggregateArgs> = {
      [P in keyof T & keyof AggregateAgentRun]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAgentRun[P]>
    : Prisma.GetScalarType<T[P], AggregateAgentRun[P]>
}




export type AgentRunGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AgentRunWhereInput
  orderBy?: Prisma.AgentRunOrderByWithAggregationInput | Prisma.AgentRunOrderByWithAggregationInput[]
  by: Prisma.AgentRunScalarFieldEnum[] | Prisma.AgentRunScalarFieldEnum
  having?: Prisma.AgentRunScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AgentRunCountAggregateInputType | true
  _min?: AgentRunMinAggregateInputType
  _max?: AgentRunMaxAggregateInputType
}

export type AgentRunGroupByOutputType = {
  id: string
  agentId: string
  status: string
  steps: string
  result: string | null
  error: string | null
  startedAt: Date | null
  completedAt: Date | null
  createdAt: Date
  _count: AgentRunCountAggregateOutputType | null
  _min: AgentRunMinAggregateOutputType | null
  _max: AgentRunMaxAggregateOutputType | null
}

export type GetAgentRunGroupByPayload<T extends AgentRunGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AgentRunGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AgentRunGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AgentRunGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AgentRunGroupByOutputType[P]>
      }
    >
  >



export type AgentRunWhereInput = {
  AND?: Prisma.AgentRunWhereInput | Prisma.AgentRunWhereInput[]
  OR?: Prisma.AgentRunWhereInput[]
  NOT?: Prisma.AgentRunWhereInput | Prisma.AgentRunWhereInput[]
  id?: Prisma.StringFilter<"AgentRun"> | string
  agentId?: Prisma.StringFilter<"AgentRun"> | string
  status?: Prisma.StringFilter<"AgentRun"> | string
  steps?: Prisma.StringFilter<"AgentRun"> | string
  result?: Prisma.StringNullableFilter<"AgentRun"> | string | null
  error?: Prisma.StringNullableFilter<"AgentRun"> | string | null
  startedAt?: Prisma.DateTimeNullableFilter<"AgentRun"> | Date | string | null
  completedAt?: Prisma.DateTimeNullableFilter<"AgentRun"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"AgentRun"> | Date | string
  agent?: Prisma.XOR<Prisma.AgentScalarRelationFilter, Prisma.AgentWhereInput>
}

export type AgentRunOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  agentId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  steps?: Prisma.SortOrder
  result?: Prisma.SortOrderInput | Prisma.SortOrder
  error?: Prisma.SortOrderInput | Prisma.SortOrder
  startedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  completedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  agent?: Prisma.AgentOrderByWithRelationInput
}

export type AgentRunWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.AgentRunWhereInput | Prisma.AgentRunWhereInput[]
  OR?: Prisma.AgentRunWhereInput[]
  NOT?: Prisma.AgentRunWhereInput | Prisma.AgentRunWhereInput[]
  agentId?: Prisma.StringFilter<"AgentRun"> | string
  status?: Prisma.StringFilter<"AgentRun"> | string
  steps?: Prisma.StringFilter<"AgentRun"> | string
  result?: Prisma.StringNullableFilter<"AgentRun"> | string | null
  error?: Prisma.StringNullableFilter<"AgentRun"> | string | null
  startedAt?: Prisma.DateTimeNullableFilter<"AgentRun"> | Date | string | null
  completedAt?: Prisma.DateTimeNullableFilter<"AgentRun"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"AgentRun"> | Date | string
  agent?: Prisma.XOR<Prisma.AgentScalarRelationFilter, Prisma.AgentWhereInput>
}, "id">

export type AgentRunOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  agentId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  steps?: Prisma.SortOrder
  result?: Prisma.SortOrderInput | Prisma.SortOrder
  error?: Prisma.SortOrderInput | Prisma.SortOrder
  startedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  completedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.AgentRunCountOrderByAggregateInput
  _max?: Prisma.AgentRunMaxOrderByAggregateInput
  _min?: Prisma.AgentRunMinOrderByAggregateInput
}

export type AgentRunScalarWhereWithAggregatesInput = {
  AND?: Prisma.AgentRunScalarWhereWithAggregatesInput | Prisma.AgentRunScalarWhereWithAggregatesInput[]
  OR?: Prisma.AgentRunScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AgentRunScalarWhereWithAggregatesInput | Prisma.AgentRunScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"AgentRun"> | string
  agentId?: Prisma.StringWithAggregatesFilter<"AgentRun"> | string
  status?: Prisma.StringWithAggregatesFilter<"AgentRun"> | string
  steps?: Prisma.StringWithAggregatesFilter<"AgentRun"> | string
  result?: Prisma.StringNullableWithAggregatesFilter<"AgentRun"> | string | null
  error?: Prisma.StringNullableWithAggregatesFilter<"AgentRun"> | string | null
  startedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"AgentRun"> | Date | string | null
  completedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"AgentRun"> | Date | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"AgentRun"> | Date | string
}

export type AgentRunCreateInput = {
  id?: string
  status?: string
  steps?: string
  result?: string | null
  error?: string | null
  startedAt?: Date | string | null
  completedAt?: Date | string | null
  createdAt?: Date | string
  agent: Prisma.AgentCreateNestedOneWithoutRunsInput
}

export type AgentRunUncheckedCreateInput = {
  id?: string
  agentId: string
  status?: string
  steps?: string
  result?: string | null
  error?: string | null
  startedAt?: Date | string | null
  completedAt?: Date | string | null
  createdAt?: Date | string
}

export type AgentRunUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  steps?: Prisma.StringFieldUpdateOperationsInput | string
  result?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  error?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  startedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  agent?: Prisma.AgentUpdateOneRequiredWithoutRunsNestedInput
}

export type AgentRunUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  agentId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  steps?: Prisma.StringFieldUpdateOperationsInput | string
  result?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  error?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  startedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AgentRunCreateManyInput = {
  id?: string
  agentId: string
  status?: string
  steps?: string
  result?: string | null
  error?: string | null
  startedAt?: Date | string | null
  completedAt?: Date | string | null
  createdAt?: Date | string
}

export type AgentRunUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  steps?: Prisma.StringFieldUpdateOperationsInput | string
  result?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  error?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  startedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AgentRunUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  agentId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  steps?: Prisma.StringFieldUpdateOperationsInput | string
  result?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  error?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  startedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AgentRunListRelationFilter = {
  every?: Prisma.AgentRunWhereInput
  some?: Prisma.AgentRunWhereInput
  none?: Prisma.AgentRunWhereInput
}

export type AgentRunOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type AgentRunCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  agentId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  steps?: Prisma.SortOrder
  result?: Prisma.SortOrder
  error?: Prisma.SortOrder
  startedAt?: Prisma.SortOrder
  completedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type AgentRunMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  agentId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  steps?: Prisma.SortOrder
  result?: Prisma.SortOrder
  error?: Prisma.SortOrder
  startedAt?: Prisma.SortOrder
  completedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type AgentRunMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  agentId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  steps?: Prisma.SortOrder
  result?: Prisma.SortOrder
  error?: Prisma.SortOrder
  startedAt?: Prisma.SortOrder
  completedAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type AgentRunCreateNestedManyWithoutAgentInput = {
  create?: Prisma.XOR<Prisma.AgentRunCreateWithoutAgentInput, Prisma.AgentRunUncheckedCreateWithoutAgentInput> | Prisma.AgentRunCreateWithoutAgentInput[] | Prisma.AgentRunUncheckedCreateWithoutAgentInput[]
  connectOrCreate?: Prisma.AgentRunCreateOrConnectWithoutAgentInput | Prisma.AgentRunCreateOrConnectWithoutAgentInput[]
  createMany?: Prisma.AgentRunCreateManyAgentInputEnvelope
  connect?: Prisma.AgentRunWhereUniqueInput | Prisma.AgentRunWhereUniqueInput[]
}

export type AgentRunUncheckedCreateNestedManyWithoutAgentInput = {
  create?: Prisma.XOR<Prisma.AgentRunCreateWithoutAgentInput, Prisma.AgentRunUncheckedCreateWithoutAgentInput> | Prisma.AgentRunCreateWithoutAgentInput[] | Prisma.AgentRunUncheckedCreateWithoutAgentInput[]
  connectOrCreate?: Prisma.AgentRunCreateOrConnectWithoutAgentInput | Prisma.AgentRunCreateOrConnectWithoutAgentInput[]
  createMany?: Prisma.AgentRunCreateManyAgentInputEnvelope
  connect?: Prisma.AgentRunWhereUniqueInput | Prisma.AgentRunWhereUniqueInput[]
}

export type AgentRunUpdateManyWithoutAgentNestedInput = {
  create?: Prisma.XOR<Prisma.AgentRunCreateWithoutAgentInput, Prisma.AgentRunUncheckedCreateWithoutAgentInput> | Prisma.AgentRunCreateWithoutAgentInput[] | Prisma.AgentRunUncheckedCreateWithoutAgentInput[]
  connectOrCreate?: Prisma.AgentRunCreateOrConnectWithoutAgentInput | Prisma.AgentRunCreateOrConnectWithoutAgentInput[]
  upsert?: Prisma.AgentRunUpsertWithWhereUniqueWithoutAgentInput | Prisma.AgentRunUpsertWithWhereUniqueWithoutAgentInput[]
  createMany?: Prisma.AgentRunCreateManyAgentInputEnvelope
  set?: Prisma.AgentRunWhereUniqueInput | Prisma.AgentRunWhereUniqueInput[]
  disconnect?: Prisma.AgentRunWhereUniqueInput | Prisma.AgentRunWhereUniqueInput[]
  delete?: Prisma.AgentRunWhereUniqueInput | Prisma.AgentRunWhereUniqueInput[]
  connect?: Prisma.AgentRunWhereUniqueInput | Prisma.AgentRunWhereUniqueInput[]
  update?: Prisma.AgentRunUpdateWithWhereUniqueWithoutAgentInput | Prisma.AgentRunUpdateWithWhereUniqueWithoutAgentInput[]
  updateMany?: Prisma.AgentRunUpdateManyWithWhereWithoutAgentInput | Prisma.AgentRunUpdateManyWithWhereWithoutAgentInput[]
  deleteMany?: Prisma.AgentRunScalarWhereInput | Prisma.AgentRunScalarWhereInput[]
}

export type AgentRunUncheckedUpdateManyWithoutAgentNestedInput = {
  create?: Prisma.XOR<Prisma.AgentRunCreateWithoutAgentInput, Prisma.AgentRunUncheckedCreateWithoutAgentInput> | Prisma.AgentRunCreateWithoutAgentInput[] | Prisma.AgentRunUncheckedCreateWithoutAgentInput[]
  connectOrCreate?: Prisma.AgentRunCreateOrConnectWithoutAgentInput | Prisma.AgentRunCreateOrConnectWithoutAgentInput[]
  upsert?: Prisma.AgentRunUpsertWithWhereUniqueWithoutAgentInput | Prisma.AgentRunUpsertWithWhereUniqueWithoutAgentInput[]
  createMany?: Prisma.AgentRunCreateManyAgentInputEnvelope
  set?: Prisma.AgentRunWhereUniqueInput | Prisma.AgentRunWhereUniqueInput[]
  disconnect?: Prisma.AgentRunWhereUniqueInput | Prisma.AgentRunWhereUniqueInput[]
  delete?: Prisma.AgentRunWhereUniqueInput | Prisma.AgentRunWhereUniqueInput[]
  connect?: Prisma.AgentRunWhereUniqueInput | Prisma.AgentRunWhereUniqueInput[]
  update?: Prisma.AgentRunUpdateWithWhereUniqueWithoutAgentInput | Prisma.AgentRunUpdateWithWhereUniqueWithoutAgentInput[]
  updateMany?: Prisma.AgentRunUpdateManyWithWhereWithoutAgentInput | Prisma.AgentRunUpdateManyWithWhereWithoutAgentInput[]
  deleteMany?: Prisma.AgentRunScalarWhereInput | Prisma.AgentRunScalarWhereInput[]
}

export type AgentRunCreateWithoutAgentInput = {
  id?: string
  status?: string
  steps?: string
  result?: string | null
  error?: string | null
  startedAt?: Date | string | null
  completedAt?: Date | string | null
  createdAt?: Date | string
}

export type AgentRunUncheckedCreateWithoutAgentInput = {
  id?: string
  status?: string
  steps?: string
  result?: string | null
  error?: string | null
  startedAt?: Date | string | null
  completedAt?: Date | string | null
  createdAt?: Date | string
}

export type AgentRunCreateOrConnectWithoutAgentInput = {
  where: Prisma.AgentRunWhereUniqueInput
  create: Prisma.XOR<Prisma.AgentRunCreateWithoutAgentInput, Prisma.AgentRunUncheckedCreateWithoutAgentInput>
}

export type AgentRunCreateManyAgentInputEnvelope = {
  data: Prisma.AgentRunCreateManyAgentInput | Prisma.AgentRunCreateManyAgentInput[]
}

export type AgentRunUpsertWithWhereUniqueWithoutAgentInput = {
  where: Prisma.AgentRunWhereUniqueInput
  update: Prisma.XOR<Prisma.AgentRunUpdateWithoutAgentInput, Prisma.AgentRunUncheckedUpdateWithoutAgentInput>
  create: Prisma.XOR<Prisma.AgentRunCreateWithoutAgentInput, Prisma.AgentRunUncheckedCreateWithoutAgentInput>
}

export type AgentRunUpdateWithWhereUniqueWithoutAgentInput = {
  where: Prisma.AgentRunWhereUniqueInput
  data: Prisma.XOR<Prisma.AgentRunUpdateWithoutAgentInput, Prisma.AgentRunUncheckedUpdateWithoutAgentInput>
}

export type AgentRunUpdateManyWithWhereWithoutAgentInput = {
  where: Prisma.AgentRunScalarWhereInput
  data: Prisma.XOR<Prisma.AgentRunUpdateManyMutationInput, Prisma.AgentRunUncheckedUpdateManyWithoutAgentInput>
}

export type AgentRunScalarWhereInput = {
  AND?: Prisma.AgentRunScalarWhereInput | Prisma.AgentRunScalarWhereInput[]
  OR?: Prisma.AgentRunScalarWhereInput[]
  NOT?: Prisma.AgentRunScalarWhereInput | Prisma.AgentRunScalarWhereInput[]
  id?: Prisma.StringFilter<"AgentRun"> | string
  agentId?: Prisma.StringFilter<"AgentRun"> | string
  status?: Prisma.StringFilter<"AgentRun"> | string
  steps?: Prisma.StringFilter<"AgentRun"> | string
  result?: Prisma.StringNullableFilter<"AgentRun"> | string | null
  error?: Prisma.StringNullableFilter<"AgentRun"> | string | null
  startedAt?: Prisma.DateTimeNullableFilter<"AgentRun"> | Date | string | null
  completedAt?: Prisma.DateTimeNullableFilter<"AgentRun"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"AgentRun"> | Date | string
}

export type AgentRunCreateManyAgentInput = {
  id?: string
  status?: string
  steps?: string
  result?: string | null
  error?: string | null
  startedAt?: Date | string | null
  completedAt?: Date | string | null
  createdAt?: Date | string
}

export type AgentRunUpdateWithoutAgentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  steps?: Prisma.StringFieldUpdateOperationsInput | string
  result?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  error?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  startedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AgentRunUncheckedUpdateWithoutAgentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  steps?: Prisma.StringFieldUpdateOperationsInput | string
  result?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  error?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  startedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AgentRunUncheckedUpdateManyWithoutAgentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  steps?: Prisma.StringFieldUpdateOperationsInput | string
  result?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  error?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  startedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  completedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type AgentRunSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  agentId?: boolean
  status?: boolean
  steps?: boolean
  result?: boolean
  error?: boolean
  startedAt?: boolean
  completedAt?: boolean
  createdAt?: boolean
  agent?: boolean | Prisma.AgentDefaultArgs<ExtArgs>
}, ExtArgs["result"]["agentRun"]>

export type AgentRunSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  agentId?: boolean
  status?: boolean
  steps?: boolean
  result?: boolean
  error?: boolean
  startedAt?: boolean
  completedAt?: boolean
  createdAt?: boolean
  agent?: boolean | Prisma.AgentDefaultArgs<ExtArgs>
}, ExtArgs["result"]["agentRun"]>

export type AgentRunSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  agentId?: boolean
  status?: boolean
  steps?: boolean
  result?: boolean
  error?: boolean
  startedAt?: boolean
  completedAt?: boolean
  createdAt?: boolean
  agent?: boolean | Prisma.AgentDefaultArgs<ExtArgs>
}, ExtArgs["result"]["agentRun"]>

export type AgentRunSelectScalar = {
  id?: boolean
  agentId?: boolean
  status?: boolean
  steps?: boolean
  result?: boolean
  error?: boolean
  startedAt?: boolean
  completedAt?: boolean
  createdAt?: boolean
}

export type AgentRunOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "agentId" | "status" | "steps" | "result" | "error" | "startedAt" | "completedAt" | "createdAt", ExtArgs["result"]["agentRun"]>
export type AgentRunInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  agent?: boolean | Prisma.AgentDefaultArgs<ExtArgs>
}
export type AgentRunIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  agent?: boolean | Prisma.AgentDefaultArgs<ExtArgs>
}
export type AgentRunIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  agent?: boolean | Prisma.AgentDefaultArgs<ExtArgs>
}

export type $AgentRunPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "AgentRun"
  objects: {
    agent: Prisma.$AgentPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    agentId: string
    status: string
    steps: string
    result: string | null
    error: string | null
    startedAt: Date | null
    completedAt: Date | null
    createdAt: Date
  }, ExtArgs["result"]["agentRun"]>
  composites: {}
}

export type AgentRunGetPayload<S extends boolean | null | undefined | AgentRunDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AgentRunPayload, S>

export type AgentRunCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AgentRunFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AgentRunCountAggregateInputType | true
  }

export interface AgentRunDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['AgentRun'], meta: { name: 'AgentRun' } }
  /**
   * Find zero or one AgentRun that matches the filter.
   * @param {AgentRunFindUniqueArgs} args - Arguments to find a AgentRun
   * @example
   * // Get one AgentRun
   * const agentRun = await prisma.agentRun.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AgentRunFindUniqueArgs>(args: Prisma.SelectSubset<T, AgentRunFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AgentRunClient<runtime.Types.Result.GetResult<Prisma.$AgentRunPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one AgentRun that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AgentRunFindUniqueOrThrowArgs} args - Arguments to find a AgentRun
   * @example
   * // Get one AgentRun
   * const agentRun = await prisma.agentRun.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AgentRunFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AgentRunFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AgentRunClient<runtime.Types.Result.GetResult<Prisma.$AgentRunPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AgentRun that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgentRunFindFirstArgs} args - Arguments to find a AgentRun
   * @example
   * // Get one AgentRun
   * const agentRun = await prisma.agentRun.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AgentRunFindFirstArgs>(args?: Prisma.SelectSubset<T, AgentRunFindFirstArgs<ExtArgs>>): Prisma.Prisma__AgentRunClient<runtime.Types.Result.GetResult<Prisma.$AgentRunPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AgentRun that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgentRunFindFirstOrThrowArgs} args - Arguments to find a AgentRun
   * @example
   * // Get one AgentRun
   * const agentRun = await prisma.agentRun.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AgentRunFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AgentRunFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AgentRunClient<runtime.Types.Result.GetResult<Prisma.$AgentRunPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more AgentRuns that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgentRunFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all AgentRuns
   * const agentRuns = await prisma.agentRun.findMany()
   * 
   * // Get first 10 AgentRuns
   * const agentRuns = await prisma.agentRun.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const agentRunWithIdOnly = await prisma.agentRun.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AgentRunFindManyArgs>(args?: Prisma.SelectSubset<T, AgentRunFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AgentRunPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a AgentRun.
   * @param {AgentRunCreateArgs} args - Arguments to create a AgentRun.
   * @example
   * // Create one AgentRun
   * const AgentRun = await prisma.agentRun.create({
   *   data: {
   *     // ... data to create a AgentRun
   *   }
   * })
   * 
   */
  create<T extends AgentRunCreateArgs>(args: Prisma.SelectSubset<T, AgentRunCreateArgs<ExtArgs>>): Prisma.Prisma__AgentRunClient<runtime.Types.Result.GetResult<Prisma.$AgentRunPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many AgentRuns.
   * @param {AgentRunCreateManyArgs} args - Arguments to create many AgentRuns.
   * @example
   * // Create many AgentRuns
   * const agentRun = await prisma.agentRun.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AgentRunCreateManyArgs>(args?: Prisma.SelectSubset<T, AgentRunCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many AgentRuns and returns the data saved in the database.
   * @param {AgentRunCreateManyAndReturnArgs} args - Arguments to create many AgentRuns.
   * @example
   * // Create many AgentRuns
   * const agentRun = await prisma.agentRun.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many AgentRuns and only return the `id`
   * const agentRunWithIdOnly = await prisma.agentRun.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AgentRunCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AgentRunCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AgentRunPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a AgentRun.
   * @param {AgentRunDeleteArgs} args - Arguments to delete one AgentRun.
   * @example
   * // Delete one AgentRun
   * const AgentRun = await prisma.agentRun.delete({
   *   where: {
   *     // ... filter to delete one AgentRun
   *   }
   * })
   * 
   */
  delete<T extends AgentRunDeleteArgs>(args: Prisma.SelectSubset<T, AgentRunDeleteArgs<ExtArgs>>): Prisma.Prisma__AgentRunClient<runtime.Types.Result.GetResult<Prisma.$AgentRunPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one AgentRun.
   * @param {AgentRunUpdateArgs} args - Arguments to update one AgentRun.
   * @example
   * // Update one AgentRun
   * const agentRun = await prisma.agentRun.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AgentRunUpdateArgs>(args: Prisma.SelectSubset<T, AgentRunUpdateArgs<ExtArgs>>): Prisma.Prisma__AgentRunClient<runtime.Types.Result.GetResult<Prisma.$AgentRunPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more AgentRuns.
   * @param {AgentRunDeleteManyArgs} args - Arguments to filter AgentRuns to delete.
   * @example
   * // Delete a few AgentRuns
   * const { count } = await prisma.agentRun.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AgentRunDeleteManyArgs>(args?: Prisma.SelectSubset<T, AgentRunDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AgentRuns.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgentRunUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many AgentRuns
   * const agentRun = await prisma.agentRun.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AgentRunUpdateManyArgs>(args: Prisma.SelectSubset<T, AgentRunUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AgentRuns and returns the data updated in the database.
   * @param {AgentRunUpdateManyAndReturnArgs} args - Arguments to update many AgentRuns.
   * @example
   * // Update many AgentRuns
   * const agentRun = await prisma.agentRun.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more AgentRuns and only return the `id`
   * const agentRunWithIdOnly = await prisma.agentRun.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AgentRunUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AgentRunUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AgentRunPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one AgentRun.
   * @param {AgentRunUpsertArgs} args - Arguments to update or create a AgentRun.
   * @example
   * // Update or create a AgentRun
   * const agentRun = await prisma.agentRun.upsert({
   *   create: {
   *     // ... data to create a AgentRun
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the AgentRun we want to update
   *   }
   * })
   */
  upsert<T extends AgentRunUpsertArgs>(args: Prisma.SelectSubset<T, AgentRunUpsertArgs<ExtArgs>>): Prisma.Prisma__AgentRunClient<runtime.Types.Result.GetResult<Prisma.$AgentRunPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of AgentRuns.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgentRunCountArgs} args - Arguments to filter AgentRuns to count.
   * @example
   * // Count the number of AgentRuns
   * const count = await prisma.agentRun.count({
   *   where: {
   *     // ... the filter for the AgentRuns we want to count
   *   }
   * })
  **/
  count<T extends AgentRunCountArgs>(
    args?: Prisma.Subset<T, AgentRunCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AgentRunCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a AgentRun.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgentRunAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AgentRunAggregateArgs>(args: Prisma.Subset<T, AgentRunAggregateArgs>): Prisma.PrismaPromise<GetAgentRunAggregateType<T>>

  /**
   * Group by AgentRun.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AgentRunGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AgentRunGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AgentRunGroupByArgs['orderBy'] }
      : { orderBy?: AgentRunGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AgentRunGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAgentRunGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the AgentRun model
 */
readonly fields: AgentRunFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for AgentRun.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AgentRunClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  agent<T extends Prisma.AgentDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AgentDefaultArgs<ExtArgs>>): Prisma.Prisma__AgentClient<runtime.Types.Result.GetResult<Prisma.$AgentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the AgentRun model
 */
export interface AgentRunFieldRefs {
  readonly id: Prisma.FieldRef<"AgentRun", 'String'>
  readonly agentId: Prisma.FieldRef<"AgentRun", 'String'>
  readonly status: Prisma.FieldRef<"AgentRun", 'String'>
  readonly steps: Prisma.FieldRef<"AgentRun", 'String'>
  readonly result: Prisma.FieldRef<"AgentRun", 'String'>
  readonly error: Prisma.FieldRef<"AgentRun", 'String'>
  readonly startedAt: Prisma.FieldRef<"AgentRun", 'DateTime'>
  readonly completedAt: Prisma.FieldRef<"AgentRun", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"AgentRun", 'DateTime'>
}
    

// Custom InputTypes
/**
 * AgentRun findUnique
 */
export type AgentRunFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgentRun
   */
  select?: Prisma.AgentRunSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgentRun
   */
  omit?: Prisma.AgentRunOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgentRunInclude<ExtArgs> | null
  /**
   * Filter, which AgentRun to fetch.
   */
  where: Prisma.AgentRunWhereUniqueInput
}

/**
 * AgentRun findUniqueOrThrow
 */
export type AgentRunFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgentRun
   */
  select?: Prisma.AgentRunSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgentRun
   */
  omit?: Prisma.AgentRunOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgentRunInclude<ExtArgs> | null
  /**
   * Filter, which AgentRun to fetch.
   */
  where: Prisma.AgentRunWhereUniqueInput
}

/**
 * AgentRun findFirst
 */
export type AgentRunFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgentRun
   */
  select?: Prisma.AgentRunSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgentRun
   */
  omit?: Prisma.AgentRunOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgentRunInclude<ExtArgs> | null
  /**
   * Filter, which AgentRun to fetch.
   */
  where?: Prisma.AgentRunWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AgentRuns to fetch.
   */
  orderBy?: Prisma.AgentRunOrderByWithRelationInput | Prisma.AgentRunOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AgentRuns.
   */
  cursor?: Prisma.AgentRunWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AgentRuns from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AgentRuns.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AgentRuns.
   */
  distinct?: Prisma.AgentRunScalarFieldEnum | Prisma.AgentRunScalarFieldEnum[]
}

/**
 * AgentRun findFirstOrThrow
 */
export type AgentRunFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgentRun
   */
  select?: Prisma.AgentRunSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgentRun
   */
  omit?: Prisma.AgentRunOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgentRunInclude<ExtArgs> | null
  /**
   * Filter, which AgentRun to fetch.
   */
  where?: Prisma.AgentRunWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AgentRuns to fetch.
   */
  orderBy?: Prisma.AgentRunOrderByWithRelationInput | Prisma.AgentRunOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AgentRuns.
   */
  cursor?: Prisma.AgentRunWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AgentRuns from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AgentRuns.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AgentRuns.
   */
  distinct?: Prisma.AgentRunScalarFieldEnum | Prisma.AgentRunScalarFieldEnum[]
}

/**
 * AgentRun findMany
 */
export type AgentRunFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgentRun
   */
  select?: Prisma.AgentRunSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgentRun
   */
  omit?: Prisma.AgentRunOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgentRunInclude<ExtArgs> | null
  /**
   * Filter, which AgentRuns to fetch.
   */
  where?: Prisma.AgentRunWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AgentRuns to fetch.
   */
  orderBy?: Prisma.AgentRunOrderByWithRelationInput | Prisma.AgentRunOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing AgentRuns.
   */
  cursor?: Prisma.AgentRunWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AgentRuns from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AgentRuns.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AgentRuns.
   */
  distinct?: Prisma.AgentRunScalarFieldEnum | Prisma.AgentRunScalarFieldEnum[]
}

/**
 * AgentRun create
 */
export type AgentRunCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgentRun
   */
  select?: Prisma.AgentRunSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgentRun
   */
  omit?: Prisma.AgentRunOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgentRunInclude<ExtArgs> | null
  /**
   * The data needed to create a AgentRun.
   */
  data: Prisma.XOR<Prisma.AgentRunCreateInput, Prisma.AgentRunUncheckedCreateInput>
}

/**
 * AgentRun createMany
 */
export type AgentRunCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many AgentRuns.
   */
  data: Prisma.AgentRunCreateManyInput | Prisma.AgentRunCreateManyInput[]
}

/**
 * AgentRun createManyAndReturn
 */
export type AgentRunCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgentRun
   */
  select?: Prisma.AgentRunSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AgentRun
   */
  omit?: Prisma.AgentRunOmit<ExtArgs> | null
  /**
   * The data used to create many AgentRuns.
   */
  data: Prisma.AgentRunCreateManyInput | Prisma.AgentRunCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgentRunIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * AgentRun update
 */
export type AgentRunUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgentRun
   */
  select?: Prisma.AgentRunSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgentRun
   */
  omit?: Prisma.AgentRunOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgentRunInclude<ExtArgs> | null
  /**
   * The data needed to update a AgentRun.
   */
  data: Prisma.XOR<Prisma.AgentRunUpdateInput, Prisma.AgentRunUncheckedUpdateInput>
  /**
   * Choose, which AgentRun to update.
   */
  where: Prisma.AgentRunWhereUniqueInput
}

/**
 * AgentRun updateMany
 */
export type AgentRunUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update AgentRuns.
   */
  data: Prisma.XOR<Prisma.AgentRunUpdateManyMutationInput, Prisma.AgentRunUncheckedUpdateManyInput>
  /**
   * Filter which AgentRuns to update
   */
  where?: Prisma.AgentRunWhereInput
  /**
   * Limit how many AgentRuns to update.
   */
  limit?: number
}

/**
 * AgentRun updateManyAndReturn
 */
export type AgentRunUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgentRun
   */
  select?: Prisma.AgentRunSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AgentRun
   */
  omit?: Prisma.AgentRunOmit<ExtArgs> | null
  /**
   * The data used to update AgentRuns.
   */
  data: Prisma.XOR<Prisma.AgentRunUpdateManyMutationInput, Prisma.AgentRunUncheckedUpdateManyInput>
  /**
   * Filter which AgentRuns to update
   */
  where?: Prisma.AgentRunWhereInput
  /**
   * Limit how many AgentRuns to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgentRunIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * AgentRun upsert
 */
export type AgentRunUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgentRun
   */
  select?: Prisma.AgentRunSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgentRun
   */
  omit?: Prisma.AgentRunOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgentRunInclude<ExtArgs> | null
  /**
   * The filter to search for the AgentRun to update in case it exists.
   */
  where: Prisma.AgentRunWhereUniqueInput
  /**
   * In case the AgentRun found by the `where` argument doesn't exist, create a new AgentRun with this data.
   */
  create: Prisma.XOR<Prisma.AgentRunCreateInput, Prisma.AgentRunUncheckedCreateInput>
  /**
   * In case the AgentRun was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AgentRunUpdateInput, Prisma.AgentRunUncheckedUpdateInput>
}

/**
 * AgentRun delete
 */
export type AgentRunDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgentRun
   */
  select?: Prisma.AgentRunSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgentRun
   */
  omit?: Prisma.AgentRunOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgentRunInclude<ExtArgs> | null
  /**
   * Filter which AgentRun to delete.
   */
  where: Prisma.AgentRunWhereUniqueInput
}

/**
 * AgentRun deleteMany
 */
export type AgentRunDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AgentRuns to delete
   */
  where?: Prisma.AgentRunWhereInput
  /**
   * Limit how many AgentRuns to delete.
   */
  limit?: number
}

/**
 * AgentRun without action
 */
export type AgentRunDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AgentRun
   */
  select?: Prisma.AgentRunSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AgentRun
   */
  omit?: Prisma.AgentRunOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AgentRunInclude<ExtArgs> | null
}
