
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `History` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model History
 * 
 */
export type HistoryModel = runtime.Types.Result.DefaultSelection<Prisma.$HistoryPayload>

export type AggregateHistory = {
  _count: HistoryCountAggregateOutputType | null
  _min: HistoryMinAggregateOutputType | null
  _max: HistoryMaxAggregateOutputType | null
}

export type HistoryMinAggregateOutputType = {
  id: string | null
  skillId: string | null
  action: string | null
  context: string | null
  createdAt: Date | null
}

export type HistoryMaxAggregateOutputType = {
  id: string | null
  skillId: string | null
  action: string | null
  context: string | null
  createdAt: Date | null
}

export type HistoryCountAggregateOutputType = {
  id: number
  skillId: number
  action: number
  context: number
  createdAt: number
  _all: number
}


export type HistoryMinAggregateInputType = {
  id?: true
  skillId?: true
  action?: true
  context?: true
  createdAt?: true
}

export type HistoryMaxAggregateInputType = {
  id?: true
  skillId?: true
  action?: true
  context?: true
  createdAt?: true
}

export type HistoryCountAggregateInputType = {
  id?: true
  skillId?: true
  action?: true
  context?: true
  createdAt?: true
  _all?: true
}

export type HistoryAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which History to aggregate.
   */
  where?: Prisma.HistoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Histories to fetch.
   */
  orderBy?: Prisma.HistoryOrderByWithRelationInput | Prisma.HistoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.HistoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Histories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Histories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Histories
  **/
  _count?: true | HistoryCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: HistoryMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: HistoryMaxAggregateInputType
}

export type GetHistoryAggregateType<T extends HistoryAggregateArgs> = {
      [P in keyof T & keyof AggregateHistory]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateHistory[P]>
    : Prisma.GetScalarType<T[P], AggregateHistory[P]>
}




export type HistoryGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.HistoryWhereInput
  orderBy?: Prisma.HistoryOrderByWithAggregationInput | Prisma.HistoryOrderByWithAggregationInput[]
  by: Prisma.HistoryScalarFieldEnum[] | Prisma.HistoryScalarFieldEnum
  having?: Prisma.HistoryScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: HistoryCountAggregateInputType | true
  _min?: HistoryMinAggregateInputType
  _max?: HistoryMaxAggregateInputType
}

export type HistoryGroupByOutputType = {
  id: string
  skillId: string
  action: string
  context: string | null
  createdAt: Date
  _count: HistoryCountAggregateOutputType | null
  _min: HistoryMinAggregateOutputType | null
  _max: HistoryMaxAggregateOutputType | null
}

export type GetHistoryGroupByPayload<T extends HistoryGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<HistoryGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof HistoryGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], HistoryGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], HistoryGroupByOutputType[P]>
      }
    >
  >



export type HistoryWhereInput = {
  AND?: Prisma.HistoryWhereInput | Prisma.HistoryWhereInput[]
  OR?: Prisma.HistoryWhereInput[]
  NOT?: Prisma.HistoryWhereInput | Prisma.HistoryWhereInput[]
  id?: Prisma.StringFilter<"History"> | string
  skillId?: Prisma.StringFilter<"History"> | string
  action?: Prisma.StringFilter<"History"> | string
  context?: Prisma.StringNullableFilter<"History"> | string | null
  createdAt?: Prisma.DateTimeFilter<"History"> | Date | string
  skill?: Prisma.XOR<Prisma.SkillScalarRelationFilter, Prisma.SkillWhereInput>
}

export type HistoryOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  skillId?: Prisma.SortOrder
  action?: Prisma.SortOrder
  context?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  skill?: Prisma.SkillOrderByWithRelationInput
}

export type HistoryWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.HistoryWhereInput | Prisma.HistoryWhereInput[]
  OR?: Prisma.HistoryWhereInput[]
  NOT?: Prisma.HistoryWhereInput | Prisma.HistoryWhereInput[]
  skillId?: Prisma.StringFilter<"History"> | string
  action?: Prisma.StringFilter<"History"> | string
  context?: Prisma.StringNullableFilter<"History"> | string | null
  createdAt?: Prisma.DateTimeFilter<"History"> | Date | string
  skill?: Prisma.XOR<Prisma.SkillScalarRelationFilter, Prisma.SkillWhereInput>
}, "id">

export type HistoryOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  skillId?: Prisma.SortOrder
  action?: Prisma.SortOrder
  context?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.HistoryCountOrderByAggregateInput
  _max?: Prisma.HistoryMaxOrderByAggregateInput
  _min?: Prisma.HistoryMinOrderByAggregateInput
}

export type HistoryScalarWhereWithAggregatesInput = {
  AND?: Prisma.HistoryScalarWhereWithAggregatesInput | Prisma.HistoryScalarWhereWithAggregatesInput[]
  OR?: Prisma.HistoryScalarWhereWithAggregatesInput[]
  NOT?: Prisma.HistoryScalarWhereWithAggregatesInput | Prisma.HistoryScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"History"> | string
  skillId?: Prisma.StringWithAggregatesFilter<"History"> | string
  action?: Prisma.StringWithAggregatesFilter<"History"> | string
  context?: Prisma.StringNullableWithAggregatesFilter<"History"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"History"> | Date | string
}

export type HistoryCreateInput = {
  id?: string
  action?: string
  context?: string | null
  createdAt?: Date | string
  skill: Prisma.SkillCreateNestedOneWithoutHistoryInput
}

export type HistoryUncheckedCreateInput = {
  id?: string
  skillId: string
  action?: string
  context?: string | null
  createdAt?: Date | string
}

export type HistoryUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  action?: Prisma.StringFieldUpdateOperationsInput | string
  context?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  skill?: Prisma.SkillUpdateOneRequiredWithoutHistoryNestedInput
}

export type HistoryUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  skillId?: Prisma.StringFieldUpdateOperationsInput | string
  action?: Prisma.StringFieldUpdateOperationsInput | string
  context?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type HistoryCreateManyInput = {
  id?: string
  skillId: string
  action?: string
  context?: string | null
  createdAt?: Date | string
}

export type HistoryUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  action?: Prisma.StringFieldUpdateOperationsInput | string
  context?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type HistoryUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  skillId?: Prisma.StringFieldUpdateOperationsInput | string
  action?: Prisma.StringFieldUpdateOperationsInput | string
  context?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type HistoryListRelationFilter = {
  every?: Prisma.HistoryWhereInput
  some?: Prisma.HistoryWhereInput
  none?: Prisma.HistoryWhereInput
}

export type HistoryOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type HistoryCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  skillId?: Prisma.SortOrder
  action?: Prisma.SortOrder
  context?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type HistoryMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  skillId?: Prisma.SortOrder
  action?: Prisma.SortOrder
  context?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type HistoryMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  skillId?: Prisma.SortOrder
  action?: Prisma.SortOrder
  context?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type HistoryCreateNestedManyWithoutSkillInput = {
  create?: Prisma.XOR<Prisma.HistoryCreateWithoutSkillInput, Prisma.HistoryUncheckedCreateWithoutSkillInput> | Prisma.HistoryCreateWithoutSkillInput[] | Prisma.HistoryUncheckedCreateWithoutSkillInput[]
  connectOrCreate?: Prisma.HistoryCreateOrConnectWithoutSkillInput | Prisma.HistoryCreateOrConnectWithoutSkillInput[]
  createMany?: Prisma.HistoryCreateManySkillInputEnvelope
  connect?: Prisma.HistoryWhereUniqueInput | Prisma.HistoryWhereUniqueInput[]
}

export type HistoryUncheckedCreateNestedManyWithoutSkillInput = {
  create?: Prisma.XOR<Prisma.HistoryCreateWithoutSkillInput, Prisma.HistoryUncheckedCreateWithoutSkillInput> | Prisma.HistoryCreateWithoutSkillInput[] | Prisma.HistoryUncheckedCreateWithoutSkillInput[]
  connectOrCreate?: Prisma.HistoryCreateOrConnectWithoutSkillInput | Prisma.HistoryCreateOrConnectWithoutSkillInput[]
  createMany?: Prisma.HistoryCreateManySkillInputEnvelope
  connect?: Prisma.HistoryWhereUniqueInput | Prisma.HistoryWhereUniqueInput[]
}

export type HistoryUpdateManyWithoutSkillNestedInput = {
  create?: Prisma.XOR<Prisma.HistoryCreateWithoutSkillInput, Prisma.HistoryUncheckedCreateWithoutSkillInput> | Prisma.HistoryCreateWithoutSkillInput[] | Prisma.HistoryUncheckedCreateWithoutSkillInput[]
  connectOrCreate?: Prisma.HistoryCreateOrConnectWithoutSkillInput | Prisma.HistoryCreateOrConnectWithoutSkillInput[]
  upsert?: Prisma.HistoryUpsertWithWhereUniqueWithoutSkillInput | Prisma.HistoryUpsertWithWhereUniqueWithoutSkillInput[]
  createMany?: Prisma.HistoryCreateManySkillInputEnvelope
  set?: Prisma.HistoryWhereUniqueInput | Prisma.HistoryWhereUniqueInput[]
  disconnect?: Prisma.HistoryWhereUniqueInput | Prisma.HistoryWhereUniqueInput[]
  delete?: Prisma.HistoryWhereUniqueInput | Prisma.HistoryWhereUniqueInput[]
  connect?: Prisma.HistoryWhereUniqueInput | Prisma.HistoryWhereUniqueInput[]
  update?: Prisma.HistoryUpdateWithWhereUniqueWithoutSkillInput | Prisma.HistoryUpdateWithWhereUniqueWithoutSkillInput[]
  updateMany?: Prisma.HistoryUpdateManyWithWhereWithoutSkillInput | Prisma.HistoryUpdateManyWithWhereWithoutSkillInput[]
  deleteMany?: Prisma.HistoryScalarWhereInput | Prisma.HistoryScalarWhereInput[]
}

export type HistoryUncheckedUpdateManyWithoutSkillNestedInput = {
  create?: Prisma.XOR<Prisma.HistoryCreateWithoutSkillInput, Prisma.HistoryUncheckedCreateWithoutSkillInput> | Prisma.HistoryCreateWithoutSkillInput[] | Prisma.HistoryUncheckedCreateWithoutSkillInput[]
  connectOrCreate?: Prisma.HistoryCreateOrConnectWithoutSkillInput | Prisma.HistoryCreateOrConnectWithoutSkillInput[]
  upsert?: Prisma.HistoryUpsertWithWhereUniqueWithoutSkillInput | Prisma.HistoryUpsertWithWhereUniqueWithoutSkillInput[]
  createMany?: Prisma.HistoryCreateManySkillInputEnvelope
  set?: Prisma.HistoryWhereUniqueInput | Prisma.HistoryWhereUniqueInput[]
  disconnect?: Prisma.HistoryWhereUniqueInput | Prisma.HistoryWhereUniqueInput[]
  delete?: Prisma.HistoryWhereUniqueInput | Prisma.HistoryWhereUniqueInput[]
  connect?: Prisma.HistoryWhereUniqueInput | Prisma.HistoryWhereUniqueInput[]
  update?: Prisma.HistoryUpdateWithWhereUniqueWithoutSkillInput | Prisma.HistoryUpdateWithWhereUniqueWithoutSkillInput[]
  updateMany?: Prisma.HistoryUpdateManyWithWhereWithoutSkillInput | Prisma.HistoryUpdateManyWithWhereWithoutSkillInput[]
  deleteMany?: Prisma.HistoryScalarWhereInput | Prisma.HistoryScalarWhereInput[]
}

export type HistoryCreateWithoutSkillInput = {
  id?: string
  action?: string
  context?: string | null
  createdAt?: Date | string
}

export type HistoryUncheckedCreateWithoutSkillInput = {
  id?: string
  action?: string
  context?: string | null
  createdAt?: Date | string
}

export type HistoryCreateOrConnectWithoutSkillInput = {
  where: Prisma.HistoryWhereUniqueInput
  create: Prisma.XOR<Prisma.HistoryCreateWithoutSkillInput, Prisma.HistoryUncheckedCreateWithoutSkillInput>
}

export type HistoryCreateManySkillInputEnvelope = {
  data: Prisma.HistoryCreateManySkillInput | Prisma.HistoryCreateManySkillInput[]
}

export type HistoryUpsertWithWhereUniqueWithoutSkillInput = {
  where: Prisma.HistoryWhereUniqueInput
  update: Prisma.XOR<Prisma.HistoryUpdateWithoutSkillInput, Prisma.HistoryUncheckedUpdateWithoutSkillInput>
  create: Prisma.XOR<Prisma.HistoryCreateWithoutSkillInput, Prisma.HistoryUncheckedCreateWithoutSkillInput>
}

export type HistoryUpdateWithWhereUniqueWithoutSkillInput = {
  where: Prisma.HistoryWhereUniqueInput
  data: Prisma.XOR<Prisma.HistoryUpdateWithoutSkillInput, Prisma.HistoryUncheckedUpdateWithoutSkillInput>
}

export type HistoryUpdateManyWithWhereWithoutSkillInput = {
  where: Prisma.HistoryScalarWhereInput
  data: Prisma.XOR<Prisma.HistoryUpdateManyMutationInput, Prisma.HistoryUncheckedUpdateManyWithoutSkillInput>
}

export type HistoryScalarWhereInput = {
  AND?: Prisma.HistoryScalarWhereInput | Prisma.HistoryScalarWhereInput[]
  OR?: Prisma.HistoryScalarWhereInput[]
  NOT?: Prisma.HistoryScalarWhereInput | Prisma.HistoryScalarWhereInput[]
  id?: Prisma.StringFilter<"History"> | string
  skillId?: Prisma.StringFilter<"History"> | string
  action?: Prisma.StringFilter<"History"> | string
  context?: Prisma.StringNullableFilter<"History"> | string | null
  createdAt?: Prisma.DateTimeFilter<"History"> | Date | string
}

export type HistoryCreateManySkillInput = {
  id?: string
  action?: string
  context?: string | null
  createdAt?: Date | string
}

export type HistoryUpdateWithoutSkillInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  action?: Prisma.StringFieldUpdateOperationsInput | string
  context?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type HistoryUncheckedUpdateWithoutSkillInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  action?: Prisma.StringFieldUpdateOperationsInput | string
  context?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type HistoryUncheckedUpdateManyWithoutSkillInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  action?: Prisma.StringFieldUpdateOperationsInput | string
  context?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type HistorySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  skillId?: boolean
  action?: boolean
  context?: boolean
  createdAt?: boolean
  skill?: boolean | Prisma.SkillDefaultArgs<ExtArgs>
}, ExtArgs["result"]["history"]>

export type HistorySelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  skillId?: boolean
  action?: boolean
  context?: boolean
  createdAt?: boolean
  skill?: boolean | Prisma.SkillDefaultArgs<ExtArgs>
}, ExtArgs["result"]["history"]>

export type HistorySelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  skillId?: boolean
  action?: boolean
  context?: boolean
  createdAt?: boolean
  skill?: boolean | Prisma.SkillDefaultArgs<ExtArgs>
}, ExtArgs["result"]["history"]>

export type HistorySelectScalar = {
  id?: boolean
  skillId?: boolean
  action?: boolean
  context?: boolean
  createdAt?: boolean
}

export type HistoryOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "skillId" | "action" | "context" | "createdAt", ExtArgs["result"]["history"]>
export type HistoryInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  skill?: boolean | Prisma.SkillDefaultArgs<ExtArgs>
}
export type HistoryIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  skill?: boolean | Prisma.SkillDefaultArgs<ExtArgs>
}
export type HistoryIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  skill?: boolean | Prisma.SkillDefaultArgs<ExtArgs>
}

export type $HistoryPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "History"
  objects: {
    skill: Prisma.$SkillPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    skillId: string
    action: string
    context: string | null
    createdAt: Date
  }, ExtArgs["result"]["history"]>
  composites: {}
}

export type HistoryGetPayload<S extends boolean | null | undefined | HistoryDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$HistoryPayload, S>

export type HistoryCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<HistoryFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: HistoryCountAggregateInputType | true
  }

export interface HistoryDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['History'], meta: { name: 'History' } }
  /**
   * Find zero or one History that matches the filter.
   * @param {HistoryFindUniqueArgs} args - Arguments to find a History
   * @example
   * // Get one History
   * const history = await prisma.history.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends HistoryFindUniqueArgs>(args: Prisma.SelectSubset<T, HistoryFindUniqueArgs<ExtArgs>>): Prisma.Prisma__HistoryClient<runtime.Types.Result.GetResult<Prisma.$HistoryPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one History that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {HistoryFindUniqueOrThrowArgs} args - Arguments to find a History
   * @example
   * // Get one History
   * const history = await prisma.history.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends HistoryFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, HistoryFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__HistoryClient<runtime.Types.Result.GetResult<Prisma.$HistoryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first History that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HistoryFindFirstArgs} args - Arguments to find a History
   * @example
   * // Get one History
   * const history = await prisma.history.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends HistoryFindFirstArgs>(args?: Prisma.SelectSubset<T, HistoryFindFirstArgs<ExtArgs>>): Prisma.Prisma__HistoryClient<runtime.Types.Result.GetResult<Prisma.$HistoryPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first History that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HistoryFindFirstOrThrowArgs} args - Arguments to find a History
   * @example
   * // Get one History
   * const history = await prisma.history.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends HistoryFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, HistoryFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__HistoryClient<runtime.Types.Result.GetResult<Prisma.$HistoryPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Histories that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HistoryFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Histories
   * const histories = await prisma.history.findMany()
   * 
   * // Get first 10 Histories
   * const histories = await prisma.history.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const historyWithIdOnly = await prisma.history.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends HistoryFindManyArgs>(args?: Prisma.SelectSubset<T, HistoryFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$HistoryPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a History.
   * @param {HistoryCreateArgs} args - Arguments to create a History.
   * @example
   * // Create one History
   * const History = await prisma.history.create({
   *   data: {
   *     // ... data to create a History
   *   }
   * })
   * 
   */
  create<T extends HistoryCreateArgs>(args: Prisma.SelectSubset<T, HistoryCreateArgs<ExtArgs>>): Prisma.Prisma__HistoryClient<runtime.Types.Result.GetResult<Prisma.$HistoryPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Histories.
   * @param {HistoryCreateManyArgs} args - Arguments to create many Histories.
   * @example
   * // Create many Histories
   * const history = await prisma.history.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends HistoryCreateManyArgs>(args?: Prisma.SelectSubset<T, HistoryCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Histories and returns the data saved in the database.
   * @param {HistoryCreateManyAndReturnArgs} args - Arguments to create many Histories.
   * @example
   * // Create many Histories
   * const history = await prisma.history.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Histories and only return the `id`
   * const historyWithIdOnly = await prisma.history.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends HistoryCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, HistoryCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$HistoryPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a History.
   * @param {HistoryDeleteArgs} args - Arguments to delete one History.
   * @example
   * // Delete one History
   * const History = await prisma.history.delete({
   *   where: {
   *     // ... filter to delete one History
   *   }
   * })
   * 
   */
  delete<T extends HistoryDeleteArgs>(args: Prisma.SelectSubset<T, HistoryDeleteArgs<ExtArgs>>): Prisma.Prisma__HistoryClient<runtime.Types.Result.GetResult<Prisma.$HistoryPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one History.
   * @param {HistoryUpdateArgs} args - Arguments to update one History.
   * @example
   * // Update one History
   * const history = await prisma.history.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends HistoryUpdateArgs>(args: Prisma.SelectSubset<T, HistoryUpdateArgs<ExtArgs>>): Prisma.Prisma__HistoryClient<runtime.Types.Result.GetResult<Prisma.$HistoryPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Histories.
   * @param {HistoryDeleteManyArgs} args - Arguments to filter Histories to delete.
   * @example
   * // Delete a few Histories
   * const { count } = await prisma.history.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends HistoryDeleteManyArgs>(args?: Prisma.SelectSubset<T, HistoryDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Histories.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HistoryUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Histories
   * const history = await prisma.history.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends HistoryUpdateManyArgs>(args: Prisma.SelectSubset<T, HistoryUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Histories and returns the data updated in the database.
   * @param {HistoryUpdateManyAndReturnArgs} args - Arguments to update many Histories.
   * @example
   * // Update many Histories
   * const history = await prisma.history.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Histories and only return the `id`
   * const historyWithIdOnly = await prisma.history.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends HistoryUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, HistoryUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$HistoryPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one History.
   * @param {HistoryUpsertArgs} args - Arguments to update or create a History.
   * @example
   * // Update or create a History
   * const history = await prisma.history.upsert({
   *   create: {
   *     // ... data to create a History
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the History we want to update
   *   }
   * })
   */
  upsert<T extends HistoryUpsertArgs>(args: Prisma.SelectSubset<T, HistoryUpsertArgs<ExtArgs>>): Prisma.Prisma__HistoryClient<runtime.Types.Result.GetResult<Prisma.$HistoryPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Histories.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HistoryCountArgs} args - Arguments to filter Histories to count.
   * @example
   * // Count the number of Histories
   * const count = await prisma.history.count({
   *   where: {
   *     // ... the filter for the Histories we want to count
   *   }
   * })
  **/
  count<T extends HistoryCountArgs>(
    args?: Prisma.Subset<T, HistoryCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], HistoryCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a History.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HistoryAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends HistoryAggregateArgs>(args: Prisma.Subset<T, HistoryAggregateArgs>): Prisma.PrismaPromise<GetHistoryAggregateType<T>>

  /**
   * Group by History.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HistoryGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends HistoryGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: HistoryGroupByArgs['orderBy'] }
      : { orderBy?: HistoryGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, HistoryGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetHistoryGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the History model
 */
readonly fields: HistoryFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for History.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__HistoryClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  skill<T extends Prisma.SkillDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SkillDefaultArgs<ExtArgs>>): Prisma.Prisma__SkillClient<runtime.Types.Result.GetResult<Prisma.$SkillPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the History model
 */
export interface HistoryFieldRefs {
  readonly id: Prisma.FieldRef<"History", 'String'>
  readonly skillId: Prisma.FieldRef<"History", 'String'>
  readonly action: Prisma.FieldRef<"History", 'String'>
  readonly context: Prisma.FieldRef<"History", 'String'>
  readonly createdAt: Prisma.FieldRef<"History", 'DateTime'>
}
    

// Custom InputTypes
/**
 * History findUnique
 */
export type HistoryFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the History
   */
  select?: Prisma.HistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the History
   */
  omit?: Prisma.HistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HistoryInclude<ExtArgs> | null
  /**
   * Filter, which History to fetch.
   */
  where: Prisma.HistoryWhereUniqueInput
}

/**
 * History findUniqueOrThrow
 */
export type HistoryFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the History
   */
  select?: Prisma.HistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the History
   */
  omit?: Prisma.HistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HistoryInclude<ExtArgs> | null
  /**
   * Filter, which History to fetch.
   */
  where: Prisma.HistoryWhereUniqueInput
}

/**
 * History findFirst
 */
export type HistoryFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the History
   */
  select?: Prisma.HistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the History
   */
  omit?: Prisma.HistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HistoryInclude<ExtArgs> | null
  /**
   * Filter, which History to fetch.
   */
  where?: Prisma.HistoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Histories to fetch.
   */
  orderBy?: Prisma.HistoryOrderByWithRelationInput | Prisma.HistoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Histories.
   */
  cursor?: Prisma.HistoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Histories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Histories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Histories.
   */
  distinct?: Prisma.HistoryScalarFieldEnum | Prisma.HistoryScalarFieldEnum[]
}

/**
 * History findFirstOrThrow
 */
export type HistoryFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the History
   */
  select?: Prisma.HistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the History
   */
  omit?: Prisma.HistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HistoryInclude<ExtArgs> | null
  /**
   * Filter, which History to fetch.
   */
  where?: Prisma.HistoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Histories to fetch.
   */
  orderBy?: Prisma.HistoryOrderByWithRelationInput | Prisma.HistoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Histories.
   */
  cursor?: Prisma.HistoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Histories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Histories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Histories.
   */
  distinct?: Prisma.HistoryScalarFieldEnum | Prisma.HistoryScalarFieldEnum[]
}

/**
 * History findMany
 */
export type HistoryFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the History
   */
  select?: Prisma.HistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the History
   */
  omit?: Prisma.HistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HistoryInclude<ExtArgs> | null
  /**
   * Filter, which Histories to fetch.
   */
  where?: Prisma.HistoryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Histories to fetch.
   */
  orderBy?: Prisma.HistoryOrderByWithRelationInput | Prisma.HistoryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Histories.
   */
  cursor?: Prisma.HistoryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Histories from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Histories.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Histories.
   */
  distinct?: Prisma.HistoryScalarFieldEnum | Prisma.HistoryScalarFieldEnum[]
}

/**
 * History create
 */
export type HistoryCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the History
   */
  select?: Prisma.HistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the History
   */
  omit?: Prisma.HistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HistoryInclude<ExtArgs> | null
  /**
   * The data needed to create a History.
   */
  data: Prisma.XOR<Prisma.HistoryCreateInput, Prisma.HistoryUncheckedCreateInput>
}

/**
 * History createMany
 */
export type HistoryCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Histories.
   */
  data: Prisma.HistoryCreateManyInput | Prisma.HistoryCreateManyInput[]
}

/**
 * History createManyAndReturn
 */
export type HistoryCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the History
   */
  select?: Prisma.HistorySelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the History
   */
  omit?: Prisma.HistoryOmit<ExtArgs> | null
  /**
   * The data used to create many Histories.
   */
  data: Prisma.HistoryCreateManyInput | Prisma.HistoryCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HistoryIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * History update
 */
export type HistoryUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the History
   */
  select?: Prisma.HistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the History
   */
  omit?: Prisma.HistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HistoryInclude<ExtArgs> | null
  /**
   * The data needed to update a History.
   */
  data: Prisma.XOR<Prisma.HistoryUpdateInput, Prisma.HistoryUncheckedUpdateInput>
  /**
   * Choose, which History to update.
   */
  where: Prisma.HistoryWhereUniqueInput
}

/**
 * History updateMany
 */
export type HistoryUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Histories.
   */
  data: Prisma.XOR<Prisma.HistoryUpdateManyMutationInput, Prisma.HistoryUncheckedUpdateManyInput>
  /**
   * Filter which Histories to update
   */
  where?: Prisma.HistoryWhereInput
  /**
   * Limit how many Histories to update.
   */
  limit?: number
}

/**
 * History updateManyAndReturn
 */
export type HistoryUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the History
   */
  select?: Prisma.HistorySelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the History
   */
  omit?: Prisma.HistoryOmit<ExtArgs> | null
  /**
   * The data used to update Histories.
   */
  data: Prisma.XOR<Prisma.HistoryUpdateManyMutationInput, Prisma.HistoryUncheckedUpdateManyInput>
  /**
   * Filter which Histories to update
   */
  where?: Prisma.HistoryWhereInput
  /**
   * Limit how many Histories to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HistoryIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * History upsert
 */
export type HistoryUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the History
   */
  select?: Prisma.HistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the History
   */
  omit?: Prisma.HistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HistoryInclude<ExtArgs> | null
  /**
   * The filter to search for the History to update in case it exists.
   */
  where: Prisma.HistoryWhereUniqueInput
  /**
   * In case the History found by the `where` argument doesn't exist, create a new History with this data.
   */
  create: Prisma.XOR<Prisma.HistoryCreateInput, Prisma.HistoryUncheckedCreateInput>
  /**
   * In case the History was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.HistoryUpdateInput, Prisma.HistoryUncheckedUpdateInput>
}

/**
 * History delete
 */
export type HistoryDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the History
   */
  select?: Prisma.HistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the History
   */
  omit?: Prisma.HistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HistoryInclude<ExtArgs> | null
  /**
   * Filter which History to delete.
   */
  where: Prisma.HistoryWhereUniqueInput
}

/**
 * History deleteMany
 */
export type HistoryDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Histories to delete
   */
  where?: Prisma.HistoryWhereInput
  /**
   * Limit how many Histories to delete.
   */
  limit?: number
}

/**
 * History without action
 */
export type HistoryDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the History
   */
  select?: Prisma.HistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the History
   */
  omit?: Prisma.HistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HistoryInclude<ExtArgs> | null
}
