
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `SEOMeta` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model SEOMeta
 * 
 */
export type SEOMetaModel = runtime.Types.Result.DefaultSelection<Prisma.$SEOMetaPayload>

export type AggregateSEOMeta = {
  _count: SEOMetaCountAggregateOutputType | null
  _min: SEOMetaMinAggregateOutputType | null
  _max: SEOMetaMaxAggregateOutputType | null
}

export type SEOMetaMinAggregateOutputType = {
  id: string | null
  path: string | null
  title: string | null
  description: string | null
  keywords: string | null
  ogImage: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type SEOMetaMaxAggregateOutputType = {
  id: string | null
  path: string | null
  title: string | null
  description: string | null
  keywords: string | null
  ogImage: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type SEOMetaCountAggregateOutputType = {
  id: number
  path: number
  title: number
  description: number
  keywords: number
  ogImage: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type SEOMetaMinAggregateInputType = {
  id?: true
  path?: true
  title?: true
  description?: true
  keywords?: true
  ogImage?: true
  createdAt?: true
  updatedAt?: true
}

export type SEOMetaMaxAggregateInputType = {
  id?: true
  path?: true
  title?: true
  description?: true
  keywords?: true
  ogImage?: true
  createdAt?: true
  updatedAt?: true
}

export type SEOMetaCountAggregateInputType = {
  id?: true
  path?: true
  title?: true
  description?: true
  keywords?: true
  ogImage?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type SEOMetaAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SEOMeta to aggregate.
   */
  where?: Prisma.SEOMetaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SEOMetas to fetch.
   */
  orderBy?: Prisma.SEOMetaOrderByWithRelationInput | Prisma.SEOMetaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SEOMetaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SEOMetas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SEOMetas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned SEOMetas
  **/
  _count?: true | SEOMetaCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SEOMetaMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SEOMetaMaxAggregateInputType
}

export type GetSEOMetaAggregateType<T extends SEOMetaAggregateArgs> = {
      [P in keyof T & keyof AggregateSEOMeta]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSEOMeta[P]>
    : Prisma.GetScalarType<T[P], AggregateSEOMeta[P]>
}




export type SEOMetaGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SEOMetaWhereInput
  orderBy?: Prisma.SEOMetaOrderByWithAggregationInput | Prisma.SEOMetaOrderByWithAggregationInput[]
  by: Prisma.SEOMetaScalarFieldEnum[] | Prisma.SEOMetaScalarFieldEnum
  having?: Prisma.SEOMetaScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SEOMetaCountAggregateInputType | true
  _min?: SEOMetaMinAggregateInputType
  _max?: SEOMetaMaxAggregateInputType
}

export type SEOMetaGroupByOutputType = {
  id: string
  path: string
  title: string
  description: string
  keywords: string | null
  ogImage: string | null
  createdAt: Date
  updatedAt: Date
  _count: SEOMetaCountAggregateOutputType | null
  _min: SEOMetaMinAggregateOutputType | null
  _max: SEOMetaMaxAggregateOutputType | null
}

export type GetSEOMetaGroupByPayload<T extends SEOMetaGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SEOMetaGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SEOMetaGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SEOMetaGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SEOMetaGroupByOutputType[P]>
      }
    >
  >



export type SEOMetaWhereInput = {
  AND?: Prisma.SEOMetaWhereInput | Prisma.SEOMetaWhereInput[]
  OR?: Prisma.SEOMetaWhereInput[]
  NOT?: Prisma.SEOMetaWhereInput | Prisma.SEOMetaWhereInput[]
  id?: Prisma.StringFilter<"SEOMeta"> | string
  path?: Prisma.StringFilter<"SEOMeta"> | string
  title?: Prisma.StringFilter<"SEOMeta"> | string
  description?: Prisma.StringFilter<"SEOMeta"> | string
  keywords?: Prisma.StringNullableFilter<"SEOMeta"> | string | null
  ogImage?: Prisma.StringNullableFilter<"SEOMeta"> | string | null
  createdAt?: Prisma.DateTimeFilter<"SEOMeta"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"SEOMeta"> | Date | string
}

export type SEOMetaOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  path?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  keywords?: Prisma.SortOrderInput | Prisma.SortOrder
  ogImage?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type SEOMetaWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  path?: string
  AND?: Prisma.SEOMetaWhereInput | Prisma.SEOMetaWhereInput[]
  OR?: Prisma.SEOMetaWhereInput[]
  NOT?: Prisma.SEOMetaWhereInput | Prisma.SEOMetaWhereInput[]
  title?: Prisma.StringFilter<"SEOMeta"> | string
  description?: Prisma.StringFilter<"SEOMeta"> | string
  keywords?: Prisma.StringNullableFilter<"SEOMeta"> | string | null
  ogImage?: Prisma.StringNullableFilter<"SEOMeta"> | string | null
  createdAt?: Prisma.DateTimeFilter<"SEOMeta"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"SEOMeta"> | Date | string
}, "id" | "path">

export type SEOMetaOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  path?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  keywords?: Prisma.SortOrderInput | Prisma.SortOrder
  ogImage?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.SEOMetaCountOrderByAggregateInput
  _max?: Prisma.SEOMetaMaxOrderByAggregateInput
  _min?: Prisma.SEOMetaMinOrderByAggregateInput
}

export type SEOMetaScalarWhereWithAggregatesInput = {
  AND?: Prisma.SEOMetaScalarWhereWithAggregatesInput | Prisma.SEOMetaScalarWhereWithAggregatesInput[]
  OR?: Prisma.SEOMetaScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SEOMetaScalarWhereWithAggregatesInput | Prisma.SEOMetaScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"SEOMeta"> | string
  path?: Prisma.StringWithAggregatesFilter<"SEOMeta"> | string
  title?: Prisma.StringWithAggregatesFilter<"SEOMeta"> | string
  description?: Prisma.StringWithAggregatesFilter<"SEOMeta"> | string
  keywords?: Prisma.StringNullableWithAggregatesFilter<"SEOMeta"> | string | null
  ogImage?: Prisma.StringNullableWithAggregatesFilter<"SEOMeta"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"SEOMeta"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"SEOMeta"> | Date | string
}

export type SEOMetaCreateInput = {
  id?: string
  path: string
  title: string
  description: string
  keywords?: string | null
  ogImage?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SEOMetaUncheckedCreateInput = {
  id?: string
  path: string
  title: string
  description: string
  keywords?: string | null
  ogImage?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SEOMetaUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  path?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  keywords?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ogImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SEOMetaUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  path?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  keywords?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ogImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SEOMetaCreateManyInput = {
  id?: string
  path: string
  title: string
  description: string
  keywords?: string | null
  ogImage?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SEOMetaUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  path?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  keywords?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ogImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SEOMetaUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  path?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  keywords?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ogImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SEOMetaCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  path?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  keywords?: Prisma.SortOrder
  ogImage?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type SEOMetaMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  path?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  keywords?: Prisma.SortOrder
  ogImage?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type SEOMetaMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  path?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  keywords?: Prisma.SortOrder
  ogImage?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}



export type SEOMetaSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  path?: boolean
  title?: boolean
  description?: boolean
  keywords?: boolean
  ogImage?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["sEOMeta"]>

export type SEOMetaSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  path?: boolean
  title?: boolean
  description?: boolean
  keywords?: boolean
  ogImage?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["sEOMeta"]>

export type SEOMetaSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  path?: boolean
  title?: boolean
  description?: boolean
  keywords?: boolean
  ogImage?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["sEOMeta"]>

export type SEOMetaSelectScalar = {
  id?: boolean
  path?: boolean
  title?: boolean
  description?: boolean
  keywords?: boolean
  ogImage?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type SEOMetaOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "path" | "title" | "description" | "keywords" | "ogImage" | "createdAt" | "updatedAt", ExtArgs["result"]["sEOMeta"]>

export type $SEOMetaPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "SEOMeta"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    path: string
    title: string
    description: string
    keywords: string | null
    ogImage: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["sEOMeta"]>
  composites: {}
}

export type SEOMetaGetPayload<S extends boolean | null | undefined | SEOMetaDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SEOMetaPayload, S>

export type SEOMetaCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SEOMetaFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SEOMetaCountAggregateInputType | true
  }

export interface SEOMetaDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['SEOMeta'], meta: { name: 'SEOMeta' } }
  /**
   * Find zero or one SEOMeta that matches the filter.
   * @param {SEOMetaFindUniqueArgs} args - Arguments to find a SEOMeta
   * @example
   * // Get one SEOMeta
   * const sEOMeta = await prisma.sEOMeta.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SEOMetaFindUniqueArgs>(args: Prisma.SelectSubset<T, SEOMetaFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SEOMetaClient<runtime.Types.Result.GetResult<Prisma.$SEOMetaPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one SEOMeta that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SEOMetaFindUniqueOrThrowArgs} args - Arguments to find a SEOMeta
   * @example
   * // Get one SEOMeta
   * const sEOMeta = await prisma.sEOMeta.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SEOMetaFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SEOMetaFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SEOMetaClient<runtime.Types.Result.GetResult<Prisma.$SEOMetaPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SEOMeta that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SEOMetaFindFirstArgs} args - Arguments to find a SEOMeta
   * @example
   * // Get one SEOMeta
   * const sEOMeta = await prisma.sEOMeta.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SEOMetaFindFirstArgs>(args?: Prisma.SelectSubset<T, SEOMetaFindFirstArgs<ExtArgs>>): Prisma.Prisma__SEOMetaClient<runtime.Types.Result.GetResult<Prisma.$SEOMetaPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first SEOMeta that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SEOMetaFindFirstOrThrowArgs} args - Arguments to find a SEOMeta
   * @example
   * // Get one SEOMeta
   * const sEOMeta = await prisma.sEOMeta.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SEOMetaFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SEOMetaFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SEOMetaClient<runtime.Types.Result.GetResult<Prisma.$SEOMetaPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more SEOMetas that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SEOMetaFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all SEOMetas
   * const sEOMetas = await prisma.sEOMeta.findMany()
   * 
   * // Get first 10 SEOMetas
   * const sEOMetas = await prisma.sEOMeta.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const sEOMetaWithIdOnly = await prisma.sEOMeta.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends SEOMetaFindManyArgs>(args?: Prisma.SelectSubset<T, SEOMetaFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SEOMetaPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a SEOMeta.
   * @param {SEOMetaCreateArgs} args - Arguments to create a SEOMeta.
   * @example
   * // Create one SEOMeta
   * const SEOMeta = await prisma.sEOMeta.create({
   *   data: {
   *     // ... data to create a SEOMeta
   *   }
   * })
   * 
   */
  create<T extends SEOMetaCreateArgs>(args: Prisma.SelectSubset<T, SEOMetaCreateArgs<ExtArgs>>): Prisma.Prisma__SEOMetaClient<runtime.Types.Result.GetResult<Prisma.$SEOMetaPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many SEOMetas.
   * @param {SEOMetaCreateManyArgs} args - Arguments to create many SEOMetas.
   * @example
   * // Create many SEOMetas
   * const sEOMeta = await prisma.sEOMeta.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SEOMetaCreateManyArgs>(args?: Prisma.SelectSubset<T, SEOMetaCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many SEOMetas and returns the data saved in the database.
   * @param {SEOMetaCreateManyAndReturnArgs} args - Arguments to create many SEOMetas.
   * @example
   * // Create many SEOMetas
   * const sEOMeta = await prisma.sEOMeta.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many SEOMetas and only return the `id`
   * const sEOMetaWithIdOnly = await prisma.sEOMeta.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SEOMetaCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SEOMetaCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SEOMetaPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a SEOMeta.
   * @param {SEOMetaDeleteArgs} args - Arguments to delete one SEOMeta.
   * @example
   * // Delete one SEOMeta
   * const SEOMeta = await prisma.sEOMeta.delete({
   *   where: {
   *     // ... filter to delete one SEOMeta
   *   }
   * })
   * 
   */
  delete<T extends SEOMetaDeleteArgs>(args: Prisma.SelectSubset<T, SEOMetaDeleteArgs<ExtArgs>>): Prisma.Prisma__SEOMetaClient<runtime.Types.Result.GetResult<Prisma.$SEOMetaPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one SEOMeta.
   * @param {SEOMetaUpdateArgs} args - Arguments to update one SEOMeta.
   * @example
   * // Update one SEOMeta
   * const sEOMeta = await prisma.sEOMeta.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SEOMetaUpdateArgs>(args: Prisma.SelectSubset<T, SEOMetaUpdateArgs<ExtArgs>>): Prisma.Prisma__SEOMetaClient<runtime.Types.Result.GetResult<Prisma.$SEOMetaPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more SEOMetas.
   * @param {SEOMetaDeleteManyArgs} args - Arguments to filter SEOMetas to delete.
   * @example
   * // Delete a few SEOMetas
   * const { count } = await prisma.sEOMeta.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SEOMetaDeleteManyArgs>(args?: Prisma.SelectSubset<T, SEOMetaDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SEOMetas.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SEOMetaUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many SEOMetas
   * const sEOMeta = await prisma.sEOMeta.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SEOMetaUpdateManyArgs>(args: Prisma.SelectSubset<T, SEOMetaUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more SEOMetas and returns the data updated in the database.
   * @param {SEOMetaUpdateManyAndReturnArgs} args - Arguments to update many SEOMetas.
   * @example
   * // Update many SEOMetas
   * const sEOMeta = await prisma.sEOMeta.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more SEOMetas and only return the `id`
   * const sEOMetaWithIdOnly = await prisma.sEOMeta.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SEOMetaUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SEOMetaUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SEOMetaPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one SEOMeta.
   * @param {SEOMetaUpsertArgs} args - Arguments to update or create a SEOMeta.
   * @example
   * // Update or create a SEOMeta
   * const sEOMeta = await prisma.sEOMeta.upsert({
   *   create: {
   *     // ... data to create a SEOMeta
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the SEOMeta we want to update
   *   }
   * })
   */
  upsert<T extends SEOMetaUpsertArgs>(args: Prisma.SelectSubset<T, SEOMetaUpsertArgs<ExtArgs>>): Prisma.Prisma__SEOMetaClient<runtime.Types.Result.GetResult<Prisma.$SEOMetaPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of SEOMetas.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SEOMetaCountArgs} args - Arguments to filter SEOMetas to count.
   * @example
   * // Count the number of SEOMetas
   * const count = await prisma.sEOMeta.count({
   *   where: {
   *     // ... the filter for the SEOMetas we want to count
   *   }
   * })
  **/
  count<T extends SEOMetaCountArgs>(
    args?: Prisma.Subset<T, SEOMetaCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SEOMetaCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a SEOMeta.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SEOMetaAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SEOMetaAggregateArgs>(args: Prisma.Subset<T, SEOMetaAggregateArgs>): Prisma.PrismaPromise<GetSEOMetaAggregateType<T>>

  /**
   * Group by SEOMeta.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SEOMetaGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SEOMetaGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SEOMetaGroupByArgs['orderBy'] }
      : { orderBy?: SEOMetaGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SEOMetaGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSEOMetaGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the SEOMeta model
 */
readonly fields: SEOMetaFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for SEOMeta.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SEOMetaClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the SEOMeta model
 */
export interface SEOMetaFieldRefs {
  readonly id: Prisma.FieldRef<"SEOMeta", 'String'>
  readonly path: Prisma.FieldRef<"SEOMeta", 'String'>
  readonly title: Prisma.FieldRef<"SEOMeta", 'String'>
  readonly description: Prisma.FieldRef<"SEOMeta", 'String'>
  readonly keywords: Prisma.FieldRef<"SEOMeta", 'String'>
  readonly ogImage: Prisma.FieldRef<"SEOMeta", 'String'>
  readonly createdAt: Prisma.FieldRef<"SEOMeta", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"SEOMeta", 'DateTime'>
}
    

// Custom InputTypes
/**
 * SEOMeta findUnique
 */
export type SEOMetaFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SEOMeta
   */
  select?: Prisma.SEOMetaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SEOMeta
   */
  omit?: Prisma.SEOMetaOmit<ExtArgs> | null
  /**
   * Filter, which SEOMeta to fetch.
   */
  where: Prisma.SEOMetaWhereUniqueInput
}

/**
 * SEOMeta findUniqueOrThrow
 */
export type SEOMetaFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SEOMeta
   */
  select?: Prisma.SEOMetaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SEOMeta
   */
  omit?: Prisma.SEOMetaOmit<ExtArgs> | null
  /**
   * Filter, which SEOMeta to fetch.
   */
  where: Prisma.SEOMetaWhereUniqueInput
}

/**
 * SEOMeta findFirst
 */
export type SEOMetaFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SEOMeta
   */
  select?: Prisma.SEOMetaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SEOMeta
   */
  omit?: Prisma.SEOMetaOmit<ExtArgs> | null
  /**
   * Filter, which SEOMeta to fetch.
   */
  where?: Prisma.SEOMetaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SEOMetas to fetch.
   */
  orderBy?: Prisma.SEOMetaOrderByWithRelationInput | Prisma.SEOMetaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SEOMetas.
   */
  cursor?: Prisma.SEOMetaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SEOMetas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SEOMetas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SEOMetas.
   */
  distinct?: Prisma.SEOMetaScalarFieldEnum | Prisma.SEOMetaScalarFieldEnum[]
}

/**
 * SEOMeta findFirstOrThrow
 */
export type SEOMetaFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SEOMeta
   */
  select?: Prisma.SEOMetaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SEOMeta
   */
  omit?: Prisma.SEOMetaOmit<ExtArgs> | null
  /**
   * Filter, which SEOMeta to fetch.
   */
  where?: Prisma.SEOMetaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SEOMetas to fetch.
   */
  orderBy?: Prisma.SEOMetaOrderByWithRelationInput | Prisma.SEOMetaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for SEOMetas.
   */
  cursor?: Prisma.SEOMetaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SEOMetas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SEOMetas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SEOMetas.
   */
  distinct?: Prisma.SEOMetaScalarFieldEnum | Prisma.SEOMetaScalarFieldEnum[]
}

/**
 * SEOMeta findMany
 */
export type SEOMetaFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SEOMeta
   */
  select?: Prisma.SEOMetaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SEOMeta
   */
  omit?: Prisma.SEOMetaOmit<ExtArgs> | null
  /**
   * Filter, which SEOMetas to fetch.
   */
  where?: Prisma.SEOMetaWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of SEOMetas to fetch.
   */
  orderBy?: Prisma.SEOMetaOrderByWithRelationInput | Prisma.SEOMetaOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing SEOMetas.
   */
  cursor?: Prisma.SEOMetaWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` SEOMetas from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` SEOMetas.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of SEOMetas.
   */
  distinct?: Prisma.SEOMetaScalarFieldEnum | Prisma.SEOMetaScalarFieldEnum[]
}

/**
 * SEOMeta create
 */
export type SEOMetaCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SEOMeta
   */
  select?: Prisma.SEOMetaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SEOMeta
   */
  omit?: Prisma.SEOMetaOmit<ExtArgs> | null
  /**
   * The data needed to create a SEOMeta.
   */
  data: Prisma.XOR<Prisma.SEOMetaCreateInput, Prisma.SEOMetaUncheckedCreateInput>
}

/**
 * SEOMeta createMany
 */
export type SEOMetaCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many SEOMetas.
   */
  data: Prisma.SEOMetaCreateManyInput | Prisma.SEOMetaCreateManyInput[]
}

/**
 * SEOMeta createManyAndReturn
 */
export type SEOMetaCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SEOMeta
   */
  select?: Prisma.SEOMetaSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SEOMeta
   */
  omit?: Prisma.SEOMetaOmit<ExtArgs> | null
  /**
   * The data used to create many SEOMetas.
   */
  data: Prisma.SEOMetaCreateManyInput | Prisma.SEOMetaCreateManyInput[]
}

/**
 * SEOMeta update
 */
export type SEOMetaUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SEOMeta
   */
  select?: Prisma.SEOMetaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SEOMeta
   */
  omit?: Prisma.SEOMetaOmit<ExtArgs> | null
  /**
   * The data needed to update a SEOMeta.
   */
  data: Prisma.XOR<Prisma.SEOMetaUpdateInput, Prisma.SEOMetaUncheckedUpdateInput>
  /**
   * Choose, which SEOMeta to update.
   */
  where: Prisma.SEOMetaWhereUniqueInput
}

/**
 * SEOMeta updateMany
 */
export type SEOMetaUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update SEOMetas.
   */
  data: Prisma.XOR<Prisma.SEOMetaUpdateManyMutationInput, Prisma.SEOMetaUncheckedUpdateManyInput>
  /**
   * Filter which SEOMetas to update
   */
  where?: Prisma.SEOMetaWhereInput
  /**
   * Limit how many SEOMetas to update.
   */
  limit?: number
}

/**
 * SEOMeta updateManyAndReturn
 */
export type SEOMetaUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SEOMeta
   */
  select?: Prisma.SEOMetaSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the SEOMeta
   */
  omit?: Prisma.SEOMetaOmit<ExtArgs> | null
  /**
   * The data used to update SEOMetas.
   */
  data: Prisma.XOR<Prisma.SEOMetaUpdateManyMutationInput, Prisma.SEOMetaUncheckedUpdateManyInput>
  /**
   * Filter which SEOMetas to update
   */
  where?: Prisma.SEOMetaWhereInput
  /**
   * Limit how many SEOMetas to update.
   */
  limit?: number
}

/**
 * SEOMeta upsert
 */
export type SEOMetaUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SEOMeta
   */
  select?: Prisma.SEOMetaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SEOMeta
   */
  omit?: Prisma.SEOMetaOmit<ExtArgs> | null
  /**
   * The filter to search for the SEOMeta to update in case it exists.
   */
  where: Prisma.SEOMetaWhereUniqueInput
  /**
   * In case the SEOMeta found by the `where` argument doesn't exist, create a new SEOMeta with this data.
   */
  create: Prisma.XOR<Prisma.SEOMetaCreateInput, Prisma.SEOMetaUncheckedCreateInput>
  /**
   * In case the SEOMeta was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SEOMetaUpdateInput, Prisma.SEOMetaUncheckedUpdateInput>
}

/**
 * SEOMeta delete
 */
export type SEOMetaDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SEOMeta
   */
  select?: Prisma.SEOMetaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SEOMeta
   */
  omit?: Prisma.SEOMetaOmit<ExtArgs> | null
  /**
   * Filter which SEOMeta to delete.
   */
  where: Prisma.SEOMetaWhereUniqueInput
}

/**
 * SEOMeta deleteMany
 */
export type SEOMetaDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which SEOMetas to delete
   */
  where?: Prisma.SEOMetaWhereInput
  /**
   * Limit how many SEOMetas to delete.
   */
  limit?: number
}

/**
 * SEOMeta without action
 */
export type SEOMetaDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SEOMeta
   */
  select?: Prisma.SEOMetaSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SEOMeta
   */
  omit?: Prisma.SEOMetaOmit<ExtArgs> | null
}
