
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Skill` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Skill
 * 
 */
export type SkillModel = runtime.Types.Result.DefaultSelection<Prisma.$SkillPayload>

export type AggregateSkill = {
  _count: SkillCountAggregateOutputType | null
  _min: SkillMinAggregateOutputType | null
  _max: SkillMaxAggregateOutputType | null
}

export type SkillMinAggregateOutputType = {
  id: string | null
  slug: string | null
  name: string | null
  description: string | null
  fullContent: string | null
  category: string | null
  subcategory: string | null
  tags: string | null
  tier: string | null
  author: string | null
  version: string | null
  sourcePath: string | null
  sourceType: string | null
  parentGroup: string | null
  isIndexed: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type SkillMaxAggregateOutputType = {
  id: string | null
  slug: string | null
  name: string | null
  description: string | null
  fullContent: string | null
  category: string | null
  subcategory: string | null
  tags: string | null
  tier: string | null
  author: string | null
  version: string | null
  sourcePath: string | null
  sourceType: string | null
  parentGroup: string | null
  isIndexed: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type SkillCountAggregateOutputType = {
  id: number
  slug: number
  name: number
  description: number
  fullContent: number
  category: number
  subcategory: number
  tags: number
  tier: number
  author: number
  version: number
  sourcePath: number
  sourceType: number
  parentGroup: number
  isIndexed: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type SkillMinAggregateInputType = {
  id?: true
  slug?: true
  name?: true
  description?: true
  fullContent?: true
  category?: true
  subcategory?: true
  tags?: true
  tier?: true
  author?: true
  version?: true
  sourcePath?: true
  sourceType?: true
  parentGroup?: true
  isIndexed?: true
  createdAt?: true
  updatedAt?: true
}

export type SkillMaxAggregateInputType = {
  id?: true
  slug?: true
  name?: true
  description?: true
  fullContent?: true
  category?: true
  subcategory?: true
  tags?: true
  tier?: true
  author?: true
  version?: true
  sourcePath?: true
  sourceType?: true
  parentGroup?: true
  isIndexed?: true
  createdAt?: true
  updatedAt?: true
}

export type SkillCountAggregateInputType = {
  id?: true
  slug?: true
  name?: true
  description?: true
  fullContent?: true
  category?: true
  subcategory?: true
  tags?: true
  tier?: true
  author?: true
  version?: true
  sourcePath?: true
  sourceType?: true
  parentGroup?: true
  isIndexed?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type SkillAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Skill to aggregate.
   */
  where?: Prisma.SkillWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Skills to fetch.
   */
  orderBy?: Prisma.SkillOrderByWithRelationInput | Prisma.SkillOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.SkillWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Skills from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Skills.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Skills
  **/
  _count?: true | SkillCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SkillMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SkillMaxAggregateInputType
}

export type GetSkillAggregateType<T extends SkillAggregateArgs> = {
      [P in keyof T & keyof AggregateSkill]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSkill[P]>
    : Prisma.GetScalarType<T[P], AggregateSkill[P]>
}




export type SkillGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SkillWhereInput
  orderBy?: Prisma.SkillOrderByWithAggregationInput | Prisma.SkillOrderByWithAggregationInput[]
  by: Prisma.SkillScalarFieldEnum[] | Prisma.SkillScalarFieldEnum
  having?: Prisma.SkillScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SkillCountAggregateInputType | true
  _min?: SkillMinAggregateInputType
  _max?: SkillMaxAggregateInputType
}

export type SkillGroupByOutputType = {
  id: string
  slug: string
  name: string
  description: string
  fullContent: string
  category: string
  subcategory: string | null
  tags: string
  tier: string | null
  author: string | null
  version: string | null
  sourcePath: string
  sourceType: string
  parentGroup: string | null
  isIndexed: boolean
  createdAt: Date
  updatedAt: Date
  _count: SkillCountAggregateOutputType | null
  _min: SkillMinAggregateOutputType | null
  _max: SkillMaxAggregateOutputType | null
}

export type GetSkillGroupByPayload<T extends SkillGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SkillGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SkillGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SkillGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SkillGroupByOutputType[P]>
      }
    >
  >



export type SkillWhereInput = {
  AND?: Prisma.SkillWhereInput | Prisma.SkillWhereInput[]
  OR?: Prisma.SkillWhereInput[]
  NOT?: Prisma.SkillWhereInput | Prisma.SkillWhereInput[]
  id?: Prisma.StringFilter<"Skill"> | string
  slug?: Prisma.StringFilter<"Skill"> | string
  name?: Prisma.StringFilter<"Skill"> | string
  description?: Prisma.StringFilter<"Skill"> | string
  fullContent?: Prisma.StringFilter<"Skill"> | string
  category?: Prisma.StringFilter<"Skill"> | string
  subcategory?: Prisma.StringNullableFilter<"Skill"> | string | null
  tags?: Prisma.StringFilter<"Skill"> | string
  tier?: Prisma.StringNullableFilter<"Skill"> | string | null
  author?: Prisma.StringNullableFilter<"Skill"> | string | null
  version?: Prisma.StringNullableFilter<"Skill"> | string | null
  sourcePath?: Prisma.StringFilter<"Skill"> | string
  sourceType?: Prisma.StringFilter<"Skill"> | string
  parentGroup?: Prisma.StringNullableFilter<"Skill"> | string | null
  isIndexed?: Prisma.BoolFilter<"Skill"> | boolean
  createdAt?: Prisma.DateTimeFilter<"Skill"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Skill"> | Date | string
  favorites?: Prisma.FavoriteListRelationFilter
  history?: Prisma.HistoryListRelationFilter
  workflowSteps?: Prisma.WorkflowStepListRelationFilter
}

export type SkillOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  fullContent?: Prisma.SortOrder
  category?: Prisma.SortOrder
  subcategory?: Prisma.SortOrderInput | Prisma.SortOrder
  tags?: Prisma.SortOrder
  tier?: Prisma.SortOrderInput | Prisma.SortOrder
  author?: Prisma.SortOrderInput | Prisma.SortOrder
  version?: Prisma.SortOrderInput | Prisma.SortOrder
  sourcePath?: Prisma.SortOrder
  sourceType?: Prisma.SortOrder
  parentGroup?: Prisma.SortOrderInput | Prisma.SortOrder
  isIndexed?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  favorites?: Prisma.FavoriteOrderByRelationAggregateInput
  history?: Prisma.HistoryOrderByRelationAggregateInput
  workflowSteps?: Prisma.WorkflowStepOrderByRelationAggregateInput
}

export type SkillWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  slug?: string
  AND?: Prisma.SkillWhereInput | Prisma.SkillWhereInput[]
  OR?: Prisma.SkillWhereInput[]
  NOT?: Prisma.SkillWhereInput | Prisma.SkillWhereInput[]
  name?: Prisma.StringFilter<"Skill"> | string
  description?: Prisma.StringFilter<"Skill"> | string
  fullContent?: Prisma.StringFilter<"Skill"> | string
  category?: Prisma.StringFilter<"Skill"> | string
  subcategory?: Prisma.StringNullableFilter<"Skill"> | string | null
  tags?: Prisma.StringFilter<"Skill"> | string
  tier?: Prisma.StringNullableFilter<"Skill"> | string | null
  author?: Prisma.StringNullableFilter<"Skill"> | string | null
  version?: Prisma.StringNullableFilter<"Skill"> | string | null
  sourcePath?: Prisma.StringFilter<"Skill"> | string
  sourceType?: Prisma.StringFilter<"Skill"> | string
  parentGroup?: Prisma.StringNullableFilter<"Skill"> | string | null
  isIndexed?: Prisma.BoolFilter<"Skill"> | boolean
  createdAt?: Prisma.DateTimeFilter<"Skill"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Skill"> | Date | string
  favorites?: Prisma.FavoriteListRelationFilter
  history?: Prisma.HistoryListRelationFilter
  workflowSteps?: Prisma.WorkflowStepListRelationFilter
}, "id" | "slug">

export type SkillOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  fullContent?: Prisma.SortOrder
  category?: Prisma.SortOrder
  subcategory?: Prisma.SortOrderInput | Prisma.SortOrder
  tags?: Prisma.SortOrder
  tier?: Prisma.SortOrderInput | Prisma.SortOrder
  author?: Prisma.SortOrderInput | Prisma.SortOrder
  version?: Prisma.SortOrderInput | Prisma.SortOrder
  sourcePath?: Prisma.SortOrder
  sourceType?: Prisma.SortOrder
  parentGroup?: Prisma.SortOrderInput | Prisma.SortOrder
  isIndexed?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.SkillCountOrderByAggregateInput
  _max?: Prisma.SkillMaxOrderByAggregateInput
  _min?: Prisma.SkillMinOrderByAggregateInput
}

export type SkillScalarWhereWithAggregatesInput = {
  AND?: Prisma.SkillScalarWhereWithAggregatesInput | Prisma.SkillScalarWhereWithAggregatesInput[]
  OR?: Prisma.SkillScalarWhereWithAggregatesInput[]
  NOT?: Prisma.SkillScalarWhereWithAggregatesInput | Prisma.SkillScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Skill"> | string
  slug?: Prisma.StringWithAggregatesFilter<"Skill"> | string
  name?: Prisma.StringWithAggregatesFilter<"Skill"> | string
  description?: Prisma.StringWithAggregatesFilter<"Skill"> | string
  fullContent?: Prisma.StringWithAggregatesFilter<"Skill"> | string
  category?: Prisma.StringWithAggregatesFilter<"Skill"> | string
  subcategory?: Prisma.StringNullableWithAggregatesFilter<"Skill"> | string | null
  tags?: Prisma.StringWithAggregatesFilter<"Skill"> | string
  tier?: Prisma.StringNullableWithAggregatesFilter<"Skill"> | string | null
  author?: Prisma.StringNullableWithAggregatesFilter<"Skill"> | string | null
  version?: Prisma.StringNullableWithAggregatesFilter<"Skill"> | string | null
  sourcePath?: Prisma.StringWithAggregatesFilter<"Skill"> | string
  sourceType?: Prisma.StringWithAggregatesFilter<"Skill"> | string
  parentGroup?: Prisma.StringNullableWithAggregatesFilter<"Skill"> | string | null
  isIndexed?: Prisma.BoolWithAggregatesFilter<"Skill"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Skill"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Skill"> | Date | string
}

export type SkillCreateInput = {
  id?: string
  slug: string
  name: string
  description: string
  fullContent: string
  category: string
  subcategory?: string | null
  tags?: string
  tier?: string | null
  author?: string | null
  version?: string | null
  sourcePath: string
  sourceType?: string
  parentGroup?: string | null
  isIndexed?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  favorites?: Prisma.FavoriteCreateNestedManyWithoutSkillInput
  history?: Prisma.HistoryCreateNestedManyWithoutSkillInput
  workflowSteps?: Prisma.WorkflowStepCreateNestedManyWithoutSkillInput
}

export type SkillUncheckedCreateInput = {
  id?: string
  slug: string
  name: string
  description: string
  fullContent: string
  category: string
  subcategory?: string | null
  tags?: string
  tier?: string | null
  author?: string | null
  version?: string | null
  sourcePath: string
  sourceType?: string
  parentGroup?: string | null
  isIndexed?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  favorites?: Prisma.FavoriteUncheckedCreateNestedManyWithoutSkillInput
  history?: Prisma.HistoryUncheckedCreateNestedManyWithoutSkillInput
  workflowSteps?: Prisma.WorkflowStepUncheckedCreateNestedManyWithoutSkillInput
}

export type SkillUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  fullContent?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  subcategory?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tags?: Prisma.StringFieldUpdateOperationsInput | string
  tier?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  author?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  version?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sourcePath?: Prisma.StringFieldUpdateOperationsInput | string
  sourceType?: Prisma.StringFieldUpdateOperationsInput | string
  parentGroup?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isIndexed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  favorites?: Prisma.FavoriteUpdateManyWithoutSkillNestedInput
  history?: Prisma.HistoryUpdateManyWithoutSkillNestedInput
  workflowSteps?: Prisma.WorkflowStepUpdateManyWithoutSkillNestedInput
}

export type SkillUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  fullContent?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  subcategory?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tags?: Prisma.StringFieldUpdateOperationsInput | string
  tier?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  author?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  version?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sourcePath?: Prisma.StringFieldUpdateOperationsInput | string
  sourceType?: Prisma.StringFieldUpdateOperationsInput | string
  parentGroup?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isIndexed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  favorites?: Prisma.FavoriteUncheckedUpdateManyWithoutSkillNestedInput
  history?: Prisma.HistoryUncheckedUpdateManyWithoutSkillNestedInput
  workflowSteps?: Prisma.WorkflowStepUncheckedUpdateManyWithoutSkillNestedInput
}

export type SkillCreateManyInput = {
  id?: string
  slug: string
  name: string
  description: string
  fullContent: string
  category: string
  subcategory?: string | null
  tags?: string
  tier?: string | null
  author?: string | null
  version?: string | null
  sourcePath: string
  sourceType?: string
  parentGroup?: string | null
  isIndexed?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type SkillUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  fullContent?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  subcategory?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tags?: Prisma.StringFieldUpdateOperationsInput | string
  tier?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  author?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  version?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sourcePath?: Prisma.StringFieldUpdateOperationsInput | string
  sourceType?: Prisma.StringFieldUpdateOperationsInput | string
  parentGroup?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isIndexed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SkillUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  fullContent?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  subcategory?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tags?: Prisma.StringFieldUpdateOperationsInput | string
  tier?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  author?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  version?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sourcePath?: Prisma.StringFieldUpdateOperationsInput | string
  sourceType?: Prisma.StringFieldUpdateOperationsInput | string
  parentGroup?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isIndexed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type SkillCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  fullContent?: Prisma.SortOrder
  category?: Prisma.SortOrder
  subcategory?: Prisma.SortOrder
  tags?: Prisma.SortOrder
  tier?: Prisma.SortOrder
  author?: Prisma.SortOrder
  version?: Prisma.SortOrder
  sourcePath?: Prisma.SortOrder
  sourceType?: Prisma.SortOrder
  parentGroup?: Prisma.SortOrder
  isIndexed?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type SkillMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  fullContent?: Prisma.SortOrder
  category?: Prisma.SortOrder
  subcategory?: Prisma.SortOrder
  tags?: Prisma.SortOrder
  tier?: Prisma.SortOrder
  author?: Prisma.SortOrder
  version?: Prisma.SortOrder
  sourcePath?: Prisma.SortOrder
  sourceType?: Prisma.SortOrder
  parentGroup?: Prisma.SortOrder
  isIndexed?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type SkillMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  fullContent?: Prisma.SortOrder
  category?: Prisma.SortOrder
  subcategory?: Prisma.SortOrder
  tags?: Prisma.SortOrder
  tier?: Prisma.SortOrder
  author?: Prisma.SortOrder
  version?: Prisma.SortOrder
  sourcePath?: Prisma.SortOrder
  sourceType?: Prisma.SortOrder
  parentGroup?: Prisma.SortOrder
  isIndexed?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type SkillScalarRelationFilter = {
  is?: Prisma.SkillWhereInput
  isNot?: Prisma.SkillWhereInput
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type SkillCreateNestedOneWithoutWorkflowStepsInput = {
  create?: Prisma.XOR<Prisma.SkillCreateWithoutWorkflowStepsInput, Prisma.SkillUncheckedCreateWithoutWorkflowStepsInput>
  connectOrCreate?: Prisma.SkillCreateOrConnectWithoutWorkflowStepsInput
  connect?: Prisma.SkillWhereUniqueInput
}

export type SkillUpdateOneRequiredWithoutWorkflowStepsNestedInput = {
  create?: Prisma.XOR<Prisma.SkillCreateWithoutWorkflowStepsInput, Prisma.SkillUncheckedCreateWithoutWorkflowStepsInput>
  connectOrCreate?: Prisma.SkillCreateOrConnectWithoutWorkflowStepsInput
  upsert?: Prisma.SkillUpsertWithoutWorkflowStepsInput
  connect?: Prisma.SkillWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.SkillUpdateToOneWithWhereWithoutWorkflowStepsInput, Prisma.SkillUpdateWithoutWorkflowStepsInput>, Prisma.SkillUncheckedUpdateWithoutWorkflowStepsInput>
}

export type SkillCreateNestedOneWithoutFavoritesInput = {
  create?: Prisma.XOR<Prisma.SkillCreateWithoutFavoritesInput, Prisma.SkillUncheckedCreateWithoutFavoritesInput>
  connectOrCreate?: Prisma.SkillCreateOrConnectWithoutFavoritesInput
  connect?: Prisma.SkillWhereUniqueInput
}

export type SkillUpdateOneRequiredWithoutFavoritesNestedInput = {
  create?: Prisma.XOR<Prisma.SkillCreateWithoutFavoritesInput, Prisma.SkillUncheckedCreateWithoutFavoritesInput>
  connectOrCreate?: Prisma.SkillCreateOrConnectWithoutFavoritesInput
  upsert?: Prisma.SkillUpsertWithoutFavoritesInput
  connect?: Prisma.SkillWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.SkillUpdateToOneWithWhereWithoutFavoritesInput, Prisma.SkillUpdateWithoutFavoritesInput>, Prisma.SkillUncheckedUpdateWithoutFavoritesInput>
}

export type SkillCreateNestedOneWithoutHistoryInput = {
  create?: Prisma.XOR<Prisma.SkillCreateWithoutHistoryInput, Prisma.SkillUncheckedCreateWithoutHistoryInput>
  connectOrCreate?: Prisma.SkillCreateOrConnectWithoutHistoryInput
  connect?: Prisma.SkillWhereUniqueInput
}

export type SkillUpdateOneRequiredWithoutHistoryNestedInput = {
  create?: Prisma.XOR<Prisma.SkillCreateWithoutHistoryInput, Prisma.SkillUncheckedCreateWithoutHistoryInput>
  connectOrCreate?: Prisma.SkillCreateOrConnectWithoutHistoryInput
  upsert?: Prisma.SkillUpsertWithoutHistoryInput
  connect?: Prisma.SkillWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.SkillUpdateToOneWithWhereWithoutHistoryInput, Prisma.SkillUpdateWithoutHistoryInput>, Prisma.SkillUncheckedUpdateWithoutHistoryInput>
}

export type SkillCreateWithoutWorkflowStepsInput = {
  id?: string
  slug: string
  name: string
  description: string
  fullContent: string
  category: string
  subcategory?: string | null
  tags?: string
  tier?: string | null
  author?: string | null
  version?: string | null
  sourcePath: string
  sourceType?: string
  parentGroup?: string | null
  isIndexed?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  favorites?: Prisma.FavoriteCreateNestedManyWithoutSkillInput
  history?: Prisma.HistoryCreateNestedManyWithoutSkillInput
}

export type SkillUncheckedCreateWithoutWorkflowStepsInput = {
  id?: string
  slug: string
  name: string
  description: string
  fullContent: string
  category: string
  subcategory?: string | null
  tags?: string
  tier?: string | null
  author?: string | null
  version?: string | null
  sourcePath: string
  sourceType?: string
  parentGroup?: string | null
  isIndexed?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  favorites?: Prisma.FavoriteUncheckedCreateNestedManyWithoutSkillInput
  history?: Prisma.HistoryUncheckedCreateNestedManyWithoutSkillInput
}

export type SkillCreateOrConnectWithoutWorkflowStepsInput = {
  where: Prisma.SkillWhereUniqueInput
  create: Prisma.XOR<Prisma.SkillCreateWithoutWorkflowStepsInput, Prisma.SkillUncheckedCreateWithoutWorkflowStepsInput>
}

export type SkillUpsertWithoutWorkflowStepsInput = {
  update: Prisma.XOR<Prisma.SkillUpdateWithoutWorkflowStepsInput, Prisma.SkillUncheckedUpdateWithoutWorkflowStepsInput>
  create: Prisma.XOR<Prisma.SkillCreateWithoutWorkflowStepsInput, Prisma.SkillUncheckedCreateWithoutWorkflowStepsInput>
  where?: Prisma.SkillWhereInput
}

export type SkillUpdateToOneWithWhereWithoutWorkflowStepsInput = {
  where?: Prisma.SkillWhereInput
  data: Prisma.XOR<Prisma.SkillUpdateWithoutWorkflowStepsInput, Prisma.SkillUncheckedUpdateWithoutWorkflowStepsInput>
}

export type SkillUpdateWithoutWorkflowStepsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  fullContent?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  subcategory?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tags?: Prisma.StringFieldUpdateOperationsInput | string
  tier?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  author?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  version?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sourcePath?: Prisma.StringFieldUpdateOperationsInput | string
  sourceType?: Prisma.StringFieldUpdateOperationsInput | string
  parentGroup?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isIndexed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  favorites?: Prisma.FavoriteUpdateManyWithoutSkillNestedInput
  history?: Prisma.HistoryUpdateManyWithoutSkillNestedInput
}

export type SkillUncheckedUpdateWithoutWorkflowStepsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  fullContent?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  subcategory?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tags?: Prisma.StringFieldUpdateOperationsInput | string
  tier?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  author?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  version?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sourcePath?: Prisma.StringFieldUpdateOperationsInput | string
  sourceType?: Prisma.StringFieldUpdateOperationsInput | string
  parentGroup?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isIndexed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  favorites?: Prisma.FavoriteUncheckedUpdateManyWithoutSkillNestedInput
  history?: Prisma.HistoryUncheckedUpdateManyWithoutSkillNestedInput
}

export type SkillCreateWithoutFavoritesInput = {
  id?: string
  slug: string
  name: string
  description: string
  fullContent: string
  category: string
  subcategory?: string | null
  tags?: string
  tier?: string | null
  author?: string | null
  version?: string | null
  sourcePath: string
  sourceType?: string
  parentGroup?: string | null
  isIndexed?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  history?: Prisma.HistoryCreateNestedManyWithoutSkillInput
  workflowSteps?: Prisma.WorkflowStepCreateNestedManyWithoutSkillInput
}

export type SkillUncheckedCreateWithoutFavoritesInput = {
  id?: string
  slug: string
  name: string
  description: string
  fullContent: string
  category: string
  subcategory?: string | null
  tags?: string
  tier?: string | null
  author?: string | null
  version?: string | null
  sourcePath: string
  sourceType?: string
  parentGroup?: string | null
  isIndexed?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  history?: Prisma.HistoryUncheckedCreateNestedManyWithoutSkillInput
  workflowSteps?: Prisma.WorkflowStepUncheckedCreateNestedManyWithoutSkillInput
}

export type SkillCreateOrConnectWithoutFavoritesInput = {
  where: Prisma.SkillWhereUniqueInput
  create: Prisma.XOR<Prisma.SkillCreateWithoutFavoritesInput, Prisma.SkillUncheckedCreateWithoutFavoritesInput>
}

export type SkillUpsertWithoutFavoritesInput = {
  update: Prisma.XOR<Prisma.SkillUpdateWithoutFavoritesInput, Prisma.SkillUncheckedUpdateWithoutFavoritesInput>
  create: Prisma.XOR<Prisma.SkillCreateWithoutFavoritesInput, Prisma.SkillUncheckedCreateWithoutFavoritesInput>
  where?: Prisma.SkillWhereInput
}

export type SkillUpdateToOneWithWhereWithoutFavoritesInput = {
  where?: Prisma.SkillWhereInput
  data: Prisma.XOR<Prisma.SkillUpdateWithoutFavoritesInput, Prisma.SkillUncheckedUpdateWithoutFavoritesInput>
}

export type SkillUpdateWithoutFavoritesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  fullContent?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  subcategory?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tags?: Prisma.StringFieldUpdateOperationsInput | string
  tier?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  author?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  version?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sourcePath?: Prisma.StringFieldUpdateOperationsInput | string
  sourceType?: Prisma.StringFieldUpdateOperationsInput | string
  parentGroup?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isIndexed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  history?: Prisma.HistoryUpdateManyWithoutSkillNestedInput
  workflowSteps?: Prisma.WorkflowStepUpdateManyWithoutSkillNestedInput
}

export type SkillUncheckedUpdateWithoutFavoritesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  fullContent?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  subcategory?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tags?: Prisma.StringFieldUpdateOperationsInput | string
  tier?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  author?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  version?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sourcePath?: Prisma.StringFieldUpdateOperationsInput | string
  sourceType?: Prisma.StringFieldUpdateOperationsInput | string
  parentGroup?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isIndexed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  history?: Prisma.HistoryUncheckedUpdateManyWithoutSkillNestedInput
  workflowSteps?: Prisma.WorkflowStepUncheckedUpdateManyWithoutSkillNestedInput
}

export type SkillCreateWithoutHistoryInput = {
  id?: string
  slug: string
  name: string
  description: string
  fullContent: string
  category: string
  subcategory?: string | null
  tags?: string
  tier?: string | null
  author?: string | null
  version?: string | null
  sourcePath: string
  sourceType?: string
  parentGroup?: string | null
  isIndexed?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  favorites?: Prisma.FavoriteCreateNestedManyWithoutSkillInput
  workflowSteps?: Prisma.WorkflowStepCreateNestedManyWithoutSkillInput
}

export type SkillUncheckedCreateWithoutHistoryInput = {
  id?: string
  slug: string
  name: string
  description: string
  fullContent: string
  category: string
  subcategory?: string | null
  tags?: string
  tier?: string | null
  author?: string | null
  version?: string | null
  sourcePath: string
  sourceType?: string
  parentGroup?: string | null
  isIndexed?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  favorites?: Prisma.FavoriteUncheckedCreateNestedManyWithoutSkillInput
  workflowSteps?: Prisma.WorkflowStepUncheckedCreateNestedManyWithoutSkillInput
}

export type SkillCreateOrConnectWithoutHistoryInput = {
  where: Prisma.SkillWhereUniqueInput
  create: Prisma.XOR<Prisma.SkillCreateWithoutHistoryInput, Prisma.SkillUncheckedCreateWithoutHistoryInput>
}

export type SkillUpsertWithoutHistoryInput = {
  update: Prisma.XOR<Prisma.SkillUpdateWithoutHistoryInput, Prisma.SkillUncheckedUpdateWithoutHistoryInput>
  create: Prisma.XOR<Prisma.SkillCreateWithoutHistoryInput, Prisma.SkillUncheckedCreateWithoutHistoryInput>
  where?: Prisma.SkillWhereInput
}

export type SkillUpdateToOneWithWhereWithoutHistoryInput = {
  where?: Prisma.SkillWhereInput
  data: Prisma.XOR<Prisma.SkillUpdateWithoutHistoryInput, Prisma.SkillUncheckedUpdateWithoutHistoryInput>
}

export type SkillUpdateWithoutHistoryInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  fullContent?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  subcategory?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tags?: Prisma.StringFieldUpdateOperationsInput | string
  tier?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  author?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  version?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sourcePath?: Prisma.StringFieldUpdateOperationsInput | string
  sourceType?: Prisma.StringFieldUpdateOperationsInput | string
  parentGroup?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isIndexed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  favorites?: Prisma.FavoriteUpdateManyWithoutSkillNestedInput
  workflowSteps?: Prisma.WorkflowStepUpdateManyWithoutSkillNestedInput
}

export type SkillUncheckedUpdateWithoutHistoryInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.StringFieldUpdateOperationsInput | string
  fullContent?: Prisma.StringFieldUpdateOperationsInput | string
  category?: Prisma.StringFieldUpdateOperationsInput | string
  subcategory?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  tags?: Prisma.StringFieldUpdateOperationsInput | string
  tier?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  author?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  version?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sourcePath?: Prisma.StringFieldUpdateOperationsInput | string
  sourceType?: Prisma.StringFieldUpdateOperationsInput | string
  parentGroup?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isIndexed?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  favorites?: Prisma.FavoriteUncheckedUpdateManyWithoutSkillNestedInput
  workflowSteps?: Prisma.WorkflowStepUncheckedUpdateManyWithoutSkillNestedInput
}


/**
 * Count Type SkillCountOutputType
 */

export type SkillCountOutputType = {
  favorites: number
  history: number
  workflowSteps: number
}

export type SkillCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  favorites?: boolean | SkillCountOutputTypeCountFavoritesArgs
  history?: boolean | SkillCountOutputTypeCountHistoryArgs
  workflowSteps?: boolean | SkillCountOutputTypeCountWorkflowStepsArgs
}

/**
 * SkillCountOutputType without action
 */
export type SkillCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SkillCountOutputType
   */
  select?: Prisma.SkillCountOutputTypeSelect<ExtArgs> | null
}

/**
 * SkillCountOutputType without action
 */
export type SkillCountOutputTypeCountFavoritesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FavoriteWhereInput
}

/**
 * SkillCountOutputType without action
 */
export type SkillCountOutputTypeCountHistoryArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.HistoryWhereInput
}

/**
 * SkillCountOutputType without action
 */
export type SkillCountOutputTypeCountWorkflowStepsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.WorkflowStepWhereInput
}


export type SkillSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  slug?: boolean
  name?: boolean
  description?: boolean
  fullContent?: boolean
  category?: boolean
  subcategory?: boolean
  tags?: boolean
  tier?: boolean
  author?: boolean
  version?: boolean
  sourcePath?: boolean
  sourceType?: boolean
  parentGroup?: boolean
  isIndexed?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  favorites?: boolean | Prisma.Skill$favoritesArgs<ExtArgs>
  history?: boolean | Prisma.Skill$historyArgs<ExtArgs>
  workflowSteps?: boolean | Prisma.Skill$workflowStepsArgs<ExtArgs>
  _count?: boolean | Prisma.SkillCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["skill"]>

export type SkillSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  slug?: boolean
  name?: boolean
  description?: boolean
  fullContent?: boolean
  category?: boolean
  subcategory?: boolean
  tags?: boolean
  tier?: boolean
  author?: boolean
  version?: boolean
  sourcePath?: boolean
  sourceType?: boolean
  parentGroup?: boolean
  isIndexed?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["skill"]>

export type SkillSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  slug?: boolean
  name?: boolean
  description?: boolean
  fullContent?: boolean
  category?: boolean
  subcategory?: boolean
  tags?: boolean
  tier?: boolean
  author?: boolean
  version?: boolean
  sourcePath?: boolean
  sourceType?: boolean
  parentGroup?: boolean
  isIndexed?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["skill"]>

export type SkillSelectScalar = {
  id?: boolean
  slug?: boolean
  name?: boolean
  description?: boolean
  fullContent?: boolean
  category?: boolean
  subcategory?: boolean
  tags?: boolean
  tier?: boolean
  author?: boolean
  version?: boolean
  sourcePath?: boolean
  sourceType?: boolean
  parentGroup?: boolean
  isIndexed?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type SkillOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "slug" | "name" | "description" | "fullContent" | "category" | "subcategory" | "tags" | "tier" | "author" | "version" | "sourcePath" | "sourceType" | "parentGroup" | "isIndexed" | "createdAt" | "updatedAt", ExtArgs["result"]["skill"]>
export type SkillInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  favorites?: boolean | Prisma.Skill$favoritesArgs<ExtArgs>
  history?: boolean | Prisma.Skill$historyArgs<ExtArgs>
  workflowSteps?: boolean | Prisma.Skill$workflowStepsArgs<ExtArgs>
  _count?: boolean | Prisma.SkillCountOutputTypeDefaultArgs<ExtArgs>
}
export type SkillIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type SkillIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $SkillPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Skill"
  objects: {
    favorites: Prisma.$FavoritePayload<ExtArgs>[]
    history: Prisma.$HistoryPayload<ExtArgs>[]
    workflowSteps: Prisma.$WorkflowStepPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    slug: string
    name: string
    description: string
    fullContent: string
    category: string
    subcategory: string | null
    tags: string
    tier: string | null
    author: string | null
    version: string | null
    sourcePath: string
    sourceType: string
    parentGroup: string | null
    isIndexed: boolean
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["skill"]>
  composites: {}
}

export type SkillGetPayload<S extends boolean | null | undefined | SkillDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SkillPayload, S>

export type SkillCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<SkillFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SkillCountAggregateInputType | true
  }

export interface SkillDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Skill'], meta: { name: 'Skill' } }
  /**
   * Find zero or one Skill that matches the filter.
   * @param {SkillFindUniqueArgs} args - Arguments to find a Skill
   * @example
   * // Get one Skill
   * const skill = await prisma.skill.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends SkillFindUniqueArgs>(args: Prisma.SelectSubset<T, SkillFindUniqueArgs<ExtArgs>>): Prisma.Prisma__SkillClient<runtime.Types.Result.GetResult<Prisma.$SkillPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Skill that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {SkillFindUniqueOrThrowArgs} args - Arguments to find a Skill
   * @example
   * // Get one Skill
   * const skill = await prisma.skill.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends SkillFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, SkillFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__SkillClient<runtime.Types.Result.GetResult<Prisma.$SkillPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Skill that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SkillFindFirstArgs} args - Arguments to find a Skill
   * @example
   * // Get one Skill
   * const skill = await prisma.skill.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends SkillFindFirstArgs>(args?: Prisma.SelectSubset<T, SkillFindFirstArgs<ExtArgs>>): Prisma.Prisma__SkillClient<runtime.Types.Result.GetResult<Prisma.$SkillPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Skill that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SkillFindFirstOrThrowArgs} args - Arguments to find a Skill
   * @example
   * // Get one Skill
   * const skill = await prisma.skill.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends SkillFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, SkillFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__SkillClient<runtime.Types.Result.GetResult<Prisma.$SkillPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Skills that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SkillFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Skills
   * const skills = await prisma.skill.findMany()
   * 
   * // Get first 10 Skills
   * const skills = await prisma.skill.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const skillWithIdOnly = await prisma.skill.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends SkillFindManyArgs>(args?: Prisma.SelectSubset<T, SkillFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SkillPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Skill.
   * @param {SkillCreateArgs} args - Arguments to create a Skill.
   * @example
   * // Create one Skill
   * const Skill = await prisma.skill.create({
   *   data: {
   *     // ... data to create a Skill
   *   }
   * })
   * 
   */
  create<T extends SkillCreateArgs>(args: Prisma.SelectSubset<T, SkillCreateArgs<ExtArgs>>): Prisma.Prisma__SkillClient<runtime.Types.Result.GetResult<Prisma.$SkillPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Skills.
   * @param {SkillCreateManyArgs} args - Arguments to create many Skills.
   * @example
   * // Create many Skills
   * const skill = await prisma.skill.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends SkillCreateManyArgs>(args?: Prisma.SelectSubset<T, SkillCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Skills and returns the data saved in the database.
   * @param {SkillCreateManyAndReturnArgs} args - Arguments to create many Skills.
   * @example
   * // Create many Skills
   * const skill = await prisma.skill.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Skills and only return the `id`
   * const skillWithIdOnly = await prisma.skill.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends SkillCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, SkillCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SkillPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Skill.
   * @param {SkillDeleteArgs} args - Arguments to delete one Skill.
   * @example
   * // Delete one Skill
   * const Skill = await prisma.skill.delete({
   *   where: {
   *     // ... filter to delete one Skill
   *   }
   * })
   * 
   */
  delete<T extends SkillDeleteArgs>(args: Prisma.SelectSubset<T, SkillDeleteArgs<ExtArgs>>): Prisma.Prisma__SkillClient<runtime.Types.Result.GetResult<Prisma.$SkillPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Skill.
   * @param {SkillUpdateArgs} args - Arguments to update one Skill.
   * @example
   * // Update one Skill
   * const skill = await prisma.skill.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends SkillUpdateArgs>(args: Prisma.SelectSubset<T, SkillUpdateArgs<ExtArgs>>): Prisma.Prisma__SkillClient<runtime.Types.Result.GetResult<Prisma.$SkillPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Skills.
   * @param {SkillDeleteManyArgs} args - Arguments to filter Skills to delete.
   * @example
   * // Delete a few Skills
   * const { count } = await prisma.skill.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends SkillDeleteManyArgs>(args?: Prisma.SelectSubset<T, SkillDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Skills.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SkillUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Skills
   * const skill = await prisma.skill.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends SkillUpdateManyArgs>(args: Prisma.SelectSubset<T, SkillUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Skills and returns the data updated in the database.
   * @param {SkillUpdateManyAndReturnArgs} args - Arguments to update many Skills.
   * @example
   * // Update many Skills
   * const skill = await prisma.skill.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Skills and only return the `id`
   * const skillWithIdOnly = await prisma.skill.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends SkillUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, SkillUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SkillPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Skill.
   * @param {SkillUpsertArgs} args - Arguments to update or create a Skill.
   * @example
   * // Update or create a Skill
   * const skill = await prisma.skill.upsert({
   *   create: {
   *     // ... data to create a Skill
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Skill we want to update
   *   }
   * })
   */
  upsert<T extends SkillUpsertArgs>(args: Prisma.SelectSubset<T, SkillUpsertArgs<ExtArgs>>): Prisma.Prisma__SkillClient<runtime.Types.Result.GetResult<Prisma.$SkillPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Skills.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SkillCountArgs} args - Arguments to filter Skills to count.
   * @example
   * // Count the number of Skills
   * const count = await prisma.skill.count({
   *   where: {
   *     // ... the filter for the Skills we want to count
   *   }
   * })
  **/
  count<T extends SkillCountArgs>(
    args?: Prisma.Subset<T, SkillCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SkillCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Skill.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SkillAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SkillAggregateArgs>(args: Prisma.Subset<T, SkillAggregateArgs>): Prisma.PrismaPromise<GetSkillAggregateType<T>>

  /**
   * Group by Skill.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SkillGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends SkillGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: SkillGroupByArgs['orderBy'] }
      : { orderBy?: SkillGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, SkillGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSkillGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Skill model
 */
readonly fields: SkillFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Skill.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__SkillClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  favorites<T extends Prisma.Skill$favoritesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Skill$favoritesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FavoritePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  history<T extends Prisma.Skill$historyArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Skill$historyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$HistoryPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  workflowSteps<T extends Prisma.Skill$workflowStepsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Skill$workflowStepsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WorkflowStepPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Skill model
 */
export interface SkillFieldRefs {
  readonly id: Prisma.FieldRef<"Skill", 'String'>
  readonly slug: Prisma.FieldRef<"Skill", 'String'>
  readonly name: Prisma.FieldRef<"Skill", 'String'>
  readonly description: Prisma.FieldRef<"Skill", 'String'>
  readonly fullContent: Prisma.FieldRef<"Skill", 'String'>
  readonly category: Prisma.FieldRef<"Skill", 'String'>
  readonly subcategory: Prisma.FieldRef<"Skill", 'String'>
  readonly tags: Prisma.FieldRef<"Skill", 'String'>
  readonly tier: Prisma.FieldRef<"Skill", 'String'>
  readonly author: Prisma.FieldRef<"Skill", 'String'>
  readonly version: Prisma.FieldRef<"Skill", 'String'>
  readonly sourcePath: Prisma.FieldRef<"Skill", 'String'>
  readonly sourceType: Prisma.FieldRef<"Skill", 'String'>
  readonly parentGroup: Prisma.FieldRef<"Skill", 'String'>
  readonly isIndexed: Prisma.FieldRef<"Skill", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"Skill", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Skill", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Skill findUnique
 */
export type SkillFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Skill
   */
  select?: Prisma.SkillSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Skill
   */
  omit?: Prisma.SkillOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SkillInclude<ExtArgs> | null
  /**
   * Filter, which Skill to fetch.
   */
  where: Prisma.SkillWhereUniqueInput
}

/**
 * Skill findUniqueOrThrow
 */
export type SkillFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Skill
   */
  select?: Prisma.SkillSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Skill
   */
  omit?: Prisma.SkillOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SkillInclude<ExtArgs> | null
  /**
   * Filter, which Skill to fetch.
   */
  where: Prisma.SkillWhereUniqueInput
}

/**
 * Skill findFirst
 */
export type SkillFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Skill
   */
  select?: Prisma.SkillSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Skill
   */
  omit?: Prisma.SkillOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SkillInclude<ExtArgs> | null
  /**
   * Filter, which Skill to fetch.
   */
  where?: Prisma.SkillWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Skills to fetch.
   */
  orderBy?: Prisma.SkillOrderByWithRelationInput | Prisma.SkillOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Skills.
   */
  cursor?: Prisma.SkillWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Skills from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Skills.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Skills.
   */
  distinct?: Prisma.SkillScalarFieldEnum | Prisma.SkillScalarFieldEnum[]
}

/**
 * Skill findFirstOrThrow
 */
export type SkillFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Skill
   */
  select?: Prisma.SkillSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Skill
   */
  omit?: Prisma.SkillOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SkillInclude<ExtArgs> | null
  /**
   * Filter, which Skill to fetch.
   */
  where?: Prisma.SkillWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Skills to fetch.
   */
  orderBy?: Prisma.SkillOrderByWithRelationInput | Prisma.SkillOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Skills.
   */
  cursor?: Prisma.SkillWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Skills from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Skills.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Skills.
   */
  distinct?: Prisma.SkillScalarFieldEnum | Prisma.SkillScalarFieldEnum[]
}

/**
 * Skill findMany
 */
export type SkillFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Skill
   */
  select?: Prisma.SkillSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Skill
   */
  omit?: Prisma.SkillOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SkillInclude<ExtArgs> | null
  /**
   * Filter, which Skills to fetch.
   */
  where?: Prisma.SkillWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Skills to fetch.
   */
  orderBy?: Prisma.SkillOrderByWithRelationInput | Prisma.SkillOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Skills.
   */
  cursor?: Prisma.SkillWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Skills from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Skills.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Skills.
   */
  distinct?: Prisma.SkillScalarFieldEnum | Prisma.SkillScalarFieldEnum[]
}

/**
 * Skill create
 */
export type SkillCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Skill
   */
  select?: Prisma.SkillSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Skill
   */
  omit?: Prisma.SkillOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SkillInclude<ExtArgs> | null
  /**
   * The data needed to create a Skill.
   */
  data: Prisma.XOR<Prisma.SkillCreateInput, Prisma.SkillUncheckedCreateInput>
}

/**
 * Skill createMany
 */
export type SkillCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Skills.
   */
  data: Prisma.SkillCreateManyInput | Prisma.SkillCreateManyInput[]
}

/**
 * Skill createManyAndReturn
 */
export type SkillCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Skill
   */
  select?: Prisma.SkillSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Skill
   */
  omit?: Prisma.SkillOmit<ExtArgs> | null
  /**
   * The data used to create many Skills.
   */
  data: Prisma.SkillCreateManyInput | Prisma.SkillCreateManyInput[]
}

/**
 * Skill update
 */
export type SkillUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Skill
   */
  select?: Prisma.SkillSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Skill
   */
  omit?: Prisma.SkillOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SkillInclude<ExtArgs> | null
  /**
   * The data needed to update a Skill.
   */
  data: Prisma.XOR<Prisma.SkillUpdateInput, Prisma.SkillUncheckedUpdateInput>
  /**
   * Choose, which Skill to update.
   */
  where: Prisma.SkillWhereUniqueInput
}

/**
 * Skill updateMany
 */
export type SkillUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Skills.
   */
  data: Prisma.XOR<Prisma.SkillUpdateManyMutationInput, Prisma.SkillUncheckedUpdateManyInput>
  /**
   * Filter which Skills to update
   */
  where?: Prisma.SkillWhereInput
  /**
   * Limit how many Skills to update.
   */
  limit?: number
}

/**
 * Skill updateManyAndReturn
 */
export type SkillUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Skill
   */
  select?: Prisma.SkillSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Skill
   */
  omit?: Prisma.SkillOmit<ExtArgs> | null
  /**
   * The data used to update Skills.
   */
  data: Prisma.XOR<Prisma.SkillUpdateManyMutationInput, Prisma.SkillUncheckedUpdateManyInput>
  /**
   * Filter which Skills to update
   */
  where?: Prisma.SkillWhereInput
  /**
   * Limit how many Skills to update.
   */
  limit?: number
}

/**
 * Skill upsert
 */
export type SkillUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Skill
   */
  select?: Prisma.SkillSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Skill
   */
  omit?: Prisma.SkillOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SkillInclude<ExtArgs> | null
  /**
   * The filter to search for the Skill to update in case it exists.
   */
  where: Prisma.SkillWhereUniqueInput
  /**
   * In case the Skill found by the `where` argument doesn't exist, create a new Skill with this data.
   */
  create: Prisma.XOR<Prisma.SkillCreateInput, Prisma.SkillUncheckedCreateInput>
  /**
   * In case the Skill was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.SkillUpdateInput, Prisma.SkillUncheckedUpdateInput>
}

/**
 * Skill delete
 */
export type SkillDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Skill
   */
  select?: Prisma.SkillSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Skill
   */
  omit?: Prisma.SkillOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SkillInclude<ExtArgs> | null
  /**
   * Filter which Skill to delete.
   */
  where: Prisma.SkillWhereUniqueInput
}

/**
 * Skill deleteMany
 */
export type SkillDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Skills to delete
   */
  where?: Prisma.SkillWhereInput
  /**
   * Limit how many Skills to delete.
   */
  limit?: number
}

/**
 * Skill.favorites
 */
export type Skill$favoritesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Favorite
   */
  select?: Prisma.FavoriteSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Favorite
   */
  omit?: Prisma.FavoriteOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FavoriteInclude<ExtArgs> | null
  where?: Prisma.FavoriteWhereInput
  orderBy?: Prisma.FavoriteOrderByWithRelationInput | Prisma.FavoriteOrderByWithRelationInput[]
  cursor?: Prisma.FavoriteWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.FavoriteScalarFieldEnum | Prisma.FavoriteScalarFieldEnum[]
}

/**
 * Skill.history
 */
export type Skill$historyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the History
   */
  select?: Prisma.HistorySelect<ExtArgs> | null
  /**
   * Omit specific fields from the History
   */
  omit?: Prisma.HistoryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HistoryInclude<ExtArgs> | null
  where?: Prisma.HistoryWhereInput
  orderBy?: Prisma.HistoryOrderByWithRelationInput | Prisma.HistoryOrderByWithRelationInput[]
  cursor?: Prisma.HistoryWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.HistoryScalarFieldEnum | Prisma.HistoryScalarFieldEnum[]
}

/**
 * Skill.workflowSteps
 */
export type Skill$workflowStepsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkflowStep
   */
  select?: Prisma.WorkflowStepSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkflowStep
   */
  omit?: Prisma.WorkflowStepOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkflowStepInclude<ExtArgs> | null
  where?: Prisma.WorkflowStepWhereInput
  orderBy?: Prisma.WorkflowStepOrderByWithRelationInput | Prisma.WorkflowStepOrderByWithRelationInput[]
  cursor?: Prisma.WorkflowStepWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.WorkflowStepScalarFieldEnum | Prisma.WorkflowStepScalarFieldEnum[]
}

/**
 * Skill without action
 */
export type SkillDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Skill
   */
  select?: Prisma.SkillSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Skill
   */
  omit?: Prisma.SkillOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SkillInclude<ExtArgs> | null
}
