
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Workflow` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Workflow
 * 
 */
export type WorkflowModel = runtime.Types.Result.DefaultSelection<Prisma.$WorkflowPayload>

export type AggregateWorkflow = {
  _count: WorkflowCountAggregateOutputType | null
  _avg: WorkflowAvgAggregateOutputType | null
  _sum: WorkflowSumAggregateOutputType | null
  _min: WorkflowMinAggregateOutputType | null
  _max: WorkflowMaxAggregateOutputType | null
}

export type WorkflowAvgAggregateOutputType = {
  runCount: number | null
}

export type WorkflowSumAggregateOutputType = {
  runCount: number | null
}

export type WorkflowMinAggregateOutputType = {
  id: string | null
  name: string | null
  description: string | null
  isBuiltIn: boolean | null
  runCount: number | null
  lastRunAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type WorkflowMaxAggregateOutputType = {
  id: string | null
  name: string | null
  description: string | null
  isBuiltIn: boolean | null
  runCount: number | null
  lastRunAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type WorkflowCountAggregateOutputType = {
  id: number
  name: number
  description: number
  isBuiltIn: number
  runCount: number
  lastRunAt: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type WorkflowAvgAggregateInputType = {
  runCount?: true
}

export type WorkflowSumAggregateInputType = {
  runCount?: true
}

export type WorkflowMinAggregateInputType = {
  id?: true
  name?: true
  description?: true
  isBuiltIn?: true
  runCount?: true
  lastRunAt?: true
  createdAt?: true
  updatedAt?: true
}

export type WorkflowMaxAggregateInputType = {
  id?: true
  name?: true
  description?: true
  isBuiltIn?: true
  runCount?: true
  lastRunAt?: true
  createdAt?: true
  updatedAt?: true
}

export type WorkflowCountAggregateInputType = {
  id?: true
  name?: true
  description?: true
  isBuiltIn?: true
  runCount?: true
  lastRunAt?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type WorkflowAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Workflow to aggregate.
   */
  where?: Prisma.WorkflowWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Workflows to fetch.
   */
  orderBy?: Prisma.WorkflowOrderByWithRelationInput | Prisma.WorkflowOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.WorkflowWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Workflows from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Workflows.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Workflows
  **/
  _count?: true | WorkflowCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: WorkflowAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: WorkflowSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: WorkflowMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: WorkflowMaxAggregateInputType
}

export type GetWorkflowAggregateType<T extends WorkflowAggregateArgs> = {
      [P in keyof T & keyof AggregateWorkflow]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateWorkflow[P]>
    : Prisma.GetScalarType<T[P], AggregateWorkflow[P]>
}




export type WorkflowGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.WorkflowWhereInput
  orderBy?: Prisma.WorkflowOrderByWithAggregationInput | Prisma.WorkflowOrderByWithAggregationInput[]
  by: Prisma.WorkflowScalarFieldEnum[] | Prisma.WorkflowScalarFieldEnum
  having?: Prisma.WorkflowScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: WorkflowCountAggregateInputType | true
  _avg?: WorkflowAvgAggregateInputType
  _sum?: WorkflowSumAggregateInputType
  _min?: WorkflowMinAggregateInputType
  _max?: WorkflowMaxAggregateInputType
}

export type WorkflowGroupByOutputType = {
  id: string
  name: string
  description: string | null
  isBuiltIn: boolean
  runCount: number
  lastRunAt: Date | null
  createdAt: Date
  updatedAt: Date
  _count: WorkflowCountAggregateOutputType | null
  _avg: WorkflowAvgAggregateOutputType | null
  _sum: WorkflowSumAggregateOutputType | null
  _min: WorkflowMinAggregateOutputType | null
  _max: WorkflowMaxAggregateOutputType | null
}

export type GetWorkflowGroupByPayload<T extends WorkflowGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<WorkflowGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof WorkflowGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], WorkflowGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], WorkflowGroupByOutputType[P]>
      }
    >
  >



export type WorkflowWhereInput = {
  AND?: Prisma.WorkflowWhereInput | Prisma.WorkflowWhereInput[]
  OR?: Prisma.WorkflowWhereInput[]
  NOT?: Prisma.WorkflowWhereInput | Prisma.WorkflowWhereInput[]
  id?: Prisma.StringFilter<"Workflow"> | string
  name?: Prisma.StringFilter<"Workflow"> | string
  description?: Prisma.StringNullableFilter<"Workflow"> | string | null
  isBuiltIn?: Prisma.BoolFilter<"Workflow"> | boolean
  runCount?: Prisma.IntFilter<"Workflow"> | number
  lastRunAt?: Prisma.DateTimeNullableFilter<"Workflow"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"Workflow"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Workflow"> | Date | string
  steps?: Prisma.WorkflowStepListRelationFilter
}

export type WorkflowOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  isBuiltIn?: Prisma.SortOrder
  runCount?: Prisma.SortOrder
  lastRunAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  steps?: Prisma.WorkflowStepOrderByRelationAggregateInput
}

export type WorkflowWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.WorkflowWhereInput | Prisma.WorkflowWhereInput[]
  OR?: Prisma.WorkflowWhereInput[]
  NOT?: Prisma.WorkflowWhereInput | Prisma.WorkflowWhereInput[]
  name?: Prisma.StringFilter<"Workflow"> | string
  description?: Prisma.StringNullableFilter<"Workflow"> | string | null
  isBuiltIn?: Prisma.BoolFilter<"Workflow"> | boolean
  runCount?: Prisma.IntFilter<"Workflow"> | number
  lastRunAt?: Prisma.DateTimeNullableFilter<"Workflow"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"Workflow"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Workflow"> | Date | string
  steps?: Prisma.WorkflowStepListRelationFilter
}, "id">

export type WorkflowOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  isBuiltIn?: Prisma.SortOrder
  runCount?: Prisma.SortOrder
  lastRunAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.WorkflowCountOrderByAggregateInput
  _avg?: Prisma.WorkflowAvgOrderByAggregateInput
  _max?: Prisma.WorkflowMaxOrderByAggregateInput
  _min?: Prisma.WorkflowMinOrderByAggregateInput
  _sum?: Prisma.WorkflowSumOrderByAggregateInput
}

export type WorkflowScalarWhereWithAggregatesInput = {
  AND?: Prisma.WorkflowScalarWhereWithAggregatesInput | Prisma.WorkflowScalarWhereWithAggregatesInput[]
  OR?: Prisma.WorkflowScalarWhereWithAggregatesInput[]
  NOT?: Prisma.WorkflowScalarWhereWithAggregatesInput | Prisma.WorkflowScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Workflow"> | string
  name?: Prisma.StringWithAggregatesFilter<"Workflow"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"Workflow"> | string | null
  isBuiltIn?: Prisma.BoolWithAggregatesFilter<"Workflow"> | boolean
  runCount?: Prisma.IntWithAggregatesFilter<"Workflow"> | number
  lastRunAt?: Prisma.DateTimeNullableWithAggregatesFilter<"Workflow"> | Date | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Workflow"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Workflow"> | Date | string
}

export type WorkflowCreateInput = {
  id?: string
  name: string
  description?: string | null
  isBuiltIn?: boolean
  runCount?: number
  lastRunAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  steps?: Prisma.WorkflowStepCreateNestedManyWithoutWorkflowInput
}

export type WorkflowUncheckedCreateInput = {
  id?: string
  name: string
  description?: string | null
  isBuiltIn?: boolean
  runCount?: number
  lastRunAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  steps?: Prisma.WorkflowStepUncheckedCreateNestedManyWithoutWorkflowInput
}

export type WorkflowUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isBuiltIn?: Prisma.BoolFieldUpdateOperationsInput | boolean
  runCount?: Prisma.IntFieldUpdateOperationsInput | number
  lastRunAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  steps?: Prisma.WorkflowStepUpdateManyWithoutWorkflowNestedInput
}

export type WorkflowUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isBuiltIn?: Prisma.BoolFieldUpdateOperationsInput | boolean
  runCount?: Prisma.IntFieldUpdateOperationsInput | number
  lastRunAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  steps?: Prisma.WorkflowStepUncheckedUpdateManyWithoutWorkflowNestedInput
}

export type WorkflowCreateManyInput = {
  id?: string
  name: string
  description?: string | null
  isBuiltIn?: boolean
  runCount?: number
  lastRunAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type WorkflowUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isBuiltIn?: Prisma.BoolFieldUpdateOperationsInput | boolean
  runCount?: Prisma.IntFieldUpdateOperationsInput | number
  lastRunAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type WorkflowUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isBuiltIn?: Prisma.BoolFieldUpdateOperationsInput | boolean
  runCount?: Prisma.IntFieldUpdateOperationsInput | number
  lastRunAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type WorkflowCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  isBuiltIn?: Prisma.SortOrder
  runCount?: Prisma.SortOrder
  lastRunAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type WorkflowAvgOrderByAggregateInput = {
  runCount?: Prisma.SortOrder
}

export type WorkflowMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  isBuiltIn?: Prisma.SortOrder
  runCount?: Prisma.SortOrder
  lastRunAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type WorkflowMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  isBuiltIn?: Prisma.SortOrder
  runCount?: Prisma.SortOrder
  lastRunAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type WorkflowSumOrderByAggregateInput = {
  runCount?: Prisma.SortOrder
}

export type WorkflowScalarRelationFilter = {
  is?: Prisma.WorkflowWhereInput
  isNot?: Prisma.WorkflowWhereInput
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}

export type WorkflowCreateNestedOneWithoutStepsInput = {
  create?: Prisma.XOR<Prisma.WorkflowCreateWithoutStepsInput, Prisma.WorkflowUncheckedCreateWithoutStepsInput>
  connectOrCreate?: Prisma.WorkflowCreateOrConnectWithoutStepsInput
  connect?: Prisma.WorkflowWhereUniqueInput
}

export type WorkflowUpdateOneRequiredWithoutStepsNestedInput = {
  create?: Prisma.XOR<Prisma.WorkflowCreateWithoutStepsInput, Prisma.WorkflowUncheckedCreateWithoutStepsInput>
  connectOrCreate?: Prisma.WorkflowCreateOrConnectWithoutStepsInput
  upsert?: Prisma.WorkflowUpsertWithoutStepsInput
  connect?: Prisma.WorkflowWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.WorkflowUpdateToOneWithWhereWithoutStepsInput, Prisma.WorkflowUpdateWithoutStepsInput>, Prisma.WorkflowUncheckedUpdateWithoutStepsInput>
}

export type WorkflowCreateWithoutStepsInput = {
  id?: string
  name: string
  description?: string | null
  isBuiltIn?: boolean
  runCount?: number
  lastRunAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type WorkflowUncheckedCreateWithoutStepsInput = {
  id?: string
  name: string
  description?: string | null
  isBuiltIn?: boolean
  runCount?: number
  lastRunAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type WorkflowCreateOrConnectWithoutStepsInput = {
  where: Prisma.WorkflowWhereUniqueInput
  create: Prisma.XOR<Prisma.WorkflowCreateWithoutStepsInput, Prisma.WorkflowUncheckedCreateWithoutStepsInput>
}

export type WorkflowUpsertWithoutStepsInput = {
  update: Prisma.XOR<Prisma.WorkflowUpdateWithoutStepsInput, Prisma.WorkflowUncheckedUpdateWithoutStepsInput>
  create: Prisma.XOR<Prisma.WorkflowCreateWithoutStepsInput, Prisma.WorkflowUncheckedCreateWithoutStepsInput>
  where?: Prisma.WorkflowWhereInput
}

export type WorkflowUpdateToOneWithWhereWithoutStepsInput = {
  where?: Prisma.WorkflowWhereInput
  data: Prisma.XOR<Prisma.WorkflowUpdateWithoutStepsInput, Prisma.WorkflowUncheckedUpdateWithoutStepsInput>
}

export type WorkflowUpdateWithoutStepsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isBuiltIn?: Prisma.BoolFieldUpdateOperationsInput | boolean
  runCount?: Prisma.IntFieldUpdateOperationsInput | number
  lastRunAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type WorkflowUncheckedUpdateWithoutStepsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  isBuiltIn?: Prisma.BoolFieldUpdateOperationsInput | boolean
  runCount?: Prisma.IntFieldUpdateOperationsInput | number
  lastRunAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type WorkflowCountOutputType
 */

export type WorkflowCountOutputType = {
  steps: number
}

export type WorkflowCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  steps?: boolean | WorkflowCountOutputTypeCountStepsArgs
}

/**
 * WorkflowCountOutputType without action
 */
export type WorkflowCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkflowCountOutputType
   */
  select?: Prisma.WorkflowCountOutputTypeSelect<ExtArgs> | null
}

/**
 * WorkflowCountOutputType without action
 */
export type WorkflowCountOutputTypeCountStepsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.WorkflowStepWhereInput
}


export type WorkflowSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  description?: boolean
  isBuiltIn?: boolean
  runCount?: boolean
  lastRunAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  steps?: boolean | Prisma.Workflow$stepsArgs<ExtArgs>
  _count?: boolean | Prisma.WorkflowCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["workflow"]>

export type WorkflowSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  description?: boolean
  isBuiltIn?: boolean
  runCount?: boolean
  lastRunAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["workflow"]>

export type WorkflowSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  description?: boolean
  isBuiltIn?: boolean
  runCount?: boolean
  lastRunAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["workflow"]>

export type WorkflowSelectScalar = {
  id?: boolean
  name?: boolean
  description?: boolean
  isBuiltIn?: boolean
  runCount?: boolean
  lastRunAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type WorkflowOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "description" | "isBuiltIn" | "runCount" | "lastRunAt" | "createdAt" | "updatedAt", ExtArgs["result"]["workflow"]>
export type WorkflowInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  steps?: boolean | Prisma.Workflow$stepsArgs<ExtArgs>
  _count?: boolean | Prisma.WorkflowCountOutputTypeDefaultArgs<ExtArgs>
}
export type WorkflowIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type WorkflowIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $WorkflowPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Workflow"
  objects: {
    steps: Prisma.$WorkflowStepPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    description: string | null
    isBuiltIn: boolean
    runCount: number
    lastRunAt: Date | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["workflow"]>
  composites: {}
}

export type WorkflowGetPayload<S extends boolean | null | undefined | WorkflowDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$WorkflowPayload, S>

export type WorkflowCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<WorkflowFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: WorkflowCountAggregateInputType | true
  }

export interface WorkflowDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Workflow'], meta: { name: 'Workflow' } }
  /**
   * Find zero or one Workflow that matches the filter.
   * @param {WorkflowFindUniqueArgs} args - Arguments to find a Workflow
   * @example
   * // Get one Workflow
   * const workflow = await prisma.workflow.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends WorkflowFindUniqueArgs>(args: Prisma.SelectSubset<T, WorkflowFindUniqueArgs<ExtArgs>>): Prisma.Prisma__WorkflowClient<runtime.Types.Result.GetResult<Prisma.$WorkflowPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Workflow that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {WorkflowFindUniqueOrThrowArgs} args - Arguments to find a Workflow
   * @example
   * // Get one Workflow
   * const workflow = await prisma.workflow.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends WorkflowFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, WorkflowFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__WorkflowClient<runtime.Types.Result.GetResult<Prisma.$WorkflowPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Workflow that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkflowFindFirstArgs} args - Arguments to find a Workflow
   * @example
   * // Get one Workflow
   * const workflow = await prisma.workflow.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends WorkflowFindFirstArgs>(args?: Prisma.SelectSubset<T, WorkflowFindFirstArgs<ExtArgs>>): Prisma.Prisma__WorkflowClient<runtime.Types.Result.GetResult<Prisma.$WorkflowPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Workflow that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkflowFindFirstOrThrowArgs} args - Arguments to find a Workflow
   * @example
   * // Get one Workflow
   * const workflow = await prisma.workflow.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends WorkflowFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, WorkflowFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__WorkflowClient<runtime.Types.Result.GetResult<Prisma.$WorkflowPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Workflows that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkflowFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Workflows
   * const workflows = await prisma.workflow.findMany()
   * 
   * // Get first 10 Workflows
   * const workflows = await prisma.workflow.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const workflowWithIdOnly = await prisma.workflow.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends WorkflowFindManyArgs>(args?: Prisma.SelectSubset<T, WorkflowFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WorkflowPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Workflow.
   * @param {WorkflowCreateArgs} args - Arguments to create a Workflow.
   * @example
   * // Create one Workflow
   * const Workflow = await prisma.workflow.create({
   *   data: {
   *     // ... data to create a Workflow
   *   }
   * })
   * 
   */
  create<T extends WorkflowCreateArgs>(args: Prisma.SelectSubset<T, WorkflowCreateArgs<ExtArgs>>): Prisma.Prisma__WorkflowClient<runtime.Types.Result.GetResult<Prisma.$WorkflowPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Workflows.
   * @param {WorkflowCreateManyArgs} args - Arguments to create many Workflows.
   * @example
   * // Create many Workflows
   * const workflow = await prisma.workflow.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends WorkflowCreateManyArgs>(args?: Prisma.SelectSubset<T, WorkflowCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Workflows and returns the data saved in the database.
   * @param {WorkflowCreateManyAndReturnArgs} args - Arguments to create many Workflows.
   * @example
   * // Create many Workflows
   * const workflow = await prisma.workflow.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Workflows and only return the `id`
   * const workflowWithIdOnly = await prisma.workflow.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends WorkflowCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, WorkflowCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WorkflowPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Workflow.
   * @param {WorkflowDeleteArgs} args - Arguments to delete one Workflow.
   * @example
   * // Delete one Workflow
   * const Workflow = await prisma.workflow.delete({
   *   where: {
   *     // ... filter to delete one Workflow
   *   }
   * })
   * 
   */
  delete<T extends WorkflowDeleteArgs>(args: Prisma.SelectSubset<T, WorkflowDeleteArgs<ExtArgs>>): Prisma.Prisma__WorkflowClient<runtime.Types.Result.GetResult<Prisma.$WorkflowPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Workflow.
   * @param {WorkflowUpdateArgs} args - Arguments to update one Workflow.
   * @example
   * // Update one Workflow
   * const workflow = await prisma.workflow.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends WorkflowUpdateArgs>(args: Prisma.SelectSubset<T, WorkflowUpdateArgs<ExtArgs>>): Prisma.Prisma__WorkflowClient<runtime.Types.Result.GetResult<Prisma.$WorkflowPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Workflows.
   * @param {WorkflowDeleteManyArgs} args - Arguments to filter Workflows to delete.
   * @example
   * // Delete a few Workflows
   * const { count } = await prisma.workflow.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends WorkflowDeleteManyArgs>(args?: Prisma.SelectSubset<T, WorkflowDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Workflows.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkflowUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Workflows
   * const workflow = await prisma.workflow.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends WorkflowUpdateManyArgs>(args: Prisma.SelectSubset<T, WorkflowUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Workflows and returns the data updated in the database.
   * @param {WorkflowUpdateManyAndReturnArgs} args - Arguments to update many Workflows.
   * @example
   * // Update many Workflows
   * const workflow = await prisma.workflow.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Workflows and only return the `id`
   * const workflowWithIdOnly = await prisma.workflow.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends WorkflowUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, WorkflowUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WorkflowPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Workflow.
   * @param {WorkflowUpsertArgs} args - Arguments to update or create a Workflow.
   * @example
   * // Update or create a Workflow
   * const workflow = await prisma.workflow.upsert({
   *   create: {
   *     // ... data to create a Workflow
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Workflow we want to update
   *   }
   * })
   */
  upsert<T extends WorkflowUpsertArgs>(args: Prisma.SelectSubset<T, WorkflowUpsertArgs<ExtArgs>>): Prisma.Prisma__WorkflowClient<runtime.Types.Result.GetResult<Prisma.$WorkflowPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Workflows.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkflowCountArgs} args - Arguments to filter Workflows to count.
   * @example
   * // Count the number of Workflows
   * const count = await prisma.workflow.count({
   *   where: {
   *     // ... the filter for the Workflows we want to count
   *   }
   * })
  **/
  count<T extends WorkflowCountArgs>(
    args?: Prisma.Subset<T, WorkflowCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], WorkflowCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Workflow.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkflowAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends WorkflowAggregateArgs>(args: Prisma.Subset<T, WorkflowAggregateArgs>): Prisma.PrismaPromise<GetWorkflowAggregateType<T>>

  /**
   * Group by Workflow.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkflowGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends WorkflowGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: WorkflowGroupByArgs['orderBy'] }
      : { orderBy?: WorkflowGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, WorkflowGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetWorkflowGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Workflow model
 */
readonly fields: WorkflowFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Workflow.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__WorkflowClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  steps<T extends Prisma.Workflow$stepsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Workflow$stepsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WorkflowStepPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Workflow model
 */
export interface WorkflowFieldRefs {
  readonly id: Prisma.FieldRef<"Workflow", 'String'>
  readonly name: Prisma.FieldRef<"Workflow", 'String'>
  readonly description: Prisma.FieldRef<"Workflow", 'String'>
  readonly isBuiltIn: Prisma.FieldRef<"Workflow", 'Boolean'>
  readonly runCount: Prisma.FieldRef<"Workflow", 'Int'>
  readonly lastRunAt: Prisma.FieldRef<"Workflow", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"Workflow", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Workflow", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Workflow findUnique
 */
export type WorkflowFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Workflow
   */
  select?: Prisma.WorkflowSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Workflow
   */
  omit?: Prisma.WorkflowOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkflowInclude<ExtArgs> | null
  /**
   * Filter, which Workflow to fetch.
   */
  where: Prisma.WorkflowWhereUniqueInput
}

/**
 * Workflow findUniqueOrThrow
 */
export type WorkflowFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Workflow
   */
  select?: Prisma.WorkflowSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Workflow
   */
  omit?: Prisma.WorkflowOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkflowInclude<ExtArgs> | null
  /**
   * Filter, which Workflow to fetch.
   */
  where: Prisma.WorkflowWhereUniqueInput
}

/**
 * Workflow findFirst
 */
export type WorkflowFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Workflow
   */
  select?: Prisma.WorkflowSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Workflow
   */
  omit?: Prisma.WorkflowOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkflowInclude<ExtArgs> | null
  /**
   * Filter, which Workflow to fetch.
   */
  where?: Prisma.WorkflowWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Workflows to fetch.
   */
  orderBy?: Prisma.WorkflowOrderByWithRelationInput | Prisma.WorkflowOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Workflows.
   */
  cursor?: Prisma.WorkflowWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Workflows from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Workflows.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Workflows.
   */
  distinct?: Prisma.WorkflowScalarFieldEnum | Prisma.WorkflowScalarFieldEnum[]
}

/**
 * Workflow findFirstOrThrow
 */
export type WorkflowFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Workflow
   */
  select?: Prisma.WorkflowSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Workflow
   */
  omit?: Prisma.WorkflowOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkflowInclude<ExtArgs> | null
  /**
   * Filter, which Workflow to fetch.
   */
  where?: Prisma.WorkflowWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Workflows to fetch.
   */
  orderBy?: Prisma.WorkflowOrderByWithRelationInput | Prisma.WorkflowOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Workflows.
   */
  cursor?: Prisma.WorkflowWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Workflows from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Workflows.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Workflows.
   */
  distinct?: Prisma.WorkflowScalarFieldEnum | Prisma.WorkflowScalarFieldEnum[]
}

/**
 * Workflow findMany
 */
export type WorkflowFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Workflow
   */
  select?: Prisma.WorkflowSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Workflow
   */
  omit?: Prisma.WorkflowOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkflowInclude<ExtArgs> | null
  /**
   * Filter, which Workflows to fetch.
   */
  where?: Prisma.WorkflowWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Workflows to fetch.
   */
  orderBy?: Prisma.WorkflowOrderByWithRelationInput | Prisma.WorkflowOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Workflows.
   */
  cursor?: Prisma.WorkflowWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Workflows from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Workflows.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Workflows.
   */
  distinct?: Prisma.WorkflowScalarFieldEnum | Prisma.WorkflowScalarFieldEnum[]
}

/**
 * Workflow create
 */
export type WorkflowCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Workflow
   */
  select?: Prisma.WorkflowSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Workflow
   */
  omit?: Prisma.WorkflowOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkflowInclude<ExtArgs> | null
  /**
   * The data needed to create a Workflow.
   */
  data: Prisma.XOR<Prisma.WorkflowCreateInput, Prisma.WorkflowUncheckedCreateInput>
}

/**
 * Workflow createMany
 */
export type WorkflowCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Workflows.
   */
  data: Prisma.WorkflowCreateManyInput | Prisma.WorkflowCreateManyInput[]
}

/**
 * Workflow createManyAndReturn
 */
export type WorkflowCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Workflow
   */
  select?: Prisma.WorkflowSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Workflow
   */
  omit?: Prisma.WorkflowOmit<ExtArgs> | null
  /**
   * The data used to create many Workflows.
   */
  data: Prisma.WorkflowCreateManyInput | Prisma.WorkflowCreateManyInput[]
}

/**
 * Workflow update
 */
export type WorkflowUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Workflow
   */
  select?: Prisma.WorkflowSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Workflow
   */
  omit?: Prisma.WorkflowOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkflowInclude<ExtArgs> | null
  /**
   * The data needed to update a Workflow.
   */
  data: Prisma.XOR<Prisma.WorkflowUpdateInput, Prisma.WorkflowUncheckedUpdateInput>
  /**
   * Choose, which Workflow to update.
   */
  where: Prisma.WorkflowWhereUniqueInput
}

/**
 * Workflow updateMany
 */
export type WorkflowUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Workflows.
   */
  data: Prisma.XOR<Prisma.WorkflowUpdateManyMutationInput, Prisma.WorkflowUncheckedUpdateManyInput>
  /**
   * Filter which Workflows to update
   */
  where?: Prisma.WorkflowWhereInput
  /**
   * Limit how many Workflows to update.
   */
  limit?: number
}

/**
 * Workflow updateManyAndReturn
 */
export type WorkflowUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Workflow
   */
  select?: Prisma.WorkflowSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Workflow
   */
  omit?: Prisma.WorkflowOmit<ExtArgs> | null
  /**
   * The data used to update Workflows.
   */
  data: Prisma.XOR<Prisma.WorkflowUpdateManyMutationInput, Prisma.WorkflowUncheckedUpdateManyInput>
  /**
   * Filter which Workflows to update
   */
  where?: Prisma.WorkflowWhereInput
  /**
   * Limit how many Workflows to update.
   */
  limit?: number
}

/**
 * Workflow upsert
 */
export type WorkflowUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Workflow
   */
  select?: Prisma.WorkflowSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Workflow
   */
  omit?: Prisma.WorkflowOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkflowInclude<ExtArgs> | null
  /**
   * The filter to search for the Workflow to update in case it exists.
   */
  where: Prisma.WorkflowWhereUniqueInput
  /**
   * In case the Workflow found by the `where` argument doesn't exist, create a new Workflow with this data.
   */
  create: Prisma.XOR<Prisma.WorkflowCreateInput, Prisma.WorkflowUncheckedCreateInput>
  /**
   * In case the Workflow was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.WorkflowUpdateInput, Prisma.WorkflowUncheckedUpdateInput>
}

/**
 * Workflow delete
 */
export type WorkflowDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Workflow
   */
  select?: Prisma.WorkflowSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Workflow
   */
  omit?: Prisma.WorkflowOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkflowInclude<ExtArgs> | null
  /**
   * Filter which Workflow to delete.
   */
  where: Prisma.WorkflowWhereUniqueInput
}

/**
 * Workflow deleteMany
 */
export type WorkflowDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Workflows to delete
   */
  where?: Prisma.WorkflowWhereInput
  /**
   * Limit how many Workflows to delete.
   */
  limit?: number
}

/**
 * Workflow.steps
 */
export type Workflow$stepsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkflowStep
   */
  select?: Prisma.WorkflowStepSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkflowStep
   */
  omit?: Prisma.WorkflowStepOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkflowStepInclude<ExtArgs> | null
  where?: Prisma.WorkflowStepWhereInput
  orderBy?: Prisma.WorkflowStepOrderByWithRelationInput | Prisma.WorkflowStepOrderByWithRelationInput[]
  cursor?: Prisma.WorkflowStepWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.WorkflowStepScalarFieldEnum | Prisma.WorkflowStepScalarFieldEnum[]
}

/**
 * Workflow without action
 */
export type WorkflowDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Workflow
   */
  select?: Prisma.WorkflowSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Workflow
   */
  omit?: Prisma.WorkflowOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkflowInclude<ExtArgs> | null
}
