
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `WorkflowStep` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model WorkflowStep
 * 
 */
export type WorkflowStepModel = runtime.Types.Result.DefaultSelection<Prisma.$WorkflowStepPayload>

export type AggregateWorkflowStep = {
  _count: WorkflowStepCountAggregateOutputType | null
  _avg: WorkflowStepAvgAggregateOutputType | null
  _sum: WorkflowStepSumAggregateOutputType | null
  _min: WorkflowStepMinAggregateOutputType | null
  _max: WorkflowStepMaxAggregateOutputType | null
}

export type WorkflowStepAvgAggregateOutputType = {
  orderIndex: number | null
}

export type WorkflowStepSumAggregateOutputType = {
  orderIndex: number | null
}

export type WorkflowStepMinAggregateOutputType = {
  id: string | null
  workflowId: string | null
  skillId: string | null
  orderIndex: number | null
  config: string | null
  label: string | null
}

export type WorkflowStepMaxAggregateOutputType = {
  id: string | null
  workflowId: string | null
  skillId: string | null
  orderIndex: number | null
  config: string | null
  label: string | null
}

export type WorkflowStepCountAggregateOutputType = {
  id: number
  workflowId: number
  skillId: number
  orderIndex: number
  config: number
  label: number
  _all: number
}


export type WorkflowStepAvgAggregateInputType = {
  orderIndex?: true
}

export type WorkflowStepSumAggregateInputType = {
  orderIndex?: true
}

export type WorkflowStepMinAggregateInputType = {
  id?: true
  workflowId?: true
  skillId?: true
  orderIndex?: true
  config?: true
  label?: true
}

export type WorkflowStepMaxAggregateInputType = {
  id?: true
  workflowId?: true
  skillId?: true
  orderIndex?: true
  config?: true
  label?: true
}

export type WorkflowStepCountAggregateInputType = {
  id?: true
  workflowId?: true
  skillId?: true
  orderIndex?: true
  config?: true
  label?: true
  _all?: true
}

export type WorkflowStepAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which WorkflowStep to aggregate.
   */
  where?: Prisma.WorkflowStepWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WorkflowSteps to fetch.
   */
  orderBy?: Prisma.WorkflowStepOrderByWithRelationInput | Prisma.WorkflowStepOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.WorkflowStepWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WorkflowSteps from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WorkflowSteps.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned WorkflowSteps
  **/
  _count?: true | WorkflowStepCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: WorkflowStepAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: WorkflowStepSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: WorkflowStepMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: WorkflowStepMaxAggregateInputType
}

export type GetWorkflowStepAggregateType<T extends WorkflowStepAggregateArgs> = {
      [P in keyof T & keyof AggregateWorkflowStep]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateWorkflowStep[P]>
    : Prisma.GetScalarType<T[P], AggregateWorkflowStep[P]>
}




export type WorkflowStepGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.WorkflowStepWhereInput
  orderBy?: Prisma.WorkflowStepOrderByWithAggregationInput | Prisma.WorkflowStepOrderByWithAggregationInput[]
  by: Prisma.WorkflowStepScalarFieldEnum[] | Prisma.WorkflowStepScalarFieldEnum
  having?: Prisma.WorkflowStepScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: WorkflowStepCountAggregateInputType | true
  _avg?: WorkflowStepAvgAggregateInputType
  _sum?: WorkflowStepSumAggregateInputType
  _min?: WorkflowStepMinAggregateInputType
  _max?: WorkflowStepMaxAggregateInputType
}

export type WorkflowStepGroupByOutputType = {
  id: string
  workflowId: string
  skillId: string
  orderIndex: number
  config: string | null
  label: string | null
  _count: WorkflowStepCountAggregateOutputType | null
  _avg: WorkflowStepAvgAggregateOutputType | null
  _sum: WorkflowStepSumAggregateOutputType | null
  _min: WorkflowStepMinAggregateOutputType | null
  _max: WorkflowStepMaxAggregateOutputType | null
}

export type GetWorkflowStepGroupByPayload<T extends WorkflowStepGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<WorkflowStepGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof WorkflowStepGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], WorkflowStepGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], WorkflowStepGroupByOutputType[P]>
      }
    >
  >



export type WorkflowStepWhereInput = {
  AND?: Prisma.WorkflowStepWhereInput | Prisma.WorkflowStepWhereInput[]
  OR?: Prisma.WorkflowStepWhereInput[]
  NOT?: Prisma.WorkflowStepWhereInput | Prisma.WorkflowStepWhereInput[]
  id?: Prisma.StringFilter<"WorkflowStep"> | string
  workflowId?: Prisma.StringFilter<"WorkflowStep"> | string
  skillId?: Prisma.StringFilter<"WorkflowStep"> | string
  orderIndex?: Prisma.IntFilter<"WorkflowStep"> | number
  config?: Prisma.StringNullableFilter<"WorkflowStep"> | string | null
  label?: Prisma.StringNullableFilter<"WorkflowStep"> | string | null
  workflow?: Prisma.XOR<Prisma.WorkflowScalarRelationFilter, Prisma.WorkflowWhereInput>
  skill?: Prisma.XOR<Prisma.SkillScalarRelationFilter, Prisma.SkillWhereInput>
}

export type WorkflowStepOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  workflowId?: Prisma.SortOrder
  skillId?: Prisma.SortOrder
  orderIndex?: Prisma.SortOrder
  config?: Prisma.SortOrderInput | Prisma.SortOrder
  label?: Prisma.SortOrderInput | Prisma.SortOrder
  workflow?: Prisma.WorkflowOrderByWithRelationInput
  skill?: Prisma.SkillOrderByWithRelationInput
}

export type WorkflowStepWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.WorkflowStepWhereInput | Prisma.WorkflowStepWhereInput[]
  OR?: Prisma.WorkflowStepWhereInput[]
  NOT?: Prisma.WorkflowStepWhereInput | Prisma.WorkflowStepWhereInput[]
  workflowId?: Prisma.StringFilter<"WorkflowStep"> | string
  skillId?: Prisma.StringFilter<"WorkflowStep"> | string
  orderIndex?: Prisma.IntFilter<"WorkflowStep"> | number
  config?: Prisma.StringNullableFilter<"WorkflowStep"> | string | null
  label?: Prisma.StringNullableFilter<"WorkflowStep"> | string | null
  workflow?: Prisma.XOR<Prisma.WorkflowScalarRelationFilter, Prisma.WorkflowWhereInput>
  skill?: Prisma.XOR<Prisma.SkillScalarRelationFilter, Prisma.SkillWhereInput>
}, "id">

export type WorkflowStepOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  workflowId?: Prisma.SortOrder
  skillId?: Prisma.SortOrder
  orderIndex?: Prisma.SortOrder
  config?: Prisma.SortOrderInput | Prisma.SortOrder
  label?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.WorkflowStepCountOrderByAggregateInput
  _avg?: Prisma.WorkflowStepAvgOrderByAggregateInput
  _max?: Prisma.WorkflowStepMaxOrderByAggregateInput
  _min?: Prisma.WorkflowStepMinOrderByAggregateInput
  _sum?: Prisma.WorkflowStepSumOrderByAggregateInput
}

export type WorkflowStepScalarWhereWithAggregatesInput = {
  AND?: Prisma.WorkflowStepScalarWhereWithAggregatesInput | Prisma.WorkflowStepScalarWhereWithAggregatesInput[]
  OR?: Prisma.WorkflowStepScalarWhereWithAggregatesInput[]
  NOT?: Prisma.WorkflowStepScalarWhereWithAggregatesInput | Prisma.WorkflowStepScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"WorkflowStep"> | string
  workflowId?: Prisma.StringWithAggregatesFilter<"WorkflowStep"> | string
  skillId?: Prisma.StringWithAggregatesFilter<"WorkflowStep"> | string
  orderIndex?: Prisma.IntWithAggregatesFilter<"WorkflowStep"> | number
  config?: Prisma.StringNullableWithAggregatesFilter<"WorkflowStep"> | string | null
  label?: Prisma.StringNullableWithAggregatesFilter<"WorkflowStep"> | string | null
}

export type WorkflowStepCreateInput = {
  id?: string
  orderIndex: number
  config?: string | null
  label?: string | null
  workflow: Prisma.WorkflowCreateNestedOneWithoutStepsInput
  skill: Prisma.SkillCreateNestedOneWithoutWorkflowStepsInput
}

export type WorkflowStepUncheckedCreateInput = {
  id?: string
  workflowId: string
  skillId: string
  orderIndex: number
  config?: string | null
  label?: string | null
}

export type WorkflowStepUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  orderIndex?: Prisma.IntFieldUpdateOperationsInput | number
  config?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  label?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  workflow?: Prisma.WorkflowUpdateOneRequiredWithoutStepsNestedInput
  skill?: Prisma.SkillUpdateOneRequiredWithoutWorkflowStepsNestedInput
}

export type WorkflowStepUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  workflowId?: Prisma.StringFieldUpdateOperationsInput | string
  skillId?: Prisma.StringFieldUpdateOperationsInput | string
  orderIndex?: Prisma.IntFieldUpdateOperationsInput | number
  config?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  label?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type WorkflowStepCreateManyInput = {
  id?: string
  workflowId: string
  skillId: string
  orderIndex: number
  config?: string | null
  label?: string | null
}

export type WorkflowStepUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  orderIndex?: Prisma.IntFieldUpdateOperationsInput | number
  config?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  label?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type WorkflowStepUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  workflowId?: Prisma.StringFieldUpdateOperationsInput | string
  skillId?: Prisma.StringFieldUpdateOperationsInput | string
  orderIndex?: Prisma.IntFieldUpdateOperationsInput | number
  config?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  label?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type WorkflowStepListRelationFilter = {
  every?: Prisma.WorkflowStepWhereInput
  some?: Prisma.WorkflowStepWhereInput
  none?: Prisma.WorkflowStepWhereInput
}

export type WorkflowStepOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type WorkflowStepCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  workflowId?: Prisma.SortOrder
  skillId?: Prisma.SortOrder
  orderIndex?: Prisma.SortOrder
  config?: Prisma.SortOrder
  label?: Prisma.SortOrder
}

export type WorkflowStepAvgOrderByAggregateInput = {
  orderIndex?: Prisma.SortOrder
}

export type WorkflowStepMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  workflowId?: Prisma.SortOrder
  skillId?: Prisma.SortOrder
  orderIndex?: Prisma.SortOrder
  config?: Prisma.SortOrder
  label?: Prisma.SortOrder
}

export type WorkflowStepMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  workflowId?: Prisma.SortOrder
  skillId?: Prisma.SortOrder
  orderIndex?: Prisma.SortOrder
  config?: Prisma.SortOrder
  label?: Prisma.SortOrder
}

export type WorkflowStepSumOrderByAggregateInput = {
  orderIndex?: Prisma.SortOrder
}

export type WorkflowStepCreateNestedManyWithoutSkillInput = {
  create?: Prisma.XOR<Prisma.WorkflowStepCreateWithoutSkillInput, Prisma.WorkflowStepUncheckedCreateWithoutSkillInput> | Prisma.WorkflowStepCreateWithoutSkillInput[] | Prisma.WorkflowStepUncheckedCreateWithoutSkillInput[]
  connectOrCreate?: Prisma.WorkflowStepCreateOrConnectWithoutSkillInput | Prisma.WorkflowStepCreateOrConnectWithoutSkillInput[]
  createMany?: Prisma.WorkflowStepCreateManySkillInputEnvelope
  connect?: Prisma.WorkflowStepWhereUniqueInput | Prisma.WorkflowStepWhereUniqueInput[]
}

export type WorkflowStepUncheckedCreateNestedManyWithoutSkillInput = {
  create?: Prisma.XOR<Prisma.WorkflowStepCreateWithoutSkillInput, Prisma.WorkflowStepUncheckedCreateWithoutSkillInput> | Prisma.WorkflowStepCreateWithoutSkillInput[] | Prisma.WorkflowStepUncheckedCreateWithoutSkillInput[]
  connectOrCreate?: Prisma.WorkflowStepCreateOrConnectWithoutSkillInput | Prisma.WorkflowStepCreateOrConnectWithoutSkillInput[]
  createMany?: Prisma.WorkflowStepCreateManySkillInputEnvelope
  connect?: Prisma.WorkflowStepWhereUniqueInput | Prisma.WorkflowStepWhereUniqueInput[]
}

export type WorkflowStepUpdateManyWithoutSkillNestedInput = {
  create?: Prisma.XOR<Prisma.WorkflowStepCreateWithoutSkillInput, Prisma.WorkflowStepUncheckedCreateWithoutSkillInput> | Prisma.WorkflowStepCreateWithoutSkillInput[] | Prisma.WorkflowStepUncheckedCreateWithoutSkillInput[]
  connectOrCreate?: Prisma.WorkflowStepCreateOrConnectWithoutSkillInput | Prisma.WorkflowStepCreateOrConnectWithoutSkillInput[]
  upsert?: Prisma.WorkflowStepUpsertWithWhereUniqueWithoutSkillInput | Prisma.WorkflowStepUpsertWithWhereUniqueWithoutSkillInput[]
  createMany?: Prisma.WorkflowStepCreateManySkillInputEnvelope
  set?: Prisma.WorkflowStepWhereUniqueInput | Prisma.WorkflowStepWhereUniqueInput[]
  disconnect?: Prisma.WorkflowStepWhereUniqueInput | Prisma.WorkflowStepWhereUniqueInput[]
  delete?: Prisma.WorkflowStepWhereUniqueInput | Prisma.WorkflowStepWhereUniqueInput[]
  connect?: Prisma.WorkflowStepWhereUniqueInput | Prisma.WorkflowStepWhereUniqueInput[]
  update?: Prisma.WorkflowStepUpdateWithWhereUniqueWithoutSkillInput | Prisma.WorkflowStepUpdateWithWhereUniqueWithoutSkillInput[]
  updateMany?: Prisma.WorkflowStepUpdateManyWithWhereWithoutSkillInput | Prisma.WorkflowStepUpdateManyWithWhereWithoutSkillInput[]
  deleteMany?: Prisma.WorkflowStepScalarWhereInput | Prisma.WorkflowStepScalarWhereInput[]
}

export type WorkflowStepUncheckedUpdateManyWithoutSkillNestedInput = {
  create?: Prisma.XOR<Prisma.WorkflowStepCreateWithoutSkillInput, Prisma.WorkflowStepUncheckedCreateWithoutSkillInput> | Prisma.WorkflowStepCreateWithoutSkillInput[] | Prisma.WorkflowStepUncheckedCreateWithoutSkillInput[]
  connectOrCreate?: Prisma.WorkflowStepCreateOrConnectWithoutSkillInput | Prisma.WorkflowStepCreateOrConnectWithoutSkillInput[]
  upsert?: Prisma.WorkflowStepUpsertWithWhereUniqueWithoutSkillInput | Prisma.WorkflowStepUpsertWithWhereUniqueWithoutSkillInput[]
  createMany?: Prisma.WorkflowStepCreateManySkillInputEnvelope
  set?: Prisma.WorkflowStepWhereUniqueInput | Prisma.WorkflowStepWhereUniqueInput[]
  disconnect?: Prisma.WorkflowStepWhereUniqueInput | Prisma.WorkflowStepWhereUniqueInput[]
  delete?: Prisma.WorkflowStepWhereUniqueInput | Prisma.WorkflowStepWhereUniqueInput[]
  connect?: Prisma.WorkflowStepWhereUniqueInput | Prisma.WorkflowStepWhereUniqueInput[]
  update?: Prisma.WorkflowStepUpdateWithWhereUniqueWithoutSkillInput | Prisma.WorkflowStepUpdateWithWhereUniqueWithoutSkillInput[]
  updateMany?: Prisma.WorkflowStepUpdateManyWithWhereWithoutSkillInput | Prisma.WorkflowStepUpdateManyWithWhereWithoutSkillInput[]
  deleteMany?: Prisma.WorkflowStepScalarWhereInput | Prisma.WorkflowStepScalarWhereInput[]
}

export type WorkflowStepCreateNestedManyWithoutWorkflowInput = {
  create?: Prisma.XOR<Prisma.WorkflowStepCreateWithoutWorkflowInput, Prisma.WorkflowStepUncheckedCreateWithoutWorkflowInput> | Prisma.WorkflowStepCreateWithoutWorkflowInput[] | Prisma.WorkflowStepUncheckedCreateWithoutWorkflowInput[]
  connectOrCreate?: Prisma.WorkflowStepCreateOrConnectWithoutWorkflowInput | Prisma.WorkflowStepCreateOrConnectWithoutWorkflowInput[]
  createMany?: Prisma.WorkflowStepCreateManyWorkflowInputEnvelope
  connect?: Prisma.WorkflowStepWhereUniqueInput | Prisma.WorkflowStepWhereUniqueInput[]
}

export type WorkflowStepUncheckedCreateNestedManyWithoutWorkflowInput = {
  create?: Prisma.XOR<Prisma.WorkflowStepCreateWithoutWorkflowInput, Prisma.WorkflowStepUncheckedCreateWithoutWorkflowInput> | Prisma.WorkflowStepCreateWithoutWorkflowInput[] | Prisma.WorkflowStepUncheckedCreateWithoutWorkflowInput[]
  connectOrCreate?: Prisma.WorkflowStepCreateOrConnectWithoutWorkflowInput | Prisma.WorkflowStepCreateOrConnectWithoutWorkflowInput[]
  createMany?: Prisma.WorkflowStepCreateManyWorkflowInputEnvelope
  connect?: Prisma.WorkflowStepWhereUniqueInput | Prisma.WorkflowStepWhereUniqueInput[]
}

export type WorkflowStepUpdateManyWithoutWorkflowNestedInput = {
  create?: Prisma.XOR<Prisma.WorkflowStepCreateWithoutWorkflowInput, Prisma.WorkflowStepUncheckedCreateWithoutWorkflowInput> | Prisma.WorkflowStepCreateWithoutWorkflowInput[] | Prisma.WorkflowStepUncheckedCreateWithoutWorkflowInput[]
  connectOrCreate?: Prisma.WorkflowStepCreateOrConnectWithoutWorkflowInput | Prisma.WorkflowStepCreateOrConnectWithoutWorkflowInput[]
  upsert?: Prisma.WorkflowStepUpsertWithWhereUniqueWithoutWorkflowInput | Prisma.WorkflowStepUpsertWithWhereUniqueWithoutWorkflowInput[]
  createMany?: Prisma.WorkflowStepCreateManyWorkflowInputEnvelope
  set?: Prisma.WorkflowStepWhereUniqueInput | Prisma.WorkflowStepWhereUniqueInput[]
  disconnect?: Prisma.WorkflowStepWhereUniqueInput | Prisma.WorkflowStepWhereUniqueInput[]
  delete?: Prisma.WorkflowStepWhereUniqueInput | Prisma.WorkflowStepWhereUniqueInput[]
  connect?: Prisma.WorkflowStepWhereUniqueInput | Prisma.WorkflowStepWhereUniqueInput[]
  update?: Prisma.WorkflowStepUpdateWithWhereUniqueWithoutWorkflowInput | Prisma.WorkflowStepUpdateWithWhereUniqueWithoutWorkflowInput[]
  updateMany?: Prisma.WorkflowStepUpdateManyWithWhereWithoutWorkflowInput | Prisma.WorkflowStepUpdateManyWithWhereWithoutWorkflowInput[]
  deleteMany?: Prisma.WorkflowStepScalarWhereInput | Prisma.WorkflowStepScalarWhereInput[]
}

export type WorkflowStepUncheckedUpdateManyWithoutWorkflowNestedInput = {
  create?: Prisma.XOR<Prisma.WorkflowStepCreateWithoutWorkflowInput, Prisma.WorkflowStepUncheckedCreateWithoutWorkflowInput> | Prisma.WorkflowStepCreateWithoutWorkflowInput[] | Prisma.WorkflowStepUncheckedCreateWithoutWorkflowInput[]
  connectOrCreate?: Prisma.WorkflowStepCreateOrConnectWithoutWorkflowInput | Prisma.WorkflowStepCreateOrConnectWithoutWorkflowInput[]
  upsert?: Prisma.WorkflowStepUpsertWithWhereUniqueWithoutWorkflowInput | Prisma.WorkflowStepUpsertWithWhereUniqueWithoutWorkflowInput[]
  createMany?: Prisma.WorkflowStepCreateManyWorkflowInputEnvelope
  set?: Prisma.WorkflowStepWhereUniqueInput | Prisma.WorkflowStepWhereUniqueInput[]
  disconnect?: Prisma.WorkflowStepWhereUniqueInput | Prisma.WorkflowStepWhereUniqueInput[]
  delete?: Prisma.WorkflowStepWhereUniqueInput | Prisma.WorkflowStepWhereUniqueInput[]
  connect?: Prisma.WorkflowStepWhereUniqueInput | Prisma.WorkflowStepWhereUniqueInput[]
  update?: Prisma.WorkflowStepUpdateWithWhereUniqueWithoutWorkflowInput | Prisma.WorkflowStepUpdateWithWhereUniqueWithoutWorkflowInput[]
  updateMany?: Prisma.WorkflowStepUpdateManyWithWhereWithoutWorkflowInput | Prisma.WorkflowStepUpdateManyWithWhereWithoutWorkflowInput[]
  deleteMany?: Prisma.WorkflowStepScalarWhereInput | Prisma.WorkflowStepScalarWhereInput[]
}

export type WorkflowStepCreateWithoutSkillInput = {
  id?: string
  orderIndex: number
  config?: string | null
  label?: string | null
  workflow: Prisma.WorkflowCreateNestedOneWithoutStepsInput
}

export type WorkflowStepUncheckedCreateWithoutSkillInput = {
  id?: string
  workflowId: string
  orderIndex: number
  config?: string | null
  label?: string | null
}

export type WorkflowStepCreateOrConnectWithoutSkillInput = {
  where: Prisma.WorkflowStepWhereUniqueInput
  create: Prisma.XOR<Prisma.WorkflowStepCreateWithoutSkillInput, Prisma.WorkflowStepUncheckedCreateWithoutSkillInput>
}

export type WorkflowStepCreateManySkillInputEnvelope = {
  data: Prisma.WorkflowStepCreateManySkillInput | Prisma.WorkflowStepCreateManySkillInput[]
}

export type WorkflowStepUpsertWithWhereUniqueWithoutSkillInput = {
  where: Prisma.WorkflowStepWhereUniqueInput
  update: Prisma.XOR<Prisma.WorkflowStepUpdateWithoutSkillInput, Prisma.WorkflowStepUncheckedUpdateWithoutSkillInput>
  create: Prisma.XOR<Prisma.WorkflowStepCreateWithoutSkillInput, Prisma.WorkflowStepUncheckedCreateWithoutSkillInput>
}

export type WorkflowStepUpdateWithWhereUniqueWithoutSkillInput = {
  where: Prisma.WorkflowStepWhereUniqueInput
  data: Prisma.XOR<Prisma.WorkflowStepUpdateWithoutSkillInput, Prisma.WorkflowStepUncheckedUpdateWithoutSkillInput>
}

export type WorkflowStepUpdateManyWithWhereWithoutSkillInput = {
  where: Prisma.WorkflowStepScalarWhereInput
  data: Prisma.XOR<Prisma.WorkflowStepUpdateManyMutationInput, Prisma.WorkflowStepUncheckedUpdateManyWithoutSkillInput>
}

export type WorkflowStepScalarWhereInput = {
  AND?: Prisma.WorkflowStepScalarWhereInput | Prisma.WorkflowStepScalarWhereInput[]
  OR?: Prisma.WorkflowStepScalarWhereInput[]
  NOT?: Prisma.WorkflowStepScalarWhereInput | Prisma.WorkflowStepScalarWhereInput[]
  id?: Prisma.StringFilter<"WorkflowStep"> | string
  workflowId?: Prisma.StringFilter<"WorkflowStep"> | string
  skillId?: Prisma.StringFilter<"WorkflowStep"> | string
  orderIndex?: Prisma.IntFilter<"WorkflowStep"> | number
  config?: Prisma.StringNullableFilter<"WorkflowStep"> | string | null
  label?: Prisma.StringNullableFilter<"WorkflowStep"> | string | null
}

export type WorkflowStepCreateWithoutWorkflowInput = {
  id?: string
  orderIndex: number
  config?: string | null
  label?: string | null
  skill: Prisma.SkillCreateNestedOneWithoutWorkflowStepsInput
}

export type WorkflowStepUncheckedCreateWithoutWorkflowInput = {
  id?: string
  skillId: string
  orderIndex: number
  config?: string | null
  label?: string | null
}

export type WorkflowStepCreateOrConnectWithoutWorkflowInput = {
  where: Prisma.WorkflowStepWhereUniqueInput
  create: Prisma.XOR<Prisma.WorkflowStepCreateWithoutWorkflowInput, Prisma.WorkflowStepUncheckedCreateWithoutWorkflowInput>
}

export type WorkflowStepCreateManyWorkflowInputEnvelope = {
  data: Prisma.WorkflowStepCreateManyWorkflowInput | Prisma.WorkflowStepCreateManyWorkflowInput[]
}

export type WorkflowStepUpsertWithWhereUniqueWithoutWorkflowInput = {
  where: Prisma.WorkflowStepWhereUniqueInput
  update: Prisma.XOR<Prisma.WorkflowStepUpdateWithoutWorkflowInput, Prisma.WorkflowStepUncheckedUpdateWithoutWorkflowInput>
  create: Prisma.XOR<Prisma.WorkflowStepCreateWithoutWorkflowInput, Prisma.WorkflowStepUncheckedCreateWithoutWorkflowInput>
}

export type WorkflowStepUpdateWithWhereUniqueWithoutWorkflowInput = {
  where: Prisma.WorkflowStepWhereUniqueInput
  data: Prisma.XOR<Prisma.WorkflowStepUpdateWithoutWorkflowInput, Prisma.WorkflowStepUncheckedUpdateWithoutWorkflowInput>
}

export type WorkflowStepUpdateManyWithWhereWithoutWorkflowInput = {
  where: Prisma.WorkflowStepScalarWhereInput
  data: Prisma.XOR<Prisma.WorkflowStepUpdateManyMutationInput, Prisma.WorkflowStepUncheckedUpdateManyWithoutWorkflowInput>
}

export type WorkflowStepCreateManySkillInput = {
  id?: string
  workflowId: string
  orderIndex: number
  config?: string | null
  label?: string | null
}

export type WorkflowStepUpdateWithoutSkillInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  orderIndex?: Prisma.IntFieldUpdateOperationsInput | number
  config?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  label?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  workflow?: Prisma.WorkflowUpdateOneRequiredWithoutStepsNestedInput
}

export type WorkflowStepUncheckedUpdateWithoutSkillInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  workflowId?: Prisma.StringFieldUpdateOperationsInput | string
  orderIndex?: Prisma.IntFieldUpdateOperationsInput | number
  config?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  label?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type WorkflowStepUncheckedUpdateManyWithoutSkillInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  workflowId?: Prisma.StringFieldUpdateOperationsInput | string
  orderIndex?: Prisma.IntFieldUpdateOperationsInput | number
  config?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  label?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type WorkflowStepCreateManyWorkflowInput = {
  id?: string
  skillId: string
  orderIndex: number
  config?: string | null
  label?: string | null
}

export type WorkflowStepUpdateWithoutWorkflowInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  orderIndex?: Prisma.IntFieldUpdateOperationsInput | number
  config?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  label?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  skill?: Prisma.SkillUpdateOneRequiredWithoutWorkflowStepsNestedInput
}

export type WorkflowStepUncheckedUpdateWithoutWorkflowInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  skillId?: Prisma.StringFieldUpdateOperationsInput | string
  orderIndex?: Prisma.IntFieldUpdateOperationsInput | number
  config?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  label?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type WorkflowStepUncheckedUpdateManyWithoutWorkflowInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  skillId?: Prisma.StringFieldUpdateOperationsInput | string
  orderIndex?: Prisma.IntFieldUpdateOperationsInput | number
  config?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  label?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}



export type WorkflowStepSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  workflowId?: boolean
  skillId?: boolean
  orderIndex?: boolean
  config?: boolean
  label?: boolean
  workflow?: boolean | Prisma.WorkflowDefaultArgs<ExtArgs>
  skill?: boolean | Prisma.SkillDefaultArgs<ExtArgs>
}, ExtArgs["result"]["workflowStep"]>

export type WorkflowStepSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  workflowId?: boolean
  skillId?: boolean
  orderIndex?: boolean
  config?: boolean
  label?: boolean
  workflow?: boolean | Prisma.WorkflowDefaultArgs<ExtArgs>
  skill?: boolean | Prisma.SkillDefaultArgs<ExtArgs>
}, ExtArgs["result"]["workflowStep"]>

export type WorkflowStepSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  workflowId?: boolean
  skillId?: boolean
  orderIndex?: boolean
  config?: boolean
  label?: boolean
  workflow?: boolean | Prisma.WorkflowDefaultArgs<ExtArgs>
  skill?: boolean | Prisma.SkillDefaultArgs<ExtArgs>
}, ExtArgs["result"]["workflowStep"]>

export type WorkflowStepSelectScalar = {
  id?: boolean
  workflowId?: boolean
  skillId?: boolean
  orderIndex?: boolean
  config?: boolean
  label?: boolean
}

export type WorkflowStepOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "workflowId" | "skillId" | "orderIndex" | "config" | "label", ExtArgs["result"]["workflowStep"]>
export type WorkflowStepInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  workflow?: boolean | Prisma.WorkflowDefaultArgs<ExtArgs>
  skill?: boolean | Prisma.SkillDefaultArgs<ExtArgs>
}
export type WorkflowStepIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  workflow?: boolean | Prisma.WorkflowDefaultArgs<ExtArgs>
  skill?: boolean | Prisma.SkillDefaultArgs<ExtArgs>
}
export type WorkflowStepIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  workflow?: boolean | Prisma.WorkflowDefaultArgs<ExtArgs>
  skill?: boolean | Prisma.SkillDefaultArgs<ExtArgs>
}

export type $WorkflowStepPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "WorkflowStep"
  objects: {
    workflow: Prisma.$WorkflowPayload<ExtArgs>
    skill: Prisma.$SkillPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    workflowId: string
    skillId: string
    orderIndex: number
    config: string | null
    label: string | null
  }, ExtArgs["result"]["workflowStep"]>
  composites: {}
}

export type WorkflowStepGetPayload<S extends boolean | null | undefined | WorkflowStepDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$WorkflowStepPayload, S>

export type WorkflowStepCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<WorkflowStepFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: WorkflowStepCountAggregateInputType | true
  }

export interface WorkflowStepDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['WorkflowStep'], meta: { name: 'WorkflowStep' } }
  /**
   * Find zero or one WorkflowStep that matches the filter.
   * @param {WorkflowStepFindUniqueArgs} args - Arguments to find a WorkflowStep
   * @example
   * // Get one WorkflowStep
   * const workflowStep = await prisma.workflowStep.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends WorkflowStepFindUniqueArgs>(args: Prisma.SelectSubset<T, WorkflowStepFindUniqueArgs<ExtArgs>>): Prisma.Prisma__WorkflowStepClient<runtime.Types.Result.GetResult<Prisma.$WorkflowStepPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one WorkflowStep that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {WorkflowStepFindUniqueOrThrowArgs} args - Arguments to find a WorkflowStep
   * @example
   * // Get one WorkflowStep
   * const workflowStep = await prisma.workflowStep.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends WorkflowStepFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, WorkflowStepFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__WorkflowStepClient<runtime.Types.Result.GetResult<Prisma.$WorkflowStepPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first WorkflowStep that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkflowStepFindFirstArgs} args - Arguments to find a WorkflowStep
   * @example
   * // Get one WorkflowStep
   * const workflowStep = await prisma.workflowStep.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends WorkflowStepFindFirstArgs>(args?: Prisma.SelectSubset<T, WorkflowStepFindFirstArgs<ExtArgs>>): Prisma.Prisma__WorkflowStepClient<runtime.Types.Result.GetResult<Prisma.$WorkflowStepPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first WorkflowStep that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkflowStepFindFirstOrThrowArgs} args - Arguments to find a WorkflowStep
   * @example
   * // Get one WorkflowStep
   * const workflowStep = await prisma.workflowStep.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends WorkflowStepFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, WorkflowStepFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__WorkflowStepClient<runtime.Types.Result.GetResult<Prisma.$WorkflowStepPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more WorkflowSteps that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkflowStepFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all WorkflowSteps
   * const workflowSteps = await prisma.workflowStep.findMany()
   * 
   * // Get first 10 WorkflowSteps
   * const workflowSteps = await prisma.workflowStep.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const workflowStepWithIdOnly = await prisma.workflowStep.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends WorkflowStepFindManyArgs>(args?: Prisma.SelectSubset<T, WorkflowStepFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WorkflowStepPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a WorkflowStep.
   * @param {WorkflowStepCreateArgs} args - Arguments to create a WorkflowStep.
   * @example
   * // Create one WorkflowStep
   * const WorkflowStep = await prisma.workflowStep.create({
   *   data: {
   *     // ... data to create a WorkflowStep
   *   }
   * })
   * 
   */
  create<T extends WorkflowStepCreateArgs>(args: Prisma.SelectSubset<T, WorkflowStepCreateArgs<ExtArgs>>): Prisma.Prisma__WorkflowStepClient<runtime.Types.Result.GetResult<Prisma.$WorkflowStepPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many WorkflowSteps.
   * @param {WorkflowStepCreateManyArgs} args - Arguments to create many WorkflowSteps.
   * @example
   * // Create many WorkflowSteps
   * const workflowStep = await prisma.workflowStep.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends WorkflowStepCreateManyArgs>(args?: Prisma.SelectSubset<T, WorkflowStepCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many WorkflowSteps and returns the data saved in the database.
   * @param {WorkflowStepCreateManyAndReturnArgs} args - Arguments to create many WorkflowSteps.
   * @example
   * // Create many WorkflowSteps
   * const workflowStep = await prisma.workflowStep.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many WorkflowSteps and only return the `id`
   * const workflowStepWithIdOnly = await prisma.workflowStep.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends WorkflowStepCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, WorkflowStepCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WorkflowStepPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a WorkflowStep.
   * @param {WorkflowStepDeleteArgs} args - Arguments to delete one WorkflowStep.
   * @example
   * // Delete one WorkflowStep
   * const WorkflowStep = await prisma.workflowStep.delete({
   *   where: {
   *     // ... filter to delete one WorkflowStep
   *   }
   * })
   * 
   */
  delete<T extends WorkflowStepDeleteArgs>(args: Prisma.SelectSubset<T, WorkflowStepDeleteArgs<ExtArgs>>): Prisma.Prisma__WorkflowStepClient<runtime.Types.Result.GetResult<Prisma.$WorkflowStepPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one WorkflowStep.
   * @param {WorkflowStepUpdateArgs} args - Arguments to update one WorkflowStep.
   * @example
   * // Update one WorkflowStep
   * const workflowStep = await prisma.workflowStep.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends WorkflowStepUpdateArgs>(args: Prisma.SelectSubset<T, WorkflowStepUpdateArgs<ExtArgs>>): Prisma.Prisma__WorkflowStepClient<runtime.Types.Result.GetResult<Prisma.$WorkflowStepPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more WorkflowSteps.
   * @param {WorkflowStepDeleteManyArgs} args - Arguments to filter WorkflowSteps to delete.
   * @example
   * // Delete a few WorkflowSteps
   * const { count } = await prisma.workflowStep.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends WorkflowStepDeleteManyArgs>(args?: Prisma.SelectSubset<T, WorkflowStepDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more WorkflowSteps.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkflowStepUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many WorkflowSteps
   * const workflowStep = await prisma.workflowStep.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends WorkflowStepUpdateManyArgs>(args: Prisma.SelectSubset<T, WorkflowStepUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more WorkflowSteps and returns the data updated in the database.
   * @param {WorkflowStepUpdateManyAndReturnArgs} args - Arguments to update many WorkflowSteps.
   * @example
   * // Update many WorkflowSteps
   * const workflowStep = await prisma.workflowStep.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more WorkflowSteps and only return the `id`
   * const workflowStepWithIdOnly = await prisma.workflowStep.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends WorkflowStepUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, WorkflowStepUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$WorkflowStepPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one WorkflowStep.
   * @param {WorkflowStepUpsertArgs} args - Arguments to update or create a WorkflowStep.
   * @example
   * // Update or create a WorkflowStep
   * const workflowStep = await prisma.workflowStep.upsert({
   *   create: {
   *     // ... data to create a WorkflowStep
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the WorkflowStep we want to update
   *   }
   * })
   */
  upsert<T extends WorkflowStepUpsertArgs>(args: Prisma.SelectSubset<T, WorkflowStepUpsertArgs<ExtArgs>>): Prisma.Prisma__WorkflowStepClient<runtime.Types.Result.GetResult<Prisma.$WorkflowStepPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of WorkflowSteps.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkflowStepCountArgs} args - Arguments to filter WorkflowSteps to count.
   * @example
   * // Count the number of WorkflowSteps
   * const count = await prisma.workflowStep.count({
   *   where: {
   *     // ... the filter for the WorkflowSteps we want to count
   *   }
   * })
  **/
  count<T extends WorkflowStepCountArgs>(
    args?: Prisma.Subset<T, WorkflowStepCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], WorkflowStepCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a WorkflowStep.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkflowStepAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends WorkflowStepAggregateArgs>(args: Prisma.Subset<T, WorkflowStepAggregateArgs>): Prisma.PrismaPromise<GetWorkflowStepAggregateType<T>>

  /**
   * Group by WorkflowStep.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {WorkflowStepGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends WorkflowStepGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: WorkflowStepGroupByArgs['orderBy'] }
      : { orderBy?: WorkflowStepGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, WorkflowStepGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetWorkflowStepGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the WorkflowStep model
 */
readonly fields: WorkflowStepFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for WorkflowStep.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__WorkflowStepClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  workflow<T extends Prisma.WorkflowDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.WorkflowDefaultArgs<ExtArgs>>): Prisma.Prisma__WorkflowClient<runtime.Types.Result.GetResult<Prisma.$WorkflowPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  skill<T extends Prisma.SkillDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.SkillDefaultArgs<ExtArgs>>): Prisma.Prisma__SkillClient<runtime.Types.Result.GetResult<Prisma.$SkillPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the WorkflowStep model
 */
export interface WorkflowStepFieldRefs {
  readonly id: Prisma.FieldRef<"WorkflowStep", 'String'>
  readonly workflowId: Prisma.FieldRef<"WorkflowStep", 'String'>
  readonly skillId: Prisma.FieldRef<"WorkflowStep", 'String'>
  readonly orderIndex: Prisma.FieldRef<"WorkflowStep", 'Int'>
  readonly config: Prisma.FieldRef<"WorkflowStep", 'String'>
  readonly label: Prisma.FieldRef<"WorkflowStep", 'String'>
}
    

// Custom InputTypes
/**
 * WorkflowStep findUnique
 */
export type WorkflowStepFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkflowStep
   */
  select?: Prisma.WorkflowStepSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkflowStep
   */
  omit?: Prisma.WorkflowStepOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkflowStepInclude<ExtArgs> | null
  /**
   * Filter, which WorkflowStep to fetch.
   */
  where: Prisma.WorkflowStepWhereUniqueInput
}

/**
 * WorkflowStep findUniqueOrThrow
 */
export type WorkflowStepFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkflowStep
   */
  select?: Prisma.WorkflowStepSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkflowStep
   */
  omit?: Prisma.WorkflowStepOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkflowStepInclude<ExtArgs> | null
  /**
   * Filter, which WorkflowStep to fetch.
   */
  where: Prisma.WorkflowStepWhereUniqueInput
}

/**
 * WorkflowStep findFirst
 */
export type WorkflowStepFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkflowStep
   */
  select?: Prisma.WorkflowStepSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkflowStep
   */
  omit?: Prisma.WorkflowStepOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkflowStepInclude<ExtArgs> | null
  /**
   * Filter, which WorkflowStep to fetch.
   */
  where?: Prisma.WorkflowStepWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WorkflowSteps to fetch.
   */
  orderBy?: Prisma.WorkflowStepOrderByWithRelationInput | Prisma.WorkflowStepOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for WorkflowSteps.
   */
  cursor?: Prisma.WorkflowStepWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WorkflowSteps from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WorkflowSteps.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of WorkflowSteps.
   */
  distinct?: Prisma.WorkflowStepScalarFieldEnum | Prisma.WorkflowStepScalarFieldEnum[]
}

/**
 * WorkflowStep findFirstOrThrow
 */
export type WorkflowStepFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkflowStep
   */
  select?: Prisma.WorkflowStepSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkflowStep
   */
  omit?: Prisma.WorkflowStepOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkflowStepInclude<ExtArgs> | null
  /**
   * Filter, which WorkflowStep to fetch.
   */
  where?: Prisma.WorkflowStepWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WorkflowSteps to fetch.
   */
  orderBy?: Prisma.WorkflowStepOrderByWithRelationInput | Prisma.WorkflowStepOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for WorkflowSteps.
   */
  cursor?: Prisma.WorkflowStepWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WorkflowSteps from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WorkflowSteps.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of WorkflowSteps.
   */
  distinct?: Prisma.WorkflowStepScalarFieldEnum | Prisma.WorkflowStepScalarFieldEnum[]
}

/**
 * WorkflowStep findMany
 */
export type WorkflowStepFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkflowStep
   */
  select?: Prisma.WorkflowStepSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkflowStep
   */
  omit?: Prisma.WorkflowStepOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkflowStepInclude<ExtArgs> | null
  /**
   * Filter, which WorkflowSteps to fetch.
   */
  where?: Prisma.WorkflowStepWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of WorkflowSteps to fetch.
   */
  orderBy?: Prisma.WorkflowStepOrderByWithRelationInput | Prisma.WorkflowStepOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing WorkflowSteps.
   */
  cursor?: Prisma.WorkflowStepWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` WorkflowSteps from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` WorkflowSteps.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of WorkflowSteps.
   */
  distinct?: Prisma.WorkflowStepScalarFieldEnum | Prisma.WorkflowStepScalarFieldEnum[]
}

/**
 * WorkflowStep create
 */
export type WorkflowStepCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkflowStep
   */
  select?: Prisma.WorkflowStepSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkflowStep
   */
  omit?: Prisma.WorkflowStepOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkflowStepInclude<ExtArgs> | null
  /**
   * The data needed to create a WorkflowStep.
   */
  data: Prisma.XOR<Prisma.WorkflowStepCreateInput, Prisma.WorkflowStepUncheckedCreateInput>
}

/**
 * WorkflowStep createMany
 */
export type WorkflowStepCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many WorkflowSteps.
   */
  data: Prisma.WorkflowStepCreateManyInput | Prisma.WorkflowStepCreateManyInput[]
}

/**
 * WorkflowStep createManyAndReturn
 */
export type WorkflowStepCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkflowStep
   */
  select?: Prisma.WorkflowStepSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the WorkflowStep
   */
  omit?: Prisma.WorkflowStepOmit<ExtArgs> | null
  /**
   * The data used to create many WorkflowSteps.
   */
  data: Prisma.WorkflowStepCreateManyInput | Prisma.WorkflowStepCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkflowStepIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * WorkflowStep update
 */
export type WorkflowStepUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkflowStep
   */
  select?: Prisma.WorkflowStepSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkflowStep
   */
  omit?: Prisma.WorkflowStepOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkflowStepInclude<ExtArgs> | null
  /**
   * The data needed to update a WorkflowStep.
   */
  data: Prisma.XOR<Prisma.WorkflowStepUpdateInput, Prisma.WorkflowStepUncheckedUpdateInput>
  /**
   * Choose, which WorkflowStep to update.
   */
  where: Prisma.WorkflowStepWhereUniqueInput
}

/**
 * WorkflowStep updateMany
 */
export type WorkflowStepUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update WorkflowSteps.
   */
  data: Prisma.XOR<Prisma.WorkflowStepUpdateManyMutationInput, Prisma.WorkflowStepUncheckedUpdateManyInput>
  /**
   * Filter which WorkflowSteps to update
   */
  where?: Prisma.WorkflowStepWhereInput
  /**
   * Limit how many WorkflowSteps to update.
   */
  limit?: number
}

/**
 * WorkflowStep updateManyAndReturn
 */
export type WorkflowStepUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkflowStep
   */
  select?: Prisma.WorkflowStepSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the WorkflowStep
   */
  omit?: Prisma.WorkflowStepOmit<ExtArgs> | null
  /**
   * The data used to update WorkflowSteps.
   */
  data: Prisma.XOR<Prisma.WorkflowStepUpdateManyMutationInput, Prisma.WorkflowStepUncheckedUpdateManyInput>
  /**
   * Filter which WorkflowSteps to update
   */
  where?: Prisma.WorkflowStepWhereInput
  /**
   * Limit how many WorkflowSteps to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkflowStepIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * WorkflowStep upsert
 */
export type WorkflowStepUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkflowStep
   */
  select?: Prisma.WorkflowStepSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkflowStep
   */
  omit?: Prisma.WorkflowStepOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkflowStepInclude<ExtArgs> | null
  /**
   * The filter to search for the WorkflowStep to update in case it exists.
   */
  where: Prisma.WorkflowStepWhereUniqueInput
  /**
   * In case the WorkflowStep found by the `where` argument doesn't exist, create a new WorkflowStep with this data.
   */
  create: Prisma.XOR<Prisma.WorkflowStepCreateInput, Prisma.WorkflowStepUncheckedCreateInput>
  /**
   * In case the WorkflowStep was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.WorkflowStepUpdateInput, Prisma.WorkflowStepUncheckedUpdateInput>
}

/**
 * WorkflowStep delete
 */
export type WorkflowStepDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkflowStep
   */
  select?: Prisma.WorkflowStepSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkflowStep
   */
  omit?: Prisma.WorkflowStepOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkflowStepInclude<ExtArgs> | null
  /**
   * Filter which WorkflowStep to delete.
   */
  where: Prisma.WorkflowStepWhereUniqueInput
}

/**
 * WorkflowStep deleteMany
 */
export type WorkflowStepDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which WorkflowSteps to delete
   */
  where?: Prisma.WorkflowStepWhereInput
  /**
   * Limit how many WorkflowSteps to delete.
   */
  limit?: number
}

/**
 * WorkflowStep without action
 */
export type WorkflowStepDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WorkflowStep
   */
  select?: Prisma.WorkflowStepSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WorkflowStep
   */
  omit?: Prisma.WorkflowStepOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WorkflowStepInclude<ExtArgs> | null
}
